### ISSUE TITLE
Change default dark theme

### ISSUE THREAD

**Issue by ehuss** [rust-lang/mdBook#1054]
#1037 added the ability to support automatic dark theme detection.  The default wasn't changed to avoid potentially breaking anyone with custom themes.  This issue is to track changing the default to one of the dark themes as a breaking change in 0.4.

**Comment by Flying-Toast** [comment]
Reminder to change the documentation too when this happens:
https://github.com/rust-lang-nursery/mdBook/blob/d63ef8330dfea202116bfef525e1ccac20f1fab7/src/config.rs#L444
https://github.com/rust-lang-nursery/mdBook/blob/d63ef8330dfea202116bfef525e1ccac20f1fab7/book-example/src/format/config.md#L156
