### ISSUE TITLE
Sidebar can't scroll to current active section

### ISSUE THREAD

**Issue by ngolin** [rust-lang/mdBook#1067]
Sidebar on the left can't auto scroll to the current active section. This is something to do with the `book.js`. I'm ready to propose a PR.

**Comment by mrec** [comment]
Hi - I'm not an mdBook maintainer and have no authoritah over PRs, but wanted to mention that `scrollIntoViewIfNeeded` is [nonstandard and very poorly supported](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded). Does the standard [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) not work here?

**Comment by ngolin** [comment]
> Hi - I'm not an mdBook maintainer and have no authoritah over PRs, but wanted to mention that `scrollIntoViewIfNeeded` is [nonstandard and very poorly supported](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded). Does the standard [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) not work here?

Now it's `.scrollIntoView({ block: 'center' });`.

**Comment by ehuss** [comment]
I think this should be more-or-less fixed with #1052 and #1161.
