### ISSUE TITLE
Error in hiding part of an example

### ISSUE THREAD

**Issue by sebastianv89** [rust-lang/mdBook#1091]
See the last example in this section: https://rust-lang.github.io/mdBook/format/mdbook.html#including-a-file-but-initially-hiding-all-except-specified-lines
It has not hidden one of the leading # symbols. This is not just less pretty, but it also breaks running the code on the playground. See the following screenshot.

![screenshot](https://user-images.githubusercontent.com/3017046/68420151-b51d1f80-0169-11ea-808e-1875a3144487.png)

When expanding the code (as you can see in the below screenshot), it appears that the issues is with the # on an empty line:
![screenshot expanded](https://user-images.githubusercontent.com/3017046/68420341-24930f00-016a-11ea-84cf-f968d8d52987.png)

**Comment by ehuss** [comment]
Thanks for the report. This has been fixed in #1088, and I'll probably make a new release soonish.
