### ISSUE TITLE
additional-js files must be in root directory?

### ISSUE THREAD

**Issue by JoshOrndorff** [rust-lang/mdBook#1111]
I'm using `additional-js` to include some google analytics and consent items. I would like those scripts to live in a dedicated directory, but they will not load from anywhere other than the root.

`additional-js = ["static/js/load.js", "static/js/config.js", "static/js/klaro.min.js"]`

We've had to make this patch to work around the issue https://github.com/substrate-developer-hub/recipes/pull/54

**Comment by ehuss** [comment]
It seems to work for me.  Can you say more about what was wrong?

Also, it looks like your project has already moved them back to a dedicated folder via https://github.com/substrate-developer-hub/recipes/pull/87?

**Comment by JoshOrndorff** [comment]
Indeed they were moved back to the subdirectory, and thus the scripts no longer load.

When I load the live site (substrate.dev/recipes), the "can we use cookies" dialog does not show and my console says `Loading failed for the <script> with source "https://substrate.dev/recipes/klaro.min.js".`

It is trying to load that script from the root even though `book.toml` points to [a different location](https://github.com/substrate-developer-hub/recipes/blob/master/book.toml#L12)

**Comment by ehuss** [comment]
Oh!  It looks like you're using an [old version](https://github.com/substrate-developer-hub/recipes/blob/4c5b927e250084adbf475ccc665659308a1a33d7/.travis.yml#L6) of mdbook.  I think this was fixed a while ago (#796).  Can you try the latest version (0.3.5)?

**Comment by JoshOrndorff** [comment]
Thank you for your time finding this issue!
