### ISSUE TITLE
Apply selected theme to all pages when viewing mdBook locally (file:///) in Firefox

### ISSUE THREAD

**Issue by 20k-ultra** [rust-lang/mdBook#1112]
When I select a theme and navigate to another page the theme is not persisted. This is because mdBooks stores the selected theme in localStorage but since these files are being served locally via file:/// each file is treated as its own domain and so the theme selected is only available to the HTML page that set the value. 

I've successfully created a way to persist the theme across all pages using sessionStorage. I'd like to create a PR with this mechanism implemented but would like to hear feedback first. My plan is to create standard functions for handling the themes such as setting, remembering, getting, and applying. This way the getting theme code can handle the complexity of checking sessionStorage then localStorage then defaulting to the default theme. 

The potential risks to consider is that sessionStorage is available to all javascript to access which could make another script/website override the mdbook-theme of your site. For example, imagine viewing a mdBook on rust-lang.org domain and another on crates.io. If you set the theme on crates.io it would then apply to rust-lang.org since the priority is to look at sessionStorage for remembered themes selected. Meaning when you select another page on rust-lang.org the mdBook will apply the theme you picked on crates.io.

A solution for this problem is only use sessionStorage when mdBook is being served via file:///. This means mdBook will perform correctly for each domain and run the same as it is today but for people using the offline docs from rustup they will be able to have the theme they picked consistently be applied.

I made a [gist](https://gist.github.com/20k-ultra/41edc0c131ae206c9fcf9a222b19c709) of my current code just to give a better idea if what I'm explaining isn't clear. I'll have to add the logic to only check sessionStorage if mdBook is being served locally. 

One last gotcha is sessionStorage is only used for the life of the browser session. Once it is closed then the values are lost. That's ok though since if we set the theme and navigate around a mdBook it will set the localStorage value for each of these files as the user browses. When they return it will again set the theme into sessionStorage since the theme was persisted in localStorage too! In the off chance they close their browser and open a never before seen page in mdBook they would just have to set the theme again which is much better then the current situation.

**Comment by 20k-ultra** [comment]
I think since this problem only exists for people that view books locally then it should only work when viewing locally. I saw in the code that google analytics code is only added if the user is not locally viewing the book so this logic exists already.

I'm working on this now and will just make PR when it's done.

**Comment by 20k-ultra** [comment]
Ok, discovered a few things. One, Chrome shares localStorage across the file:/// "domain" so this problem doesn't exist for Chrome users however I only use Firefox and just have Chrome to test behavior between browsers.

And so in Firefox my change to mdBook successfully creates a book that will persist the selected theme when viewing locally. I know this because I will compile mdBook then make [the book](https://github.com/rust-lang/book) which previously when loaded from rustup doc it wouldn't persist the theme I selected across pages but my new mdBook build does!

Great, but then I tried the book-example provided in this repo and it doesn't work. I don't know if this is a bug with Firefox though or something in my code but the sessionStorage gets cleared when the file path changes.

I know this because the rust-lang book I built with my customized mdBook all the pages are in the same path just different files. For example:

**file:///home/mig/Projects/mdBook/rust-book/book/**ch04-02-references-and-borrowing.html
**file:///home/mig/Projects/mdBook/rust-book/book/**ch04-03-slices.html
**file:///home/mig/Projects/mdBook/rust-book/book/**ch05-00-structs.html

And the theme is persisted for all of these. But the example-book sessionStorage changes when the path in the url changes. For example:

**file:///home/mig/Projects/mdBook/book-example/book/format/**summary.html
**file:///home/mig/Projects/mdBook/book-example/book/format/**config.html
**file:///home/mig/Projects/mdBook/book-example/book/for_developers/**index.html

The file paths in these links change and sessionStorage is not persisted across them. 

I'll keep playing around this this.

**Comment by 20k-ultra** [comment]
I am currently playing around with using cookies. Maybe the cookie implementation will persist across file:/// "domains". I'll have an update later today.

**Comment by SpicyRicecaker** [comment]
I think that this local storage behavior on Firefox was implemented due to security reasons, see the Firefox docs on [Reason: CORS request not HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp).

So setting the flag in about:config `privacy.file_unique_origin` to `false` while viewing the book using the file protocol should persist themes, but it does have some security implications.

**Comment by ntc2** [comment]
I have this problem with Firefox 114.0, but not with Chrome 114.0.5735.90.

**Comment by 20k-ultra** [comment]
I [mentioned](https://github.com/rust-lang/mdBook/pull/1115#issuecomment-566104663) in my PR to fix this issue that the issue was specific to my browser setup and that this worked in other version of Firefox (specifically the non-developer version).

I never found what specifically about my browser was causing this issue. I have a pretty aggressive set of extensions installed for privacy so it might have been one of those. I also messed with FF settings so it could have been that.

sorry @ntc2!
