### ISSUE TITLE
Search highlightning breaks inline code segments with '-' character

### ISSUE THREAD

**Issue by antipin00** [rust-lang/mdBook#1113]
Inline code segments that have '-' character break when searching for a string if the code segment ends with this string. [Example](https://doc.rust-lang.org/cargo/reference/unstable.html?highlight=tures#namespaced-features), [another example](https://doc.rust-lang.org/cargo/reference/unstable.html?highlight=ofile#config-profiles)
![broken_code_segment](https://user-images.githubusercontent.com/17460779/70633016-e3968a80-1c40-11ea-8d9f-d67bbc1789fc.png)
Firefox 71.0 x64 on Kubuntu 19.10

**Comment by ehuss** [comment]
Thanks for the report. This has already been fixed (via #1058 I think).  The fix is currently on Rust's beta channel (which should hit stable next week).
