### ISSUE TITLE
update the mdBook Documentation for author to fix menu-title render

### ISSUE THREAD

**Issue by stardussttx** [rust-lang/mdBook#1118]
![image](https://user-images.githubusercontent.com/58855704/71105921-541d4880-21f9-11ea-9320-fbb507af0b07.png)

https://github.com/stardussttx/mao-sama-retry

**Comment by ehuss** [comment]
Can you provide more information?  I visited the site at the url given and I see:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/43198/71327573-14878280-24bf-11ea-93c2-76c8a4d2ceb7.png">

**Comment by stardussttx** [comment]
I use Environment Variables in Travis CI let it output title, it doesn't work if you set book title in book.toml.

**Comment by stardussttx** [comment]
![Screenshot_20191226-121525_Chrome](https://user-images.githubusercontent.com/58855704/71457565-799de980-27d9-11ea-8a00-c87163cf58c3.png)

**Comment by ehuss** [comment]
Ah, I see the problem.  The `authors` field needs to be an array of strings.  

It's a bug that mdBook is not displaying a warning or error message.

**Comment by stardussttx** [comment]
It works .
***
[book]
title = "魔王大人、RETRY！"
**authors = ["神埼黑音"]**
***
I think we need to update the mdBook Documentation ?
***
[book]
title = "Example book"
**author = "John Doe"**
description = "The example book covers examples."
***

**Comment by stardussttx** [comment]
And close https://github.com/rust-lang/mdBook/issues/596

**Comment by ehuss** [comment]
mdbook will now generate an error when `authors` is a string via #1539.
