### ISSUE TITLE
Feature request: Usability nitpick for the sidebar.

### ISSUE THREAD

**Issue by cjayross** [rust-lang/mdBook#1119]
When using mdBook generated sites, I am very frequently jumping around to different sections outlined in the sidebar. The issue is that every time a page is loaded, the sidebar resets to it's default position—meaning that I have to scroll down to where I was every time I go to a new section, which can be frustrating.

Just my two cents.

**Comment by ehuss** [comment]
I'm not sure if I'm following correctly, but I think that has been fixed (#1052).  Which version of mdbook are you using?  Which browser?  The sidebar should now have the selected page appear at the top.

**Comment by cjayross** [comment]
You're right, that does look consistent with what I'm looking for. I'm on chromium. It must be that a few books I've been looking at are out of date.

**Comment by ehuss** [comment]
Ok, closing then as I think this is fixed.
