### ISSUE TITLE
Is the sliding behaviour of left side menu correct?

### ISSUE THREAD

**Issue by mobop** [rust-lang/mdBook#1121]
I except it to behave like material design on mobile. It should on top of the main content, like gitbook. Currently if you zoom out while menu is open on mobile you can see the whole page.

**Comment by mobop** [comment]
@alexcrichton ?

**Comment by mobop** [comment]
@nikomatsakis

**Comment by Dylan-DPC** [comment]
@mobop please do not mention people (especially those who aren't maintainers of the project)
