### ISSUE TITLE
Can't compile v0.3.5 today

### ISSUE THREAD

**Issue by leudz** [rust-lang/mdBook#1124]
Hi! First, thank you for this crate, it's awesome!

I use it to make a user guide for a crate but today I pushed some code (not part of the guide) and since then mdbook fails to compile.

<details>
<summary>Error</summary>

    Compiling mdbook v0.3.5
    error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-0.3.5/src/lib.rs:123:5
        |
    123 | /     error_chain! {
    124 | |         foreign_links {
    125 | |             Io(std::io::Error) #[doc = "A wrapper around `std::io::Error`"];
    126 | |             HandlebarsRender(handlebars::RenderError) #[doc = "Handlebars rendering failed"];
    ...   |
    156 | |         }
    157 | |     }
        | |_____^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
        |
        = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
        = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
        = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
        = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
        = note: required because it appears within the type `handlebars::error::RenderError`
        = note: required because it appears within the type `errors::ErrorKind`
        = note: required because it appears within the type `errors::Error`
        = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

</details>

v0.3.5 is out since November and it compiled fine yesterday so I went through the dependencies and handlebars went from v2.0.2 to v2.0.3. It's the only change.

**Comment by SteVwonder** [comment]
Thanks @leudz for documenting this and tracking down the root cause! Saved me a lot of time today 😄 

FWIW to anyone else stumbling across this via searching, I temporarily worked around the problem by doing `cargo install --locked mdbook` since the upstream Cargo.lock still has handlbars v2.0.2 in it.

**Comment by Dylan-DPC** [comment]
2.0.3 is yanked so you shouldn't be having this problem. Can you do a fresh install and confirm?

**Comment by SteVwonder** [comment]
> Can you do a fresh install and confirm?

Works perfectly now.  Thanks!
