### ISSUE TITLE
ignore files in the output directory

### ISSUE THREAD

**Issue by ctaggart** [rust-lang/mdBook#1126]
Is there a way to have `mdbook serve` ignore a list of files in the output directory and not remove them? I want it to ignore the `.git` folder. The output folder is a separate .git repository.

**Comment by segfaultsourcery** [comment]
I just went hunting in the code, and I don't believe there's any way to turn this off, as [the entire folder is deleted and recreated by the renderer](https://github.com/rust-lang/mdBook/blob/1f505c2b2eecac73751b57496ee6dc33c91ffa6b/src/renderer/html_handlebars/hbs_renderer.rs#L291).

Would it be possible for you to create the git repository in the parent directory instead? That would completely sidestep the issue.

**Comment by ctaggart** [comment]
Thanks for looking into it.
