### ISSUE TITLE
Code block using the "async" keyword causes compilation failure

### ISSUE THREAD

**Issue by cfsamson** [rust-lang/mdBook#1134]
Using any code using the `async` keyword inside a runnable code block, or using `include` or `playpen` directives to pull in a file containing code which contains the `async` keyword, generates a compiler error even though the code compiles and runs as expected on the playground.

## Steps to reproduce

1. create a new directories and `mdbook init`
2. Paste in the following to `chapter_1.md`:

```rust
```

If you run `mdbook test`, or build the book and try to run the example, it will fail giving the error message:
```
  Compiling playground v0.0.1 (/playground)
error: expected one of `,` or `}`, found `!`
 --> src/main.rs:3:16
  |
2 |     let fut = async {
  |               ----- while parsing this struct
3 |         println!("Hello world!");
  |                ^ expected one of `,` or `}` here

error[E0422]: cannot find struct, variant or union type `async` in this scope
 --> src/main.rs:2:15
  |
2 |     let fut = async {
  |               ^^^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0422`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

For a longer runnable example [I have a playground link to the code that originally caused this issue.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=628bfcd3e5a63fabadc70a645230cace)

**Comment by steveklabnik** [comment]
I believe this is because it's testing with rust 2015, not 2018?

**Comment by cfsamson** [comment]
You're right. Adding `edition2018` to the code block solved it. I assumed that 2018 edition would be the default, and the examples from the `async book` had the following error:

```
Compiling playground v0.0.1 (/playground)
error[E0670]: `async fn` is not permitted in the 2015 edition
 --> src/main.rs:7:1
  |
7 | async fn foo() -> u8 { 5 }
  | ^^^^^
```
So I assumed it was not the edition that was wrong, but it seems the error messages for async blocks and async functions are a bit different, the latter giving a better hint. Thanks for clearing that up so quickly.
