### ISSUE TITLE
[feature request] Expandable sections - Ability to tell that particular section should be hidden by defaut

### ISSUE THREAD

**Issue by fulara** [rust-lang/mdBook#1138]
I think github has feature like this it looks something like this:

You write sth similar to this in your markdown:
```
### Your collapsable section

<!--
Content you want to have hidden by default
-->

```

That would render as:

### Your collapsable section
And then there should be a button that would show this 'Content...' text.

Otherwise the 'Content...' is hidden.

This is useful for attaching logs on the markdown for example

**Comment by mgeier** [comment]
I think you are talking about the HTML element `<details>`, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Example:

````html
<details>
<summary>Click me!</summary>

```
text
text
text
```

</details>
````

... is displayed as (since Github comments allow `<details>` elements):

<details>
<summary>Click me!</summary>

```
text
text
text
```

</details>

**Comment by fulara** [comment]
Wow - thanks. 

I just confirmed that this works.
Closing.
