### ISSUE TITLE
Expose more variables to the templates

### ISSUE THREAD

**Issue by tarvos21** [rust-lang/mdBook#1142]
https://rust-lang.github.io/mdBook/format/theme/index-hbs.html

If I want to add `font-size` and `font-family` data to the `index.hbs`, how could I do? 

How to expose more variables from the `book.toml` configuration file?

Thanks!

**Comment by krisradio** [comment]
Look at the stylesheets referenced in index.hbs. You can add font-size and font-family there. 

        
        <link rel="stylesheet" href="{{ path_to_root }}FontAwesome/css/font-awesome.css">

        ... 

        
        {{#each additional_css}}
        <link rel="stylesheet" href="{{ ../path_to_root }}{{ this }}">
        {{/each}}

Not sure what you mean about book.toml. Those variables are basically just used for building the book, afaik, and won't be prevalent in the final HTML.

**Comment by tarvos21** [comment]
thanks!
