### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by robbie-mac** [rust-lang/mdBook#1143]

**Comment by Dylan-DPC** [comment]
I hope that's not your password 😅

**Comment by robbie-mac** [comment]
It was… not anymore. 😉

That’s the problem with rushing while multitasking… sometimes your cursor isn’t where you think it is, and when you hit enter its too late.

**Comment by robbie-mac** [comment]
Well, it isnt NOW. 😁

That's what I get for rushing and multitasking.
