### ISSUE TITLE
images will not be copied to 'book' if symbolic links are utilized in src folder

### ISSUE THREAD

**Issue by mash-graz** [rust-lang/mdBook#1157]
as we work on a multilingual project and #5 (=multilingual support) is still unsolved, i had to look for a workaround. that's why i worked with two independent trees, each containing: SUMMARY.md, config.tom, and a src folder, but tried to use **symbolic links** for the actual content, which we still maintain in an external repository.

this works for most of the content, but **images will not be copied to the generated `book` folder**.

the pages will be only include broken html links to the location, where the image files should be located.

it doesn't make a difference, if the images themself are realized as symbolic links or just the folders, where they are located. in both cases you will observe the same behavior.

this affects at least the last release of mdbook = v0.3.5

**Comment by fosskers** [comment]
https://github.com/rust-lang/mdBook/issues/708 Does this help?
