### ISSUE TITLE
link to gitbook

### ISSUE THREAD

**Issue by xuejipeng** [rust-lang/mdBook#1158]
Can a project built with mdbook be published to gitbook?

**Comment by krisradio** [comment]
Going off the [GitBook structure](https://github.com/GitbookIO/gitbook/blob/master/docs/structure.md), files are stored in a manner very similar to mdbook. You should be able to [find GitBook files in your home directory](https://github.com/GitbookIO/help.gitbook.com/blob/master/editor/where-are-the-files-stored.md) by default. 

However, mdBook and GitBook have completely different build schemes. And obviously if you build it with one, you won't be using the build from the other. So I don't think it's very practical or even warranted to use both.

**Comment by xuejipeng** [comment]
@krisradio I have posted to my github pages, thx.
