### ISSUE TITLE
Hide line in editable code block

### ISSUE THREAD

**Issue by dalance** [rust-lang/mdBook#1166]
I want to hide a line in editable code block.

````
```rust
# // should be hidden
// aaa
```

```rust, editable
# // should be hidden
// aaa
```
````

The rendering result of mdbook v0.3.5 is below:

![image](https://user-images.githubusercontent.com/4331004/76832168-284b4680-686c-11ea-951b-9ad008872b30.png)

The line in `rust` block is hidden, but the line in `rust,editable` is not.
Is this the expected result?

**Comment by ehuss** [comment]
I believe there's no choice but to show the hidden lines.  The editor needs to contain the full content (ACE doesn't have "hidden line" support, which I'm not even sure what that would mean.)

**Comment by dalance** [comment]
I understand it.
Thanks!
