### ISSUE TITLE
Add ability to disable the Print button and print.html

### ISSUE THREAD

**Issue by DannyBen** [rust-lang/mdBook#1177]
In some cases, I would like to avoid providing an easy way for the reader to simply snatch the entire content as one comfortable PDF. I would love the option to disable the button and of course, the generation of the `print.html` page.

Since [the config documentation page](https://github.com/rust-lang/mdBook/blob/master/book-example/src/format/config.md) does not contain the word "print", I am guessing this feature does not exist.

**Comment by Dylan-DPC** [comment]
Hi. Thanks for the issue. Are you willing to send a PR that makes this change? Thanks

**Comment by ehuss** [comment]
There is already a PR for this at #1169.

**Comment by DannyBen** [comment]
> There is already a PR for this at #1169.

Thank you, didn't think about searching in PRs.
