### ISSUE TITLE
Revert #1135

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/mdBook#1180]
Hey, I upgraded my mdbook and my project stopped building when using `mdbook-0.3.6` because of https://github.com/rust-lang/mdBook/pull/1135. I'm fairly sure its behaviour is incorrect and should be reverted. For some context, in rust-lang teams and projects groups have a meta repository for team coordination (e.g. [rust-lang/lang-team](https://github.com/rust-lang/lang-team)). Some of us also started trying to have this information available through mdbook. As it can be a nicer interface at times especially since it shows a complete tree of contents that you control where as GitHub does not. These repositories are entirely markdown files and doesn't really make sense to have every folder be a subfolder in the `src` directory.

You can see in the [`gh-pages`](https://github.com/rust-lang/project-group-template/tree/gh-pages) branch of [rust-lang/project-group-template](https://github.com/rust-lang/project-group-template/) it doesn't generate recursive copies of itself, it generates a [normal mdbook project](https://rust-lang.github.io/project-group-template/index.html). To me this is a legitimate behaviour that should be allowed.

**Comment by ehuss** [comment]
Sorry, I'm a bit confused.  Is it just not working correctly, or is it giving an error message?  It might be helpful to provide a reproduction, and an explanation of what isn't behaving as expected.  From the given links, I see a template of a book with 4 chapters, and I don't see anything particularly wrong with it.

**Comment by XAMPPRocky** [comment]
@ehuss Sorry, I wrote this late and forgot to include the logs. The project now fails to build with `0.3.6` with `Destination directory cannot be contained in source directory`. https://github.com/rust-lang/project-group-template/runs/556822171#step:3:12
