### ISSUE TITLE
org-mode support?

### ISSUE THREAD

**Issue by karlicoss** [rust-lang/mdBook#1183]
Was wondering, how hard would it be to, in theory, support different input formats, like [org-mode](https://en.wikipedia.org/wiki/Org-mode)? 

I've got a [personal wiki](https://beepb00p.xyz/exobrain) in org-mode and I'm using mdbook + [some hacky scripts](https://github.com/karlicoss/exobrain-compiler/tree/master/src) to convert it into markdown and publish as mdbook. 

While it kind of works, it's a bit overcomplicated and flaky, so I've been wondering that perhaps it's worth having first-class support of org-mode.

Main things I like about mdbook are the search index, incremental search and the navigation sidebar. I could, of course, just reimplement it from scratch. But in case mdbook is already generic enough to relatively easily support alternative input formats, I'd be happy to contribute to it instead.

**Comment by tendant** [comment]
@karlicoss Have you tried https://ox-hugo.scripter.co? It can convert org file to markdown. You might need to clean up exported markdown file to make it work with mdBook.

**Comment by karlicoss** [comment]
@tendant thanks for the link! Yep, have seen it, but haven't found it much different from the standard org-mode exporter into markdown (also requires a bit of cleanup).

**Comment by Michael-F-Bryan** [comment]
@karlicoss. instead of using your own build scripts or other hackiness, have you looked into making your own [preprocessor](https://rust-lang.github.io/mdBook/for_developers/preprocessors.html)?

What you'd need to do is create some script which:

1. reads a blob of JSON from stdin
2. scans through the book to find any chapters who's [`name`](https://docs.rs/mdbook/0.3.7/mdbook/book/struct.Chapter.html#structfield.name) ends in `.org`
3. convert the `contents` from org-mode format to markdown
4. print the result as another blob of JSON

This is nice because it'll integrate with the `mdbook` build process, so everything should *Just Work*.

**Comment by karlicoss** [comment]
@Michael-F-Bryan oh, that looks very neat, I'll check this out! And big thanks for the mentoring offer -- I'll let you know if I have any issues and will send you the final version when I prototype something.

**Comment by richardwesthaver** [comment]
just wanted to put in the +1 for org-mode support :) @karlicoss I appreciate u sharing your hack at it - my current setup for web-sharing stuff uses something similar with a Makefile, calling ox-hugo on the files and building the web content with zola (static site generator).

I'm still learning about mdbook but I was thinking of implementing a markdown handler with this crate: https://github.com/PoiScript/orgize which provides an org syntax parser that implements serde - the source code has some useful tidbits if it's of any use.

Cheers,
Richard

**Comment by chipsenkbeil** [comment]
@Michael-F-Bryan, I wouldn't mind taking a crack a preprocessor, but for [vimwiki](http://vimwiki.github.io/). I spent some time writing [vimwiki-rs](https://github.com/chipsenkbeil/vimwiki-rs), but need to add the ability to output back into markdown. Of the plugins you've written, which would you recommend as the best starting point to model a new preprocessor?

Once I get vimwiki done, I could do the same for orgize unless @richardwesthaver wants to take a crack at it instead.

**Comment by Michael-F-Bryan** [comment]
@chipsenkbeil the best place to start is the [*For Developers*]https://rust-lang.github.io/mdBook/for_developers/index.html) chapter in the *User Guide*. That shows a how you can hook up custom preprocessors and backends.

There is also a [`nop-preprocessor`](https://github.com/rust-lang/mdBook/blob/a64a7b747080dc3cbc9d57aab36d83e609444020/examples/nop-preprocessor.rs) example which goes through the preprocessor machinery then returns the same book unchanged. 

You just need to write code which returns a [`mdbook::book::Book`](https://docs.rs/mdbook/0.4.4/mdbook/book/struct.Book.html) with your desired changes. In this case, converting vimwiki syntax to markdown so it can be rendered by the HTML renderer.

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil the best place to start is the [_For Developers_]https://rust-lang.github.io/mdBook/for_developers/index.html) chapter in the _User Guide_. That shows a how you can hook up custom preprocessors and backends.
> 
> There is also a [`nop-preprocessor`](https://github.com/rust-lang/mdBook/blob/a64a7b747080dc3cbc9d57aab36d83e609444020/examples/nop-preprocessor.rs) example which goes through the preprocessor machinery then returns the same book unchanged.
> 
> You just need to write code which returns a [`mdbook::book::Book`](https://docs.rs/mdbook/0.4.4/mdbook/book/struct.Book.html) with your desired changes. In this case, converting vimwiki syntax to markdown so it can be rendered by the HTML renderer.

Great! That's similar to what I'll looking to support for [adding vimwiki support to cobalt.rs](https://github.com/cobalt-org/cobalt.rs/issues/817), so I can tackle these both at the same time.

**Comment by zim0369** [comment]
Just add support for org files. Please :please:

**Comment by ehuss** [comment]
I'm going to close since it is unlikely that direct support for different input formats will be added at this time. It seems like it shouldn't be too difficult to create an org-mode preprocessor. If someone creates one, be sure to add it to the [third party plugins list](https://github.com/rust-lang/mdBook/wiki/Third-party-plugins).
