### ISSUE TITLE
Add toggle-able checkboxes

### ISSUE THREAD

**Issue by troyerta** [rust-lang/mdBook#1185]
Hi all,

I've run into a use case for mdBook which could very much benefit from checkboxes.

It's nice to mark off your place in a list, or sequence of steps on a page. Is it possible to add something like this with a placeholder marker in mdBook markdown?

Maybe something like {{checkbox}} ? Maybe there is a better suggestion to go with instead?

Please let me know what you all think!

Thanks!

**Comment by ehuss** [comment]
You can use GitHub-style [task lists](https://github.github.com/gfm/#task-list-items-extension-).

```
- [x] foo
  - [ ] bar
  - [x] baz
- [ ] bim
```

renders as:

- [x] foo
  - [ ] bar
  - [x] baz
- [ ] bim

**Comment by troyerta** [comment]
I did not know about this feature - but it seems that they do not produce toggle-able checkboxes.

I'll add "toggling" to the issue title to clarify.

Is there a way to do this? This is for a commonly used list of procedures.

**Comment by bamhm182** [comment]
So the reason that you can't check them is because they're not able to be saved. If you're cool with that and you just need a few checkboxes that will reset every time you visit the page, you can do the following:

1. Add the following to `./book.toml`:
```
[output.html]
additional-js = ["js/enable-checkboxes.js"]
```
2. Put the following in `./js/enable-checkboxes.js`:
```
Array.from(document.getElementsByTagName('input')).map(i => { if (i.type == "checkbox") {i.disabled = false}})
```

Your mdbook now has checkboxes enabled across the board.

I don't know whether or not it's a good change to make across the board because it may lead to some people misunderstanding that the checkboxes are not able to be saved, but yeah, either way, this works for now.

**Comment by troyerta** [comment]
@bamhm182 Thanks very much for the tip! This definitely works as I hoped! Though it looks like a newline is placed between the checkbox and it's associated text. Is there a way to keep the text on the same line? It's neat that this can be done locally on my book alone - without affecting the program behavior for everyone else!.

- [ ] Expected output

- [ ]
  Current output

**Comment by bamhm182** [comment]
Yeah, mdbook is fantastic. I just found out about it earlier this week and it has me wanting to learn Rust so I can contribute, haha. That's super weird that it is doing that for you... I can't get it to act like that on mine... I even copy-pasted exactly what I told you to add. I feel like perhaps your .md file is messed up. If you can't get it figured out, would it be possible to copy-paste your line here? You can put it between three backticks (\`) so it will format correctly. Alternatively, try to copy-paste this and see if it is doing it:

```
[ ] One
[ ] Two
[ ] Three
[X] Four
[X] Five
```

**Comment by troyerta** [comment]
Thanks for taking a look - I can just link you to the hosted source and result of the simplest method that produces the strange result.

It's a recipe book on github pages.. just for context

[Source](https://github.com/troyerta/recipes/blob/master/src/recipes/01-Appetizers/baked-brie-and-prosciutto-rolls.md)

[Result](https://troyerta.github.io/recipes/recipes/01-Appetizers/baked-brie-and-prosciutto-rolls.html)

It renders this way when I run my local host through "mdBook serve", and apparently, when hosted on github too. I thought perhaps it was just a line-width / word-wrap issue, but I'm not convinced.

Any thoughts on this?

**Comment by bamhm182** [comment]
I figured it out. It doesn't like the spaces between the items. I have no idea why...

This works:
```
- [ ] one
- [ ] two
- [ ] three
```
This works:
```
- [ ] one
some words
- [ ] two
more words
- [ ] three
even more words
```
This does not:
```
- [ ] one

- [ ] two

- [ ] three
```

The first option should return the exact same result, but with the checkboxes inline. What is weird though is that mdbook outputs both a bullet and a checkbox, vs just the checkbox as is displayed in most other markdown interpreters.

**Comment by troyerta** [comment]
Thanks for figuring that out! I agree, this task list feature does not seem to work as expected, especially given the inline bullet point. I ran another test to try and narrow down the issue.

See the tested markdown source file in tests/dummy/book/src/first/markdown.md:
```markdown
## Tasklisks

- [X] Apples
- [X] Broccoli
- [ ] Carrots
```

And the corresponding test case in rendered_output.rs:503:
```rust
    assert_contains_strings(
        &path,
        &[
            "<li><input disabled=\"\" type=\"checkbox\" checked=\"\"/>\nApples",
            "<li><input disabled=\"\" type=\"checkbox\" checked=\"\"/>\nBroccoli",
            "<li><input disabled=\"\" type=\"checkbox\"/>\nCarrots",
        ],
```

It seems to be *expecting* a newline before each checkbox's name or title or whatever it's called..

I have not been able to find the mdBook source that actually makes these transformations from markdown to html. Can anyone advise on where to find this?

Being unfamiliar with rust or html, here's all I've been able to do:

```shell
cargo build
cargo test markdown_options
```

This passes the test, as expected. But if you change the task list markdown.md to
```markdown
- [X] Apples

- [X] Broccoli

- [ ] Carrots
```

Running the same test again fails. What's interesting is all the html output that gets spewed out of the terminal while the test fails. Here is the relevant section:

```html
<h2><a class="header" href="#tasklisks" id="tasklisks">Tasklisks</a></h2>
<ul>
<li><input disabled="" type="checkbox" checked=""/>
<p>Apples</p>
</li>
<li><input disabled="" type="checkbox" checked=""/>
<p>Broccoli</p>
</li>
<li><input disabled="" type="checkbox"/>
<p>Carrots</p>
</li>
</ul>
```
I think the bullet points sticks around possibly because we're still inside the <ul> tag. Then, I think stuff is appearing on a new line because of the <p> tags which seem to get introduced. If I understand the test case correctly, then I don't think it expects to see these <p> tags in place.

Is this correct output? Or does the test case need to smarter?

If I could just find the source that makes these transformations, I could try some experimenting and write some new test cases, but I'm out of my depth here until then.

@ehuss, can you confirm this Github task list should be rendered differently than this? Looks like the renderer puts out a bullet point with an inline checkbox. Can you advise on where to look for the rendering functions that handle this Github-style task list? Thanks!

**Comment by troyerta** [comment]
Since these checkboxes render strangely, I went ahead and just wrote a post-processing script in python to go through and surgically replace the mdbook-generated html with customized checkbox objects that render correctly without needing to be in a list tag, and then added some additional tricks while I was in there.

It was a good opportunity to learn some HTML and javascript, and now my checkboxes will get greyed out with strikethrough fonts as checkboxes get "checked".

See my dumb recipe book repo's "checkboxes.py" to see how I did it. But I honestly wouldn't recommend doing it this way.

Closing due to lack of options.
