### ISSUE TITLE
Netlify Support

### ISSUE THREAD

**Issue by Ramshandilya** [rust-lang/mdBook#1191]
Hi there,

I'm looking to publish my wiki build with mdbook on Netlify. I believe Netlify currently [doesn't support Rust](https://github.com/netlify/build-image/pull/320) in its build images.
I tweeted about this and [@rustlang suggested](https://twitter.com/rustlang/status/1250217411405627394?s=20) we open an issue and take it from there. So here we are :)

**Comment by jamesmunns** [comment]
Hey! I've used netlify to publish with mdbook before. You can use the binary releases that mdbook has, and set that in your deploy settings. Under `Build & Deploy` > `Continuous Deployment` > `Build Settings` > `Build command`, I use the following command:

```
curl -L https://github.com/rust-lang/mdBook/releases/download/v0.3.3/mdbook-v0.3.3-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build 
```

Then I set the `publish directory` to `book` (or whatever your mdbook is configured to).

**Comment by steveklabnik** [comment]
hey @Ramshandilya , thanks for actually doing this!

I was gonna suggest exactly what @jamesmunns was going to! Can you give it a try and let us know if it works for you?

**Comment by Ramshandilya** [comment]
Hi @steveklabnik 
Just tried @jamesmunns 's suggestion and it worked. Thank you so much!  :)

**Comment by PEZ** [comment]
Don't know if @jamesmunns' way is still the way to do this. For me I also have some mdBook plugins and I really wanted Netlify to cache the build dependencies, so I build a dummy app specifying mdbook et al as `build-dependencies`, to get them cached. Full recipe here: https://blog.agical.se/en/posts/15-second-netlify-deploy-of-a-rust-mdbook/
