### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by Hitaro** [rust-lang/mdBook#1194]
May you please add support for internationalization? I mean something like [this](https://github.com/google/docsy/tree/master/i18n), possibility to switch to other languages via config file.

**Comment by ehuss** [comment]
Multilingual support is a pretty big project.  There is quite a bit of discussion over at #5, so closing as a duplicate of that.

**Comment by Hitaro** [comment]
Oh no! this is not about _multilingual feature_. Here I'm asking for i18n, that means posibility to translate default words such as "next, previous, etc".
