### ISSUE TITLE
Urls with ids end up with target out of view

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang/mdBook#1198]
An example of this can be seen here: https://rustc-dev-guide.rust-lang.org/appendix/glossary.html#nll

Regardless of whether you're in desktop or mobile, the nll item it just out of view. This seems to be related to how the sticky header is implemented.

**Comment by Nashenas88** [comment]
I've got a prototype in place at https://jsfiddle.net/q7pbjdxc/12/ that might also fix #1102.

**Comment by mgeier** [comment]
You could also try `scroll-margin-top: var(--header-height);` on the target element.

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top

Does need a special case for Safari though, and doesn't work on Internet Explorer (who cares!):
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top#Browser_compatibility

**Comment by Nashenas88** [comment]
This was the most recent iteration: https://jsfiddle.net/q7pbjdxc/17/.

I haven't worked on this much since then. I lost my motivation to continue this, but hopefully what I've done so far is a good starting point for someone else.
