### ISSUE TITLE
Typing s opens search 

### ISSUE THREAD

**Issue by briantliao** [rust-lang/mdBook#1204]
When you type s, it opens search. Is there a way to disable this?

**Comment by daniel-vainsencher** [comment]
I want to have a form in the about page of my website, and this makes `s` challenging to enter... currently only workaround I've found is to disable search entirely, which seems a bit extreme.

I propose to enable user to override the keycode activating search (including disabling keyboard activation) by:
- Add a field of "search keycode" to [output.html.search]
- Write it out to the html with a node id (somewhere in hbs_rendererer.rs?)
- getElementById for that node in searcher.js, use it to initialize the SEARCH_HOTKEY_KEYCODE (or not).

I've never written js in my life, but this doesn't look too challenging (actually, a [sketch](https://github.com/rust-lang/mdBook/pull/1558/files) of the js part). PR welcome? if so, happy to hear any improvements to the plan above.

**Comment by ehuss** [comment]
I would prefer to avoid adding configuration here if possible.  Is there a reason that the [check](https://github.com/rust-lang/mdBook/blob/8201b411aba2f4957f19c4e146ceb54d3682ce39/src/theme/searcher/searcher.js#L319) to avoid conflict isn't working for your form?

**Comment by daniel-vainsencher** [comment]
Ah, I hadn't understood that mechanism. It is because the fields's type is not one of the excluded types, it is "email". I can make the trivial PR to also include email, though this does seem a bit of a whack-a-mole (I might find myself using a different new field type tomorrow). Perhaps it would be better to instead enumerate the types that mdbook uses in normal operation, and apply the s behavior only to them?

**Comment by daniel-vainsencher** [comment]
@ehuss ^ ? the trivial PR does work for me, for now I am using a fork that excludes the "email" field.

**Comment by ehuss** [comment]
> Perhaps it would be better to instead enumerate the types that mdbook uses in normal operation, and apply the s behavior only to them?

If you know of a way to do that, feel free to open a PR!  I'm not sure if it is possible to check for an "allowed" list, though.

**Comment by briantliao** [comment]
It was old… yes would like to have it merged please.

**Comment by sspaeti** [comment]
I created a new PR (https://github.com/rust-lang/mdBook/pull/2311) that is ready to merge. I'm running that version on my book and e.g. [this form](https://www.dedp.online/login.html) allows you to enter `s` without the search popping up. Search is still active for everything else.
