### ISSUE TITLE
[request] Authentication feature

### ISSUE THREAD

**Issue by fulara** [rust-lang/mdBook#1212]
Would it be possible to add an authentication feature?
Reasoning:
Within company we have separation to different departments,
Currently our hosted mdbook page is open to everyone, which ideally wouldnt be the case.
It would be nice if there would be an option to enable authentication ( that has sso feature ideally ) and then selective select which users can access the book or not. 

Is something like that achievable via some plugin out there already?

**Comment by ehuss** [comment]
Since mdBook is a static site generator, I don't think it will have built-in support for authentication. That usually requires some interaction with the server.  You may be able to configure your web server to provide authentication, or use a proxy which provides an authentication wall.
