### ISSUE TITLE
SUMMARY linking to heading creates file instead of what I would expect

### ISSUE THREAD

**Issue by SirTates** [rust-lang/mdBook#1213]
In markdown I can typically link to a header in another markdown file through the following syntax:

```md
- [Markdown File](markdownFile.md)
  - [To Heading](markdownFile.md#heading-name)
```

However (in the `SUMMARY.md` file only) mdbook creates a new file as opposed to creating a link to the page and overrides the last instance of the address markdownFile.html with the contents of that file.

I would expect it to be interpreted as a link to `markdownFile.html#heading-name`, like it does in other source files.

**Comment by ehuss** [comment]
Thanks, this looks like the same as #167, so closing as a duplicate.
