### ISSUE TITLE
git build on nixos failed, could not compile `percent-encoding`

### ISSUE THREAD

**Issue by rubenmoor** [rust-lang/mdBook#1217]
on NixOS

    $> cargo --version
    cargo 1.32.0

    $> cargo install --git https://github.com/rust-lang/mdBook.git mdbook

       Compiling percent-encoding v2.1.0
    error: local variables in const fn are unstable
      --> /home/ruben/.cargo/registry/src/github.com-1ecc6299db9ec823/percent-encoding-2.1.0/lib.rs:72:13
       |
    72 |         let chunk = self.mask[byte as usize / BITS_PER_CHUNK];
       |             ^^^^^

    error: aborting due to previous error

    error: Could not compile `percent-encoding`.
    warning: build failed, waiting for other jobs to finish...
    error: failed to compile `mdbook v0.4.0 (https://github.com/rust-lang/mdBook.git#e8d4bc52)`, intermediate artifacts can be found at `/tmp/cargo-installYPCwbj`

    Caused by:
      build failed

**Comment by ehuss** [comment]
The minimum Rust version is 1.35.

**Comment by rubenmoor** [comment]
Making my first steps with `rust` on NixOS. This is one way to get it to work, including `mdbook`.

    # code/rust-mdbook/shell.nix
    # any stable channel should work, too
    with import <nixos-unstable> {};
    stdenv.mkDerivation {
        name = "my-rust-env";
        buildInputs = [
             pkgs.cargo
             pkgs.gcc
         ];
    }

And then in `code/rust-mdbook/`:

    > nix-shell
    nix-shell> cargo install --git https://github.com/rust-lang/mdbook.git 

I also had to configure nixos for more space for nix-shell in `/run/user/1000/` like this in `/etc/nixos/configuration.nix`:

    services.logind.extraConfig = ''
         RuntimeDirectorySize=2G
    '';

and

    > sudo nixos-rebuild boot

followed by a reboot to avoid an OS error about insufficient disk space.

**Comment by rubenmoor** [comment]
Realizing now that `rust-lang/mdbook` under the name `mdbook` is a perfectly up-to-date package within the nixos package universe.
