### ISSUE TITLE
Feature Request: Add 'Edit on Github' Link to pages

### ISSUE THREAD

**Issue by netlander** [rust-lang/mdBook#1236]
New to mdBook but looked around and couldn't find anything related to a feature that would add a link on each page allowing the reader to edit the page's content on Github as is the case with many doc generators.

**Comment by quinn-freshly** [comment]
I would also like this.

I am going to do this by adding a javascript asset that would add the link at runtime, would be nice to have a more "official" way

**Comment by ehuss** [comment]
See PR #1148.

**Comment by ehuss** [comment]
Closing, as this should now be implemented via #1506 (using `edit-url-template` config setting).
