### ISSUE TITLE
proposal: There should not be any option to add Google analytics

### ISSUE THREAD

**Issue by milrope** [rust-lang/mdBook#1242]
This needs to be taken seriously. You shouldn't give an easy way to authors to use Google analytics on
there book.
I want to read a book. Not get tracked by Google.
Yes it is optional, but having this in the option is a promotional task and you shouldn't do it.

TODO: Remove the option to add Google analytics

**Comment by Dylan-DPC** [comment]
Hi. Thanks for creating the issue. However, as library authors we can't dictate how our users want to use mdbook. If they need google analytics or some other thing, t he responsibility is on them and not us to block them from doing it. We, as maintainers are being neutral to third party platforms and do not want to promote or push against the use of any plugin.

**Comment by milrope** [comment]
no, you can't have an option to add a proprietary system to a free software.
you should understand the concern.

Please remove that option.
