### ISSUE TITLE
`mdbook serve` creates files linked from summary if they do not exist

### ISSUE THREAD

**Issue by acheronfail** [rust-lang/mdBook#1246]
I'm relatively sure that this is a "feature" and not a bug, but the behaviour surprised me.

I created a `SUMMARY.md` like the following:

```md
# Summary

- [Chapter 1](./chapter_1.md)
- [Chapter 2](#)
```

With the `#` uri as a placeholder since I hadn't yet created the file.
When I ran `mdbook serve` I was surprised to discover that the `src/#` file existed!

I guess this may be the behaviour described in the User Guide here:

> When a SUMMARY.md file already exists, the init command will first parse it and generate the missing files according to the paths used in the SUMMARY.md. This allows you to think and create the whole structure of your book and then let mdBook generate it for you.

Should this also happen when running `mdbook serve`?

* If so, it should probably be documented.
* If not, should the behaviour be toggle-able via a CLI flag?

**Comment by acheronfail** [comment]
This also adds an unfortunate side effect that if I run `mdbook serve`, and delete the file `src/chapter_1.md`, then when `mdbook` reloads it _recreates_ the file I just deleted.

Which is another thing that seems counter-intuitive to me, since if I want to remove a note/delete a file, then I must remove it first from the `SUMMARY.md` and _then_ delete the file itself...

**Comment by ehuss** [comment]
Yea, that's intentional.  It could probably be documented better.

As for the `#`, that's a little odd. It could probably detect fragment-only urls and reject them.

Also, FYI, the next release will support "draft" chapters, which allow you to add entries that won't automatically create new files (#1153).

**Comment by bikeshedder** [comment]
The "draft" chapters feature has landed in 0.4.0. I think this issue can be closed.

**Comment by ehuss** [comment]
Probably should still update the build, serve, and watch documentation to mention that missing files in the SUMMARY are auto-generated.

**Comment by VaZark** [comment]
In that case, how do we indicate a Section header without a file? @ehuss 

In the example below, I'm using Topic as merely a logical separator and it has no file has associated with it. With drafts, using `()` marks it as a draft and using `(#)` redirects to root.

```
- Topic
    - Subtopic.md
    - Subtopic2.md 
```
