### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/mdBook#1259]
Hey, there does not seem to be any public documentation about how or when mdbook publishes so I'm making an issue about publishing the current master to crates.io.

**Comment by mark-i-m** [comment]
@XAMPPRocky My understanding is that `mdbook` is largely reviewed/maintained by @ehuss in their spare time, so the next release will be whenever they finish reviewing any breaking changes slated for 0.4... 

That said, it looks like that will be relatively soon: https://github.com/rust-lang/mdBook/milestone/10

**Comment by ehuss** [comment]
The new version should be published now.
