### ISSUE TITLE
Reliable links to source files

### ISSUE THREAD

**Issue by dhbradshaw** [rust-lang/mdBook#1274]
I'm trying to add an edit link and icon (next to the print icon and the optional git icon on the top right of each page).

The goal is to have that link point to the source markdown file when possible.  So far, I've gotten almost there but not quite using

`href="{{git_repository_url}}/tree/master/src/{{path}}"`.

This seems to work for every page -- except for the front page!  In this case, the template `path` variable resolves to `index.md`, but there isn't actually an `index.md` in the source folder so the link gets a `404`.  

(I looked into special casing this, checking for `path == index.md` and then fixing it, but unfortunately default handlebars doesn't accept equality checks in if statements.)

Any thoughts on how to embed more reliable source file links?

**Comment by ehuss** [comment]
There is a PR at #1148 to add this, but ran into the same problem with readme/index translation.

**Comment by dhbradshaw** [comment]
Nice to see that I'm not alone here.  
(Although in our particular case `index.html` should point to `introduction.md` rather than to readme). 

It seems like a couple of different paths could make this work.  

1. We could either alter path so that it doesn't mangle the md links (or, if that behavior needs to be kept we could introduce non_mangled_path), or 
2. We could extend handlebars with an extra custom command to enable more powerful logic.  For example, if_eq. https://stackoverflow.com/a/15095019.

One would be to register `if_eq` for handlebars

**Comment by ehuss** [comment]
I'm not entirely sure if it solves your use case, but I think #1506 solves this as there is now a `edit-url-template` option for providing a link to the original source.  Feel free to clarify if that doesn't cover this.
