### ISSUE TITLE
No kotlin syntax highlighting despite highlight.js support?

### ISSUE THREAD

**Issue by maniyar1** [rust-lang/mdBook#1275]
Running into a problem where Kotlin code snippets are not properly being highlighted. 
[Here is a test repository to demonstrate](https://github.com/maniyar1/test-book) (generated with current git version of mdBook). 

This is fixed by dropping in a [new version](cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js) of highlight.js in the `theme/` folder, but this is strange since according to the [changelog](https://github.com/highlightjs/highlight.js/blob/master/CHANGES.md) Kotlin has been supported for a good while before the current version in mdBook (9.15).

In any case, it seems updating highlight.js is trivial, so I'd be totally open to PRing in the most recent version, just was wondering if anyone else had thoughts on this (especially since I know Kotlin isn't really a target language).

**Comment by ehuss** [comment]
The default higlightjs uses the common languages and a few select extras. Kotlin isn't in the default set.  A PR to update to add Kotlin would be fine, just make sure not to remove any languages currently included.

**Comment by maniyar1** [comment]
Ah, that's interesting and makes perfect sense. What's the criteria for being added? I doubt mdBook is being used that much for Kotlin code anyway, and the work-around is pretty simple. 
Looking at their bundling it looks like now Kotlin is in their "common" bundle/set (not sure about phrasing), so I guess it might make sense to add it in. Is there a running list of the languages currently supported?

**Comment by ehuss** [comment]
The criteria has generally been when someone asks for a new language.

I don't remember exactly what the list is.  You can load the current [highlight.js](https://github.com/rust-lang/mdBook/blob/master/src/theme/highlight.js) and search for all the calls to `registerLanguage` to get the complete list. According to #942 it is `:common armasm d go handlebars haskell julia rust scala swift x86asm yaml`, but I don't remember if that is a current list.
