### ISSUE TITLE
can support other language: python go js ...?

### ISSUE THREAD

**Issue by luckrill** [rust-lang/mdBook#1276]
mdbook can edit and execute rust code.

How to support other language, python go js ...?

**Comment by ehuss** [comment]
Testing for other languages is not supported at this time.

**Comment by williamd1k0** [comment]
If I got it right, the code playground just sends a request to play.rust-lang.org.
So I think it should be good enough to implement support for other languages using custom HTTP APIs (the user would be responsible for providing the API URL in the book.toml file).

**Comment by luckrill** [comment]
ok know
