### ISSUE TITLE
Add a list of preprocessors to the readme or the guide book?

### ISSUE THREAD

**Issue by dhbradshaw** [rust-lang/mdBook#1278]
And if we create such a list, I'd like to add

[mdbook-classy](https://github.com/Reviewable/mdbook-classy)

to it for people who want to add kramdown-style css class annotations to their paragraphs. :smile_cat:

**Comment by sburris0** [comment]
I think this would be nice.
I suppose someone could make an awesome-mdbook-preprocessor repo if this doesn't happen.

Anyways, here are some more:
[mdbook-open-on-gh](https://github.com/badboy/mdbook-open-on-gh)
[mdbook-checklist](https://github.com/ANSSI-FR/mdbook-checklist)
[mdbook-curly-quotes](https://github.com/arminha/mdbook-curly-quotes)
[mdbook-plantuml](https://github.com/sytsereitsma/mdbook-plantuml)
[mdbook-toc](https://github.com/badboy/mdbook-toc)
[mdbook-svgbob](https://github.com/fzzr-/mdbook-svgbob)
[mdbook-mermaid](https://github.com/badboy/mdbook-mermaid)
[mdbook-katex](https://github.com/lzanini/mdbook-katex)

**Comment by sburris0** [comment]
mdbook-katex was added to the book in #1392, seems like a complete list of available preprocessors is reasonable
