### ISSUE TITLE
What is the intended behavior when a backend isn't available?

### ISSUE THREAD

**Issue by ericonr** [rust-lang/mdBook#1283]
Hi there! We are using `mdbook` for the Void Linux handbook. We have configured the `mdbook-linkcheck` backend to help with verifying contributions, since it keeps any dead links out of the handbook. However, when deploying the book, we don't include have `mdbook-linkcheck` available in the machine, and it simply complains about not finding the plugin, but still builds the whole book perfectly.

However, when using `mdbook serve` and `mdbook-linkcheck` isn't available, it errors out completely, with the error message below:

```
2020-07-24 00:42:26 [INFO] (mdbook::book): Book building has started
2020-07-24 00:42:26 [INFO] (mdbook::book): Running the html backend
2020-07-24 00:42:26 [INFO] (mdbook::book): Running the linkcheck backend
2020-07-24 00:42:26 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
2020-07-24 00:42:26 [ERROR] (mdbook::renderer): The command `mdbook-linkcheck` wasn't found, is the `linkcheck` backend installed?
2020-07-24 00:42:26 [ERROR] (mdbook::utils): Error: Rendering failed
2020-07-24 00:42:26 [ERROR] (mdbook::utils): 	Caused By: Unable to start the backend
2020-07-24 00:42:26 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
```

Ideally, I would like to be able to serve the handbook locally for testing purposes without having `mdbook-linkcheck` installed. I can try to fix this issue, but I don't know what the preferred behavior is. Would it be desirable to remove the failure from `mdbook serve`, so it acts like `mdbook build` and simply complains about the lacking backend, or should `mdbook serve` accept a flag to ignore missing backends and/or not use any backends beyond the HTML one?

**Comment by ericonr** [comment]
Sorry, tested the new version with `mdbook build` and it also errored out. So I guess I'd like some way of controlling the backend behavior. For example, we run linkcheck at CI but not at prod, so being able to choose backends would be nice.

**Comment by ehuss** [comment]
If you are using mdbook 0.4, the intended way to do that is to make it optional:

```toml
[output.mdbook-linkcheck]
optional = true
```

Does that work for you?

**Comment by ericonr** [comment]
Oh! That does work. Thanks a lot :D 

I will see if I can think of some way to make this easier to discover in the documentation (found it in https://rust-lang.github.io/mdBook/format/config.html#custom-renderers), but if I don't I will just close the issue.

**Comment by ehuss** [comment]
I think the error message should definitely be updated to mention the `optional` flag, I think we just neglected that when adding it.

**Comment by ericonr** [comment]
Hmm I think so too. How do you think the phrasing should go? I can make a PR for it.
