### ISSUE TITLE
Code highlighting doesn't work in Chrome, MacOS Big Sur

### ISSUE THREAD

**Issue by buttercrab** [rust-lang/mdBook#1301]
OS: MacOS Big Sur public beta
Browser: Chrome(Maybe Chromium) (Not on Safari)

Screenshots in 5 themes ([rust programming book](https://doc.rust-lang.org/book/ch01-02-hello-world.html#writing-and-running-a-rust-program)):

|Light|Rust|Coal|Navy|Ayu|
|:-:|:-:|:-:|:-:|:-:|
|![image](https://user-images.githubusercontent.com/34997549/90234135-20fb8980-de5a-11ea-97fc-8ddc08154007.png)|![image](https://user-images.githubusercontent.com/34997549/90234156-2953c480-de5a-11ea-96ea-3a7f7e4e8424.png)|![image](https://user-images.githubusercontent.com/34997549/90234171-31136900-de5a-11ea-9be2-8d764e5c9ce8.png)|![image](https://user-images.githubusercontent.com/34997549/90234183-3670b380-de5a-11ea-8939-3ab336244ce3.png)|![image](https://user-images.githubusercontent.com/34997549/90234199-3ffa1b80-de5a-11ea-8897-1f7241ee3ac2.png)|

As you can see, the code highlighting isn't working. 
However, the computed color is different from black.

Screenshot:
![image](https://user-images.githubusercontent.com/34997549/90234409-99fae100-de5a-11ea-9476-1f4ca808ff11.png)
(`println!` keyword is computed to orange in lower right)

Why is this happening? Also, where can I get help in this problem?

**Comment by flapjackfritz** [comment]
Try deleting the Source Code Pro font from your Font Book. That fixed it for me.

**Comment by joshgoebel** [comment]
Interesting.  Is that a font the website itself has specified?  So weird...

**Comment by camelid** [comment]
Does this still happen for you? There was a recent change that fixed this in Firefox on macOS. Make sure that you're using the latest release of mdBook (v0.4.3).

You can test this by cloning rust-lang/book, installing the latest version of mdBook, and viewing it locally with `mdbook serve`.

**Comment by buttercrab** [comment]
> Does this still happen for you?

I've downgraded to 10.15. Sorry that I can't check it now.

**Comment by camelid** [comment]
That's okay!

**Comment by ehuss** [comment]
I'm going to assume this was a font issue.
