### ISSUE TITLE
site-url as a CLI parameter

### ISSUE THREAD

**Issue by Nainterceptor** [rust-lang/mdBook#1302]
Hello,

I've seen in [Changelog](https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#breaking-changes) that site-url is used to generate a right 404.html, it could be a good option to be able to pass site-url as a CLI parameter, in this way we will be able to use CI variable to propagate url who is defined through CI.

Examples (So, we're using gitlab...) : 
- Environment URL([CI_ENVIRONMENT_URL](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html))
- Gitlab Pages URL([CI_PAGES_URL](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)) <- Our usecase

If contibutions are welcome, @EpiFouloux can do a PR.
But, let's have a discuss about how-to-do : 
`mdbook build --site-url <url>` match my needs, but maybe it's better to have something more generic to override other parameters ? 
Other suggestions : 
- `mdbook build --set <key>=<value>` like helm
- `mdbook build --<categoryInToml>.<key> <value>`

Should it be available too on `serve` command ?

Any insight about how to add this feature from contributors is welcome to do the PR easier.

Best regards,
Gaël

**Comment by ehuss** [comment]
You can set the site-url with the `MDBOOK_OUTPUT__HTML__SITE_URL` environment variable.

**Comment by Nainterceptor** [comment]
> You can set the site-url with the `MDBOOK_OUTPUT__HTML__SITE_URL` environment variable.

Aha, ok perfect, it should fix our problem ! Feel free to close the issue, or see with @EpiFouloux if you want the feature anyway.
