### ISSUE TITLE
git submodules

### ISSUE THREAD

**Issue by r3k2** [rust-lang/mdBook#1305]
Hello, wondering if one can add parts of the src as/from a git submodule, example.
I want to add pieces from another project, or I want to be able to separate pieces on their own repo to be part of a blog post for that particular piece and not the whole book... etc.

Thanks
PS: BTW how do I force one of the current themes to be the default? like Coal one?

**Comment by marco-m-pix4d** [comment]
Hello, if I understand correctly, this is a duplicate of #1347.

**Comment by ehuss** [comment]
Yea, closing this as a duplicate of #1347.
