### ISSUE TITLE
Invalid release asset for macOS

### ISSUE THREAD

**Issue by peaceiris** [rust-lang/mdBook#1318]
[Release v0.4.3 · rust-lang/mdBook](https://github.com/rust-lang/mdBook/releases/tag/v0.4.3) seems to have an invalid release asset for macOS.

<img width="851" alt="Screen Shot 2020-09-09 at 9 59 57" src="https://user-images.githubusercontent.com/30958501/92542302-622d6080-f283-11ea-8f97-d13a128ff6f2.png">

**Comment by ehuss** [comment]
Thanks for the heads-up!  I suspect it is related to a bug with BSD tar and APFS  (the first 8MB of the file are 0). I unrelatedly have been dealing with this at https://github.com/rust-lang/cargo/issues/8603#issuecomment-684085412.  I will try one of the workarounds listed there.

**Comment by ehuss** [comment]
I have rebuilt the 0.4.3 artifacts, and macos seems to be working now.
