### ISSUE TITLE
Ignore swap files

### ISSUE THREAD

**Issue by camelid** [rust-lang/mdBook#1327]
I think mdBook should ignore `*.swp` files. Editing a book in Vim while `mdbook serve` is running causes lots of rebuilds because Vim frequently updates the swap file. I imagine this could be implemented just by checking the extension of the file that changed and skipping a rebuild if it ends in `.swp`.

**Comment by camelid** [comment]
I guess one way to work around it would be to add `*.swp` to the `.gitignore`, but I don't think there's ever a case where a swap file change should cause a rebuild.

**Comment by ehuss** [comment]
I think this is roughly a duplicate of #383, so closing in favor of that.
