### ISSUE TITLE
How do I use a local font in place of the default Source Code Pro?

### ISSUE THREAD

**Issue by ehamiter** [rust-lang/mdBook#1338]
Hi there-- I *really* enjoy using this tool and it is truly a thing of beauty. The one thing that I am having a problem figuring out is how to replace the default `code` font "Source Code Pro" with a local `woff` font file that I have. I've read through the docs pretty extensively but can't figure out how to make it work. This is what I've tried:

  * Created a `theme` folder at the root, then added a `fonts` directory with a new `fonts.css` file inside this
  * Copied the source folder `theme` from this repo, renamed it `my-theme` at my root, replaced the files and the css, and set `theme = "my-theme" in `book.toml`
  * Set `copy-fonts = false` and tried the above
  * Copied `index.hbs` and tried to load a separate css file in this section but I never get it to link properly:

```
        <!-- Custom theme stylesheets -->
        {{#each additional_css}}
        <link rel="stylesheet" href="{{ ../path_to_root }}{{ this }}">
        {{/each}}
```

I'm not sure what to modify here, what this should be pointed to. If I alter this, should I disable `copy-fonts`? 

No matter what I try, `general.css` will be overwritten and "Source Code Pro" will continue to be the first font selection for the `code > font-family`.

Is there an easy way to swap out one font for another? I feel like there must be, but I just don't know how to do it. Help?

Thanks for any tips!

**Comment by ehamiter** [comment]
Belay my last-- I figured it out. If anyone else finds them here wondering how to do it, I added this to my `book.toml`, which allowed the default css to be overwritten (and this may be obvious but it took me a few routes to get here):

```
[output.html]
additional-css = ["theme/custom.css"]
```

Thanks again for this tool, it's great!

**Comment by hacktivista** [comment]
I couldn't find a way to copy the fonts to the public path, how did you do that @ehamiter ?

**Comment by ehamiter** [comment]
@hacktivista you can look at my directory structure here:

https://github.com/ehamiter/ipython-book/tree/main/src

In my example, I have a `fonts` folder at the source root, and in my `theme/css/general.css`, I point to them like such:

```
@font-face {
  font-family: 'Edlo';
  font-style: normal;
  font-weight: 500;
  src: url('../fonts/edlo.woff2') format('woff2');
  font-display: swap;
}
```

**Comment by jalethesh** [comment]
It works well. Thank you @ehamiter

**Comment by mo1ein** [comment]
This works in chrome but not in firefox (version 126).
