### ISSUE TITLE
no use to set "output.html.print.enable = false"

### ISSUE THREAD

**Issue by 2372281891** [rust-lang/mdBook#1359]
The icon is still on the top-right

<code>
[book]
authors = [] 
language = "en"
multilingual = true
src = "src"
title = "帅德笔记"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true 
level = 1

[output.html.search]
enable = true

[output.html.print]
enable = false
</code>

**Comment by 2372281891** [comment]
mdbook version  0.4.3

**Comment by ehuss** [comment]
That feature hadn't been released, yet.  I just released 0.4.4, can you try to upgrade and check it out?

**Comment by 2372281891** [comment]
it works,thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric Huss"<notifications@github.com&gt;; 
发送时间: 2020年10月20日(星期二) 晚上11:22
收件人: "rust-lang/mdBook"<mdBook@noreply.github.com&gt;; 
抄送: "2372281891"<2372281891@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rust-lang/mdBook] no use to set &quot;output.html.print.enable = false&quot; (#1359)





 
That feature hadn't been released, yet.  I just released 0.4.4, can you try to upgrade and check it out?
