### ISSUE TITLE
Running mdbook build does not create "theme" subdirectory

### ISSUE THREAD

**Issue by Ciro-Fusco** [rust-lang/mdBook#1362]
Running _mdbook build_  ends with the error "Impossible to find the path" due to the impossibility of copying "theme/2018-edition.css to the destination path". Checking on the explorer I discoverd "theme" subdirectory in the "book" directory is not even created. 

I'm wondering if this is a mdbook bug or just a problem of my PC.

**Comment by ehuss** [comment]
Can you copy the exact error message that is displayed?  Also, which version of mdbook are you using?  I assume you are using a custom theme?  Does the `output.html.theme` configuration value match where the `theme` is located?

**Comment by Ciro-Fusco** [comment]
@ehuss Thank you for answering

 Here is the exact error displayed:

`2020-10-23 08:56:42 [ERROR] (mdbook::utils): Error: Rendering failed`
`2020-10-23 08:56:42 [ERROR] (mdbook::utils):    Caused By: Unable to copy across additional CSS and JS`
`2020-10-23 08:56:42 [ERROR] (mdbook::utils):    Caused By: Unable to copy theme/2018-edition.css to C:\Users\Ciro\Desktop\rust\book\theme/2018-edition.css`
`2020-10-23 08:56:42 [ERROR] (mdbook::utils):    Caused By: Impossibile trovare il percorso specificato. (os error 3)`

The italian part means "Impossible to find the specified path."

I'm usign mdbook v0.1.0, not using any custom theme just copyed the repository from github and tried to build.

For the output.html.theme I don't know where to find it.

**Comment by ehuss** [comment]
v0.1.0 is almost 3 years old. Can you maybe try with the latest version?

`output.html.theme` is defined in the `book.toml` file.  It might look something like this:

```toml
[output.html]
theme = "src/theme"
```

That tells mdbook where the custom theme is located.

**Comment by Ciro-Fusco** [comment]
I actually misread the version that rust-lang/rust uses on the github page so instead of 0.4.3 I installed the 0.1.0. Upgrading to the suggested version solved the problem. Thank you for the help.
