### ISSUE TITLE
 Code highlighting not working in Firefox 82.0.3 macOS Big Sur

### ISSUE THREAD

**Issue by radiosilence** [rust-lang/mdBook#1380]
* OS: macOS 11.0.1 (20B28)
* Browser: Firefox 82.0.3
* Extensions: All disabled.

<img width="874" alt="Screenshot 2020-11-11 at 18 46 19" src="https://user-images.githubusercontent.com/65021/98924652-fbb7ff00-24cc-11eb-9574-6475b8e2938f.png">

Originally posted here: https://github.com/rust-lang/book/issues/2501

But I noticed it fails on all mdBook docs.

**Comment by ehuss** [comment]
I'm assuming you have a locally installed copy of the Source Code Pro font?  If so, this should be fixed by #1307 in mdBook 0.4.3.

Have you tried https://doc.rust-lang.org/beta/book/ or https://doc.rust-lang.org/nightly/book/?

**Comment by ehuss** [comment]
Closing as I think this is now fixed.
