### ISSUE TITLE
Conflicting name attributes on searchbar input

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/mdBook#1382]
This \<input\> has both name="search" and name="searchbar". I'm not sure how browsers handle this but it's confusing at best, and seems unintentional. It would be better to have just one (not sure which is the right one).

https://github.com/rust-lang/mdBook/blob/59f2a9bf4ed62f7ad37ff8a14887886ca16ef576/src/theme/index.hbs#L157

**Comment by ehuss** [comment]
This was fixed in #1509.
