### ISSUE TITLE
Support space as seperator between language and additional class in code block

### ISSUE THREAD

**Issue by tuyen-at-work** [rust-lang/mdBook#1384]
### Use case

> Let say I want to add `h500` as a class for a code block.

### Editor

In VS Code, we can use space between language and additional class without loose syntax highlighting:

![image](https://user-images.githubusercontent.com/68000455/99209304-72b70580-27f5-11eb-8c76-6bc4d9b02cca.png)

But if I use comma instead of space between language and additional class, the highlighting doesn't work:

![image](https://user-images.githubusercontent.com/68000455/99209213-38e5ff00-27f5-11eb-97f2-9a951cd04314.png)

### Render

Let check what happen when two above code blocks got rendered:

The first case loose syntax highlighting:

![image](https://user-images.githubusercontent.com/68000455/99209622-24563680-27f6-11eb-8f3e-fd8ffb95abab.png)

The second case work nicely:

![image](https://user-images.githubusercontent.com/68000455/99209715-5ff10080-27f6-11eb-90f1-343edb4b702a.png)

### Current status

In current situation, if I want to use additional class, I have to choose:

- Either have syntax highlighting in VS Code, and loose it when rendered, or
- Don't have syntax highlighting in VS Code, and get it when rendered

### Feature request

Please support space as seperator between language and additional class in code block, so we can have syntax highlighting for both editor and rendered version.

**Comment by ehuss** [comment]
This should be fixed by #1469.
