### ISSUE TITLE
pikchr support

### ISSUE THREAD

**Issue by qrnch-jan** [rust-lang/mdBook#1386]
It would be nice to be able to create pikchr diagrams directly in markdown for mdbooks. There's even a crate for it: https://crates.io/crates/pikchr

**Comment by ehuss** [comment]
I'm going to close this as out of scope for mdbook itself.  Things like diagrams are best implemented as a preprocessor (like [mdbook-mermaid](https://github.com/badboy/mdbook-mermaid)).

**Comment by podsvirov** [comment]
The [mdbook-pikchr](https://crates.io/crates/mdbook-pikchr) preprocessor now available! This is my first Rust project, don't be too strict.
