### ISSUE TITLE
404 page displays without CSS if the address is a subfolder

### ISSUE THREAD

**Issue by Simonbdy** [rust-lang/mdBook#1391]
It looks like an error in root address when 404 page is in a subfolder

Example: 
[https://docs.luos.io/wrong-subfolder/wrong-page.html](https://docs.luos.io/wrong-subfolder/wrong-page.html) -> 404 page without CSS (subfolder in address)
[https://docs.luos.io/wrong-page.html](https://docs.luos.io/wrong-page.html) -> 404 page with CSS (no subfolder in address)

It's as if the `{{ path_to_root }}` variable wasn't taken into account in index.hbs when displaying a 404 page, and only when the address has one or several subfolders in it. But as it seems to work well on mdbook documentation, I feel I'm missing something.

Thanks

EDIT: typos

**Comment by ehuss** [comment]
Do you have a custom theme or are you setting the `site-url` in the book.toml?  Which version of mdbook are you using?

The default template sets a [base url](https://github.com/rust-lang/mdBook/blob/59f2a9bf4ed62f7ad37ff8a14887886ca16ef576/src/theme/index.hbs#L10-L12) which for the 404 page [defaults to `/`](https://github.com/rust-lang/mdBook/blob/59f2a9bf4ed62f7ad37ff8a14887886ca16ef576/src/renderer/html_handlebars/hbs_renderer.rs#L137-L147).

**Comment by Simonbdy** [comment]
No `site-url` set in book.toml, but it appears the base url wasn't set in my index.hbs.
I added back these few lines and the 404 page works everywhere now.

```
{{/if}}
{{#if base_url}}
<base href="{{ base_url }}">
{{/if}}
```

Thanks a lot @ehuss, I close this issue as it's resolved now.
