### ISSUE TITLE
Rendering failed when book directory contains broken symlink

### ISSUE THREAD

**Issue by soareschen** [rust-lang/mdBook#1396]
When the book src directory contains broken symlink, mdbook will fail to build the book with obscure error message `No such file or directory`.

Steps to reproduce:

- Create a broken symlink in the book src directory, e.g. `ln -s /path/not-found`.

- Running `mdbook` will produce the following error:

```bash
$ mdbook build
[INFO] (mdbook::book): Book building has started
[INFO] (mdbook::book): Running the html backend
[ERROR] (mdbook::utils): Error: Rendering failed
[ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

As shown above, the error message does not give any clue that the error is caused by broken symlink, making it difficult to debug.

Tested with mdbook v0.4.4 on Linux.

**Comment by maowen** [comment]
With the current implementation on the `master` branch, mdBook still fails to build when the book directory contains a broken symlink although there is now a helpful error message that provides helpful feedback and makes it more clear that the broken symlink caused the build to fail.

I recently submitted an MR (#1944) that I believe provides a full resolution to the original issue. Would it make sense to re-open this issue or should I create a new one instead?
