### ISSUE TITLE
Make EPUB (mdbook-epub pluging) working with 'parent' mdbook and create correct EPUB books from MD sources

### ISSUE THREAD

**Issue by blandger** [rust-lang/mdBook#1403]
Hi all
As I can see the project doesn't show activity anymore... No power, no resources, doesn't it ? I mean - 43 Opened PRs, 243 Issues...

Recently I worked on code to make **mdbook-epub** tool processing MD sources, generating epub files with preprocessed links  like : _{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/no-listing-04-looping/src/main.rs:here}}_
and successfull correct file epub book generation. I created several different epub rust books and even one 'Kubernates book' with Go sources linked.

Here are my current results you can download from.
**TRPL Eng + Rus** 
https://github.com/rust-lang-ru/book/releases/tag/0.0.1
**TRPL Simplified Chinese version**
https://github.com/blandger/trpl-zh-cn/releases/tag/v.0.0.1
**The Embedded Rust Book**
https://github.com/blandger/book-1/releases/tag/0.0.1
**The Rustonomicon**
https://github.com/blandger/nomicon/releases/tag/0.0.1
**The Little Book of Rust Macros**
https://github.com/blandger/tlborm/releases/tag/0.0.1
**Exploring Async Basics with Rust**
https://github.com/blandger/book-exploring-async-basics/releases/tag/0.0.1
**Futures Explained in 200 Lines of Rust**
https://github.com/blandger/books-futures-explained/releases/tag/0.0.1

But I don't see chances to pull prepared mdbook changes which enabled MD source pre-processing within mdbook-epub 'plugin' by calling ready for usage mdbook's functionality, because the project is rather dead then live.

![Image of Samadhi](https://yoganama.com/wp-content/uploads/2017/06/meditation-1384758_1920.jpg)

**Comment by ehuss** [comment]
This project does not have a roadmap, or significant resources for maintenance. But I would not characterize it as not having any activity. If you look at the commit logs, you can see that there has been an average of two PRs merged per week over the past year.  

I'm not sure what exactly this issue is about.  I'm glad that you have been working to improve the mdbook-epub plugin.  However, I think it is unlikely that it would be accepted as a built-in backend for the foreseeable future, due to the lack of resources.  Is there some problem with it being an external plugin?

**Comment by Dylan-DPC** [comment]
Having open prs and issues is not a metric to how active or not a repository is. And libraries often do not have a roadmap because it is difficult to judge what maintainers can and need to deliver. Also as Eric said, i'm not sure what your issue is about, so would recommend creating a new issue with less colour ;)

**Comment by blandger** [comment]
@ehuss @Dylan-DPC 

> ...it is unlikely that it would be accepted as a built-in backend for the foreseeable future...

That's not an issue. I'm not talk about that. The problem is following. The new rust book version includes links:
_{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/no-listing-04-looping/src/main.rs:here}}_
in sources. 
The epub plugin processes pages/chapters one-by-one and not as a bunch (all pages at once) from the one side. Also epub plugin doesn't process those 'new links' by itself (the links are quite new feature as I remember), so I added some code to mdbook to be able to reuse such functionality by calling that processing code from the mdbook itself. I'm using:
`use mdbook::preprocess::{PreprocessorContext, Preprocessor};`
and call Links Preprocessor code for that.

But there are some code changes in mdbook to make it possible reusing 'Preprocessor' functionality inside epub by taking/cloning that stuff.
An as I wrote - _I don't see chances to pull prepared mdbook changes_ (because small activity and lots of opened PRs).

That's why I created issue for trying to figure out if my efforts are needed or they are useless. That's why I'm here make attempt to know about project status.

**Comment by ehuss** [comment]
Sorry, I'm a bit confused about what the relationship is with the links preprocessor.  A backend should receive the book after it has been processed.  Can you explain your situation in more detail?

**Comment by blandger** [comment]
Sure. Here is a matter....

1. The mdbook uses Preprocessor as kind of batch processing way and all book's Chapters are processed at once:
```
pub trait Preprocessor: PreprocessorClone {
.........
     fn run(&self, ctx: &PreprocessorContext, book: Book) -> Result<Book>;
....}
```

2. The mdbook-epub plugin has another architecture, it processes book 'chapter-by-chapter' on rendering epub content by calling it's internal method:
`fn add_chapter(&mut self, ch: &Chapter) -> Result<(), Error> {`
https://github.com/blandger/mdbook-epub/blob/182546bb9c0dc696978b263a0df12c4fefb56f96/src/generator.rs#L98
on every Chapter's processing loop.
**That is the main reason for such changes and main difference between mdbook and epub plugin.**

3. I wouldn't like to completely change/rework mdbook-epub approach as the author is @Michael-F-Bryan. I would like to extend mdbook (by adding one more trait's method) to give a possibility reuse LinkPreprocessor internal functionality for epub generation like this:
```
pub trait Preprocessor: PreprocessorClone {
.............
        fn preprocess_chapter(&self, ctx: &PreprocessorContext, chapter: &mut Chapter) -> Result<()> {
}
```
4. _Additionally I would like to clone LinkPreprocessor from mdbook context into mdbook-epub context for calling newly added method. (I'm not 100% sure if it's a best approach, but it works at least.)_

5. One more moment with content generated by LinkPreprocessor is following:
Internal method functionality 
https://github.com/rust-lang/mdBook/blob/ba6bffac5a2eac13a10b5fc91601dc167ef89449/src/preprocess/links.rs#L294
`fn render_with_path<P: AsRef<Path>>(&self, base: P) -> Result<String> {`
replaces link _'{{#rustdoc_include ../listings/c....'_ by the 'Rust source code' content from another file and comments out by # symbol some code lines (sometimes).
The Rust code comments by # dash symbol are OK for HTML case.
But the # dash symbol generates 'H1 title' in case EPUB (later internally with 'post processing' in mdbook-epub). So it's better to remove completely those 'commented out' source code lines in case epub content generation.

6. Here is a complete diff for my changes that gives ability to reuse and call LinkPreprocessor correctly inside mdbook-epub plugin context. https://github.com/rust-lang/mdBook/compare/master...blandger:master

7. _Optionally.... If you are not tired by now, there are all 'mdbook-epub' plugin source changes with using 'newly added mdbook code' and reusing LinkPreprocessor functionality inside._
https://github.com/Michael-F-Bryan/mdbook-epub/compare/master...blandger:add_links_preprocessing

**Comment by blandger** [comment]
That is good to hear that there is no chances to contribute to project.
So mdbook-epub plugin won't work with mdbook as it is for a long time.

**Here is a complete diff for my changes that gives ability to reuse and call LinkPreprocessor correctly inside mdbook-epub plugin context after copying it from mdbook context.** 
https://github.com/rust-lang/mdBook/compare/master...blandger:master
