### ISSUE TITLE
No arrows

### ISSUE THREAD

**Issue by tripleo1** [rust-lang/mdBook#1415]
When I build the rust-lang mdbook, there are no arrows in the sidebar.

Oh, this seems to be by design as it is the same on the web.

But it is not the case for [Rust By Example](https://doc.rust-lang.org/stable/rust-by-example/)

What is the difference?

 
![rust  2020-12-28 05-12-52](https://user-images.githubusercontent.com/50311859/103207154-9f1d7180-48cb-11eb-924d-9f18a47c61cb.png)

See https://github.com/rust-lang/book/issues/2531

**Comment by ehuss** [comment]
Collapsible sidebar table-of-contents is an option in the book configuration that is opt-in.  See the `[output.html.fold]` section in the [config docs](https://rust-lang.github.io/mdBook/format/config.html).

**Comment by ehuss** [comment]
Closing, as I think this is referring to folding.
