### ISSUE TITLE
confusing guide - missing body.css

### ISSUE THREAD

**Issue by RustyJoeM** [rust-lang/mdBook#1429]
Hello,

I'm trying to modify the theme and would like to add custom background, change style of paragraph etc.

Reading the guide (https://rust-lang.github.io/mdBook/format/theme/index.html) - `body.css` file seems to be place to be edited... However, i fail to find such file in the location propsed by the guide...

Did i misunderstand some concept, or is the guide out of sync with mdbook behavior?

```
user@dev:~$ mdbook --version; mdbook init --theme test-book
mdbook v0.4.5

Copying the default theme to src
This could potentially overwrite files already present in that directory.

Are you sure you want to continue? (y/n) y

Do you want a .gitignore to be created? (y/n)
y
What title would you like to give the book?
hello
2021-01-05 19:56:06 [INFO] (mdbook::book::init): Creating a new book with stub content

All done, no errors...
user@dev:~$ tree ./test-book/
./test-book/
├── book
├── book.toml
└── src
    ├── chapter_1.md
    ├── SUMMARY.md
    └── theme
        ├── book.js
        ├── css
        │   ├── chrome.css
        │   ├── general.css
        │   ├── print.css
        │   └── variables.css
        ├── favicon.png
        ├── favicon.svg
        ├── highlight.css
        ├── highlight.js
        └── index.hbs

4 directories, 13 files
```

**Comment by ehuss** [comment]
The docs look to be a little out of date, I have posted an update at #1431.

You can look at the [source of the main template](https://github.com/rust-lang/mdBook/blob/76cd39e5e28aab7de37b5d4ed9b189f5491c3313/src/theme/index.hbs#L29-L34) to see how it loads CSS.
