### ISSUE TITLE
Stray spacing of code blocks containing injected main

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/mdBook#1433]
For example see the first code block in https://doc.rust-lang.org/1.47.0/book/ch03-02-data-types.html.

````markdown
```rust
let guess: u32 = "42".parse().expect("Not a number!");
```
````

<br>

#### Screenshot:

![Screenshot from 2020-11-05 21-31-53](https://user-images.githubusercontent.com/1940490/98330028-6689a780-1fae-11eb-8e85-c617e0197b92.png)

**Comment by dtolnay** [comment]
#### Desired:

![Screenshot from 2020-11-05 21-32-20](https://user-images.githubusercontent.com/1940490/98330033-6ab5c500-1fae-11eb-8f63-fdb4fe8a3849.png)

<br>

#1374 has one fix, but it isn't perfect because a long first line on a narrow screen can cause the buttons to overlap the code when they didn't before. (There is a separate bug about this: #1322.)

**Comment by pickfire** [comment]
But I see that mdbook examples itself does not have the extra spacing.

![image](https://user-images.githubusercontent.com/4687791/103844159-3eb0e000-50d4-11eb-83fb-82de25a6d35f.png)

**Comment by pickfire** [comment]
Oh, the newline only appears on some block.

![Screen Shot 2021-01-07 at 10 47 32](https://user-images.githubusercontent.com/4687791/103844844-c77c4b80-50d5-11eb-8189-87eda427c01e.png)

What if we put it the buttons closer to the borders on mobile? So even if it did overlap, it overlap half of it.

Or maybe we can put the buttons outside of the box in mobile.

**Comment by dtolnay** [comment]
> But I see that mdbook examples itself does not have the extra spacing.

Correct. That code block does not have an injected `main`. The `main` is handwritten.

https://github.com/rust-lang/mdBook/blob/3d55375f618594d62707eab18b98d32c52b4c9b7/guide/src/format/mdbook.md#L21-L28

**Comment by ehuss** [comment]
I posted #1806 with a proposed fix.

I would appreciate if you could take a look and see if you have any thoughts.  I posted a demo at https://ehuss.github.io/rust-book/.  If you could look through some examples, try different browsers and platforms, different color themes, etc.  If you have access to Android, that would particularly be nice to test since I don't have access to that.

**Comment by dtolnay** [comment]
Android/Firefox:

<img width="100" src="https://user-images.githubusercontent.com/1940490/168720663-fae0ec0e-0f4f-4323-bc4a-762a3230d0c4.png"> <img width="100" src="https://user-images.githubusercontent.com/1940490/168720672-85b548ee-37df-4043-8073-e5be15f75853.png">

Chrome looks substantially identical.

The non-editable code blocks look passable to me, certainly better than before your change. The editable ones are not getting the same padding and are not so good I think.

What if we offset the icons by half a line upwards, so that they are half in/half out of the box? Then we could get away with less padding on those non-editable code blocks, since I think I'd prefer less than what's in the screenshot. If half in/half out looks janky, they could get either a tab (background extending up in the vicinity of the icons) or notch (background carved downward away from the vicinity of the icons).
