### ISSUE TITLE
Reader functionality in mdbook/create external tool to read mdbooks in terminal

### ISSUE THREAD

**Issue by simonsan** [rust-lang/mdBook#1439]
An idea that came from [rust-patterns](https://github.com/rust-unofficial/patterns/issues/170):

A tool that is able to pull in mdbook repositories and shows it `man`-like in the terminal, so people could actually search within these articles from the command line. 

Outline:
- distributable via `crate.io`
- `cargo install mdb-reader` to install, (thus updatable with `cargo install-update mdb-reader` to update)
- you could use that tool to search e.g `patterns` on the commandline working like `man` on Linux (e.g. [rusty-man](https://crates.io/crates/rusty-man))
- `mdbook read rust-patterns builder` (or anything alike) prints the `builder pattern` article in a nice commandline-native way
- nice to read something while developing in IDE

**Comment by ehuss** [comment]
I'm going to close, as I don't think this is something we will likely include natively.  However, it seems like something that could very likely be supported as a [custom renderer](https://rust-lang.github.io/mdBook/for_developers/backends.html).
