### ISSUE TITLE
Changes in the destinations of symbolic links not detected

### ISSUE THREAD

**Issue by FrankHB** [rust-lang/mdBook#1441]
Changes made in the destinations of symbolic links are not detected by `mdbook serve` (tested in the target `x86_64-pc-windows-gnu`).

The [CHANGELOG](https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#mdbook-044) is not accurate for this case (although it can work in cases like #1323).

**Comment by KFearsoff** [comment]
@rustbot label +C-bug +Command-serve +Command-watch +S-Duplicate

See https://github.com/rust-lang/mdBook/issues/2102#issuecomment-1810982299
