### ISSUE TITLE
Stylesheet contrast issues

### ISSUE THREAD

**Issue by endgame** [rust-lang/mdBook#1442]
Some of the styling is quite low-contrast, which makes it harder to read and navigate than it could be:

* The `<h1>` of the currently-viewed page is light-on-light,
* I didn't notice the `<` and `>` previous/next page controls for a couple of minutes because they render light-on-light,
* Inline code (where syntax highlighting is not applied) is dark-on-dark.

I'm no designer so I hesitate to suggest specific fixes, but https://contrastchecker.com/ is good at least to check body text.

(Re-reporting scrive/nix-workshop#1 upstream.)

**Comment by ehuss** [comment]
Can you check out https://github.com/rust-lang/mdBook/pull/1353 and see if those color adjustments help?

**Comment by endgame** [comment]
Yes, the "contrast" theme is a massive improvement.

**Comment by tim-seoss** [comment]
Glad you've found that useful - any critical feedback on that theme is also welcome of course!

**Comment by tim-seoss** [comment]
I'd be interested to hear others' thoughts on:
- Is `contrast` a good name for the new theme?
- Would a revised version of the PR, which instead implements the new theme in the `light` theme be preferable (or not!)?  If "yes", then the existing `light` colour palette could either be removed, or renamed to something like `soft`?
- Any aesthetic suggestions?

Thanks!
