### ISSUE TITLE
Can be upgrade msrv?

### ISSUE THREAD

**Issue by apatniv** [rust-lang/mdBook#1450]
Currently, the mrsv seems to be  `1.39.0` which was released on `2019-11-07`.  The current version is `1.49.0`. Can we upgrade to say version `1.45.0` which was released on  `2020-07-16`.

**Comment by ehuss** [comment]
Is there a reason to change it?

**Comment by apatniv** [comment]
I feel it is good to keep up the latest releases of rust considering that mdbook is still not 1.0 yet.  I understand that this may force some of the users to update their toolchain.   

I choose Version 1.45.0 as it was released almost 6 months back and it contains some of the features for addressing #1414

**Comment by ehuss** [comment]
The MSRV was updated to 1.42 in #1528.  Generally, I'm fine with updating it if there is a reason (like new functionality that would be helpful that is only in a new version, or dependencies require it).
