### ISSUE TITLE
How to override highlight.js?

### ISSUE THREAD

**Issue by Hoffenbar** [rust-lang/mdBook#1458]
Is there some way to achieve that a modified version auf highlight.js is not overwritten with the build-in one each time the book is regenerated? E.g., mdbook.exe could look for a modified version somewhere along the book source and use that version then.

**Comment by ZeWaka** [comment]
Mine doesn't get overwritten, I'm unable to reproduce this.

**Comment by Hoffenbar** [comment]
Then maybe I'm doing something wrong. Each time I do a build or serve, the file book/highlight.js is the initial one, not the one I'm copying in there after that (I'm doing this because I'm missing some highlighters).

**Comment by ZeWaka** [comment]
> Then maybe I'm doing something wrong. Each time I do a build or serve, the file book/highlight.js is the initial one, not the one I'm copying in there after that (I'm doing this because I'm missing some highlighters). I'm on windows.

Are you following the instructions and putting your modified highlight.js in the `theme` folder? Like this: 
![image](https://user-images.githubusercontent.com/4741640/109430083-3aa68d80-79b4-11eb-83e2-fc6ce95b2c9e.png)

**Comment by Hoffenbar** [comment]
Yes, it's there.  And if I remember well, with 0.4.5, it worked as expected. Or is it the timestamp of the highlight.js in the the theme-folder which prevents it from beeing copied over?

**Comment by Hoffenbar** [comment]
The overwrite only happens the first time calling `mdbook serve`. Subsequent changes to the sources only update the changed files.

**Comment by Hoffenbar** [comment]
I was wrong. highlight.js gets overwritten everytime a change is monitored (mdbook serve).

**Comment by Hoffenbar** [comment]
I deactivated the entry `theme = "light"` under `[output.html]`in the `book.toml` . Since then, highlight.js isn't overwritten anymore, it seems. Will investigate further.

**Comment by ehuss** [comment]
I'm going to close since this doesn't have a clear reproduction. If you're able to reproduce, feel free to reopen with instructions on how to reproduce.
