### ISSUE TITLE
[feature request] Adding a comment section at the end of a chapter and/or page

### ISSUE THREAD

**Issue by KennethEnevoldsen** [rust-lang/mdBook#1460]
Hi, I want to allow students to engage with the material, by adding a comment section at the end of the chapter. I can see that something similar has been asked previously in this [issue](https://github.com/rust-lang/mdBook/issues/99)  but get an error when I try to open it. 

From the title however it seems to ask for inline comments, while I would be satisfied with simply adding a comment section at the end of the chapter.

Sorry if this repeats the previous issue.

**Comment by ZeWaka** [comment]
Same issue essentially, you essentially need to move away from the model of a static site you can put on GitHub Pages, to a dynamic server-hosted model.

**Comment by KennethEnevoldsen** [comment]
Hmm not entirely you can add it as html code using e.g.:
https://www.htmlcommentbox.com

an example of where it is used on a static site:
https://www.kennethenevoldsen.com/post/new-fast-and-efficient-state-of-the-art-in-danish-nlp/

As this solves my issue I will close it.
