### ISSUE TITLE
Use my crate in playable snippets

### ISSUE THREAD

**Issue by ManevilleF** [rust-lang/mdBook#1467]
Hello,

I don't know if this is possible but I would like to use my crate, which my `mdbook` is about in the playable snippets.

How do I do this? If I simply `use mycrate` compilation fails, if I use `extern crate mycrate` the snippet is no longer playable.

I don't find any information about this in the `playground` documentation nor in the `mdbook` book.

**Comment by ehuss** [comment]
It's not possible with the Rust Playground, it uses a closed Docker container to run examples, and only includes a set of the most common crates.

There is #706 to track adding the ability to link to external crates for `mdbook test`.

**Comment by ManevilleF** [comment]
Thank you !
