### ISSUE TITLE
Add support for inline diffs

### ISSUE THREAD

**Issue by ManevilleF** [rust-lang/mdBook#1468]
Gitlab support markdown inline diff like:
```diff
#[derive(Clone {+ , Debug +}, {- Copy -})]
pub struct Example  {
}
```
It would be nice for `mdbook` to handle it as well.

Also, it would be nice to be able to do `diff rust` and get both CSS applied.

Edit: Github doesn't handle inline diffs so the example is not rendered correctly

**Comment by ZeWaka** [comment]
Do you just mean the syntax highlighting? So, within another code block? I'm not sure GitLab supports that, going by [here](https://docs.gitlab.com/ee/user/markdown.html#inline-diff).

**Comment by ManevilleF** [comment]
@ZeWaka  I'm talking about https://docs.gitlab.com/ee/user/markdown.html#inline-diff

**Comment by ZeWaka** [comment]
> @ZeWaka  I'm talking about https://docs.gitlab.com/ee/user/markdown.html#inline-diff

Yeah, I linked that in my post... There's no highlighting happening within another lang code block there.

**Comment by ManevilleF** [comment]
Indeed, I just tried it and it doesn't seem to work. Too bad, It would be a nice feature
