### ISSUE TITLE
Support for Right to Left

### ISSUE THREAD

**Issue by moaz-mokhtar** [rust-lang/mdBook#1486]
EDITED

Very thankful for this tool. 
We need to add support to configure RTL languages (ex: Arabic) to be appeared professionally.

I did test `mdbook` for Arabic text as below:
![image](https://user-images.githubusercontent.com/5870208/111000776-56823a00-838b-11eb-9a07-38881dac8728.png)

---
### First fix
I did edit `html` tag in resulted `chapter_1.html` as below to support `rtl`:
```html
<html dir="rtl" lang="en" class="sidebar-visible no-js light">

```
It is appeared as below:
![image](https://user-images.githubusercontent.com/5870208/111001087-d4464580-838b-11eb-9d15-525e88029b79.png)

---
### Second fix
I did edit the linked stylesheet in `chapter_1.html` as below to right align.
```html
<link rel="stylesheet" type="text/css" href="font-awesome-rtl.css">
```
Appeared as below:
![image](https://user-images.githubusercontent.com/5870208/111002260-c8f41980-838d-11eb-9e49-f357f25a74de.png)

---

Still found issue:
- Sidebar is not Right aligned.

**Comment by crawfxrd** [comment]
> Sidebar is not Right aligned

Seems to be because `src/theme/css/chrome.css` (`build/css/chrome.css`) only sets `padding-left` for `.chapter`.

**Comment by moaz-mokhtar** [comment]
Thank you Tim, but actually I think we need to right alight the whole sidebar.

I tried to change padding-left to padding-right but same issue which only did change alight of the chapter name inside sidebar not the whole sidebar.

When `padding-lift` disabled, result is as below:
![image](https://user-images.githubusercontent.com/5870208/111050996-a24ee500-8458-11eb-9d01-3c26bf3dfd95.png)

When
```css
.chapter {
  list-style: none outside none;
  /* padding-left: 0; */
  padding-right: 0;
  line-height: 2.2em;
}
```
Result as below:
![image](https://user-images.githubusercontent.com/5870208/111051023-d62a0a80-8458-11eb-91c9-7de22c4da445.png)


So I think we need to fix the css properties to confirm RTL working properly.

**Comment by crawfxrd** [comment]
Ah, I see. I thought you just meant the huge padding in the sidebar itself.

So more like this:

```diff
 .sidebar {
     ...
-    left:0;
+    right: 0;
     ...
 }
```

```diff
 @media only screen and (min-width: 620px) {
     .sidebar-visible .page-wrapper {
         transform: none;
-        margin-left: var(--sidebar-width);
+        margin-right: var(--sidebar-width);
     }
 }
```

```diff
 .next {
-    float: right;
+    float: left;
     right: var(--page-padding);
}
```

The arrow directions for next/previous (set by class `.fa-angle-{left,right}`) would need to change as well.

**Comment by crawfxrd** [comment]
Best solution would probably be to use [CSS logical properties](https://drafts.csswg.org/css-logical/). Most of them seem to be supported on everything except Internet Explorer.

**Comment by hamidrezakp** [comment]
Hey @moaz-mokhtar and @crawfxrd , I don't know if this is directly related to this RTL support but in order to have good quality support for Arabic-script languages like `Arabic` and `Persian` we need to use proper fonts than `open-sans`.

Is there any option to configure specific fonts for specific languages?

**Comment by ehuss** [comment]
I'm going to close as basic rtl support is now available with the `book.text-direction` option ([docs](https://rust-lang.github.io/mdBook/format/configuration/general.html?highlight=rtl#supported-configuration-options)).
