### ISSUE TITLE
similarly named headings are not linked correctly

### ISSUE THREAD

**Issue by simonmichael** [rust-lang/mdBook#1493]
I believe the current release does not handle duplicated headings on a page well. Eg https://hledger.org/hledger.html has a "tags" heading under COMMANDS (https://hledger.org/hledger.html#tags) and a "Tags" heading under JOURNAL FORMAT (https://hledger.org/hledger.html#tags-1). Distinct anchors are created, but links in the page TOC and in search results point only to the first (https://hledger.org/hledger.html#tags). This can be quite confusing.
https://github.com/simonmichael/hledger_site/issues/33

**Comment by ehuss** [comment]
Thanks for the report!  mdBook doesn't produce a TOC, so maybe that is from a plugin?  As for the search results, issue #720 is tracking the ids not being handled correctly.

**Comment by simonmichael** [comment]
Oops, quite right. I will take it up with mdbook-toc. 

Thanks for mdbook !

**Comment by ehuss** [comment]
Closing as this seems to have been an mdbook-toc issue.
