### ISSUE TITLE
gitlab ci failed with errors for pages 

### ISSUE THREAD

**Issue by ashutoshmjain** [rust-lang/mdBook#1495]
When I added the .gitlab-ci-yml  , the git lab ci started but failed with following error 

'''

error: aborting due to previous error

error: failed to compile `mdbook v0.4.7`, intermediate artifacts can be found at `/tmp/cargo-install2prHDz`

Caused by:
  could not compile `proc-macro-hack`
''' 
Complete log from gitlab runner attached below 

[gitlab-ci-job.log](https://github.com/rust-lang/mdBook/files/6226128/gitlab-ci-job.log)

**Comment by syntezoid** [comment]
I have the same problem, with gitlab CI from [mdbook guide](https://rust-lang.github.io/mdBook/continuous-integration.html).
[gitlab-ci-job.log](https://github.com/rust-lang/mdBook/files/6328309/gitlab-ci-job.log)

**Comment by almereyda** [comment]
Same error here. The failure appears to be:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.0.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.1.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.10.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.11.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.12.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.13.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.14.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.15.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.2.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.3.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.4.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.5.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.6.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.7.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.8.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.proc_macro_hack.2hwc38bi-cgu.9.rcgu.o" "-o" "/tmp/cargo-installswn5WB/release/deps/libproc_macro_hack-bc8fe316d33edfbf.so" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.4f9erz1p7mo6q6x.rcgu.o" "/tmp/cargo-installswn5WB/release/deps/proc_macro_hack-bc8fe316d33edfbf.1mgswikucdidabx.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/tmp/cargo-installswn5WB/release/deps" "-L" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libproc_macro-5fe61f6531bffa91.rlib" "-Wl,--start-group" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-a022ba88caf346cc.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-36ad53f06d2dfa4b.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libminiz_oxide-7c7804ff82de4a2d.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libadler-3f7bdf90a2b4f8fc.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libobject-694f73b3d2449c2a.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libaddr2line-1150bf52f1abae51.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libgimli-90c6d090a256e3eb.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-54c2c969bd4088b4.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-573562ba61cce1fd.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-899352146d4a3135.rlib" "/tmp/rustc16Aa9x/libunwind-ad44bf4bb1b1e673.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-637426cb1244bccb.rlib" "/tmp/rustc16Aa9x/liblibc-24859b86ebe92dc9.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-902da53b7d14709a.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-72749be80d046134.rlib" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-4479f7a1fb7eb5fd.rlib" "-Wl,--end-group" "/usr/local/rustup/toolchains/1.51.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-9d8678953f36ed76.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc"
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `proc-macro-hack`
```

The linker is complaining about missing headers for crti.o, which may be due to Alpine's use of `musl`.

If you replace `rust:alpine` with only `rust` in your `.gitlab-ci.yml` it builds just fine.

**Comment by ashutoshmjain** [comment]
Thanks a ton  .. That seems to have done the trick

**Comment by ashutoshmjain** [comment]
Reopening the issue because the gitlab ci failed after I made a little change and pushed a commit  .. Here is  the raw 

---
[0KRunning with gitlab-runner 13.11.0-rc1 (286f7013)
[0;m[0K  on docker-auto-scale fa6cab46
[0;m[0K  feature flags: FF_GITLAB_REGISTRY_HELPER_IMAGE:true
[0;msection_start:1619191857:resolve_secrets
[0K[0K[36;1mResolving secrets[0;m
[0;msection_end:1619191857:resolve_secrets
[0Ksection_start:1619191857:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m
[0;m[0KUsing Docker executor with image rust ...
[0;m[0KPulling docker image rust ...
[0;m[0KUsing docker image sha256:5cbef0869ecba53e84d1e409f2721a328094b4fa825c7447138e369ad3a27558 for rust with digest rust@sha256:180f72fd8e8b40ad6499e71d59e291f6cade96603ace1af82694b7292e5e3b49 ...
[0;msection_end:1619191901:prepare_executor
[0Ksection_start:1619191901:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-fa6cab46-project-26093111-concurrent-0 via runner-fa6cab46-srm-1619191809-e241d36c...
section_end:1619191903:prepare_script
[0Ksection_start:1619191903:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Initialized empty Git repository in /builds/ashutoshmjain/arjunuvaach/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 7208b829 as main...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1619191905:get_sources
[0Ksection_start:1619191905:restore_cache
[0K[0K[36;1mRestoring cache[0;m
[0;m[32;1mChecking cache for default...[0;m
Downloading cache.zip from https://storage.googleapis.com/gitlab-com-runners-cache/project/26093111/default[0;m 
[32;1mSuccessfully extracted cache[0;m
section_end:1619191906:restore_cache
[0Ksection_start:1619191906:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m
[0;m[0KUsing docker image sha256:5cbef0869ecba53e84d1e409f2721a328094b4fa825c7447138e369ad3a27558 for rust with digest rust@sha256:180f72fd8e8b40ad6499e71d59e291f6cade96603ace1af82694b7292e5e3b49 ...
[0;m[32;1m$ export PATH="$PATH:$CARGO_HOME/bin" - mdbook --version || cargo install mdbook[0;m
/bin/bash: line 119: export: `-': not a valid identifier
/bin/bash: line 119: export: `--version': not a valid identifier
    Updating crates.io index
 Downloading crates ...
  Downloaded mdbook v0.4.7
error: binary `mdbook` already exists in destination
Add --force to overwrite
section_end:1619191947:step_script
[0Ksection_start:1619191948:cleanup_file_variables
[0K[0K[36;1mCleaning up file based variables[0;m
[0;msection_end:1619191948:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m

------

It seems that the gitlab ci is  trying to download mdnbook again instead of pushing only the changes  ..

**Comment by ehuss** [comment]
@ashutoshmjain It is hard to tell what is going on without seeing the CI config file, but from the error I would assume you are missing a newline between the `export` and the next line.

If you are having trouble setting up a CI configuration, I would recommend trying a user forum (maybe https://forum.gitlab.com/?).

**Comment by ehuss** [comment]
I'm going to close, as this appears to be a configuration error.
