### ISSUE TITLE
Check for missing images

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rust-lang/mdBook#1499]
Am I correct that when an image (svg in my case) referenced in a Markdown file is missing, that mdbook doesn’t produce any warning or error during build?

And the linkcheck plugin neither?

Would you consider that functionality could be part of mdbook (i.e. an RFE) or you would suggest I look to a plugin to add it to?

**Comment by ehuss** [comment]
Have you tried the [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck) plugin?  It appears to validate images:

```
error: File not found: path/to/img.jpg
  ┌─ chapter_1.md:3:1
  │
3 │ ![Alt text](path/to/img.jpg "optional title")
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: path/to/img.jpg
```

**Comment by andrewdavidmackenzie** [comment]
I'll try to next week when back from PTO.

**Comment by andrewdavidmackenzie** [comment]
OK, it looks like a problem with GH_pages Travis deployment. The files are present locally but not uploaded. So not an issue here *or* with lintcheck :-(
