### ISSUE TITLE
[Question] Is there a way to include remote JavaScript and CSS ?

### ISSUE THREAD

**Issue by phunkpwnz** [rust-lang/mdBook#1503]
I'm reading through the available documentation and I only see an option in book.toml to include local JavaScript and CSS files. Is there a way to include remotely hosted CSS and JavaScript files?

Thanks in advance.

**Comment by ehuss** [comment]
I would suggest adding [head.hbs](https://rust-lang.github.io/mdBook/format/theme/index.html) and add whatever HTML tags you want to that.

**Comment by phunkpwnz** [comment]
Alright thanks!
