### ISSUE TITLE
Add a clippy check to the Actions workflow

### ISSUE THREAD

**Issue by joshrotenberg** [rust-lang/mdBook#1516]
Running clippy turns up a decent chunk of warnings. Adding a check in `.github/workflows/main.yml` and then cleaning them up would be cool.

**Comment by ehuss** [comment]
Thanks for the suggestion, however I would prefer to not automatically check for clippy in CI at this time.  If you would like to post PRs to clean up the code, that would be appreciated, I would just ask to try to keep the PRs relatively small (giant "run clippy" PRs can be hard to review).
