### ISSUE TITLE
mdbook init force flag documentation is wrong

### ISSUE THREAD

**Issue by joshrotenberg** [rust-lang/mdBook#1556]
The documentation for the force flag for the `init` subcommand states "Skips confirmation prompts", but it actually only affects whether a prompt is given if the `--theme` flag is present and the theme directory exists. It has no effect on the prompts for creating the `.gitignore` or getting the book name (which, ok, isn't technically a "confirmation" prompt). 

The easiest fix is to just update the documentation. Another fix might be to make the `.gitignore` prompt also respect the flag so that the "confirmation" part is technically right. It might also be helpful to add a flag for creating the `.gitignore` and the book title too to round things out and make book initialization fully prompt free if someone desires.

Something like this. If `--force` is specified, in addition to the current behavior, init the book with the defaults for `--with-gitignore` and `--with-title`.

```bash
mdbook-init v0.4.8
Creates the boilerplate structure and files for a new book

USAGE:
    mdbook init [FLAGS] [dir]

FLAGS:
        --force             Skips confirmation prompts
    -h, --help              Prints help information
        --theme             Copies the default theme into your source folder
    -V, --version           Prints version information
        --with-gitignore    Creates a .gitignore file [default: true]
        --with-title        Set the book title [default: "my book"]

ARGS:
    <dir>    Directory to create the book in
             (Defaults to the Current Directory when omitted)
```

**Comment by ehuss** [comment]
Hm, looks like this was changed as part of #491, but there doesn't seem to be an explanation why.  I would say the original intent is that it avoids all prompts.  I agree that `--force` should probably not do any prompts.

**Comment by joshrotenberg** [comment]
Thoughts on adding the extra flags as well to make it possible to supply an answer for book name and .gitignore creation as part of the fix here? Or do you prefer to just make force do what it says and use defaults for those (and maybe call them out in the documentation string)?

**Comment by ehuss** [comment]
Preferably have separate PRs.

As for the flags, how about `--title=...` and `--ignore=git` or `--ignore=none`?

**Comment by joshrotenberg** [comment]
> As for the flags, how about `--title=...` and `--ignore=git` or `--ignore=none`?

I went with `--gitignore` as a boolean. If we wanted to support other `.ignore` file types, though, `--ignore=<type>` is probably better ... but the only other one I know is `.hgignore`.

The next step would be to set defaults and check `--force` first for both args:

* if `--force`, set default
* if `is_present`, set from command line value
* otherwise prompt

**Comment by ISSOtm** [comment]
What's the status on this?

**Comment by seanpoulter** [comment]
I just found this issue. Would you welcome a PR? What default would you want for the title, `Example book` like the docs?

**Comment by ehuss** [comment]
I'm not certain about the defaults, but I'll suggest:

* Assume `--ignore=none`
* Set `BookConfig.title` to None (no title)

**Comment by seanpoulter** [comment]
Thanks @ehuss. I've got a PR #2057 up.
