### ISSUE TITLE
Playground Communication: timeout from the published guide

### ISSUE THREAD

**Issue by joshrotenberg** [rust-lang/mdBook#1561]
A colleague of mine (@djcarpe)  mentioned that the he was getting errors from the Rust playground examples in the [guide](https://rust-lang.github.io/mdBook/format/mdbook.html). 

I'm seeing the same consistently on the published guide, but when I run the guide locally with `mdbook serve` the error is intermittent.

<img width="880" alt="Screen Shot 2021-06-01 at 9 12 48 AM" src="https://user-images.githubusercontent.com/3231/120357008-d1d3f780-c2b9-11eb-999c-78ae11400df6.png">

**Comment by ehuss** [comment]
Timeouts are not unusual, as the playground has limited resources, and if too many people are using it at once it will time out.  I also think there has been an unexplained increase in timeouts. This might be better followed up on the playground tracker, and I think there's already an issue for it: https://github.com/integer32llc/rust-playground/issues/712.

**Comment by joshrotenberg** [comment]
Closing this since it's probably not an mdbook specific issue.
