### ISSUE TITLE
headings differing only in case are linked wrongly in search results

### ISSUE THREAD

**Issue by simonmichael** [rust-lang/mdBook#1579]
https://github.com/badboy/mdbook-toc/issues/16 seems to be an mdBook issue. At https://hledger.org/hledger.html I have "tags" and "Tags" sections. This is almost working now, except that in https://hledger.org/hledger.html?search=tags, both results link to the "tags" section. [The first result, "Tags", should link to <https://hledger.org/hledger.html?highlight=tags#tags-1>]

[cc <https://github.com/simonmichael/hledger_site/issues/33>]

**Comment by ehuss** [comment]
This is mentioned in #720 (duplicate header names don't use the same logic).  It would be nice if they could use the same code.

**Comment by ehuss** [comment]
Closing as resolved by #1749.
