### ISSUE TITLE
Code spans in headers are highlighted with editable playpen

### ISSUE THREAD

**Issue by ehuss** [rust-lang/mdBook#1580]
If `output.html.playpen.editable = true` is set, then any headers with a code span end up with the span highlighted as a link.  This is not intended, and I'm not sure why it is happening. This was previously fixed in #1162, but for some reason that didn't fix it with editable code blocks.

Example:

```
## This has a `code` span
```

Is rendered as:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/43198/122329046-91918d80-cee5-11eb-835a-1c6c07c7e344.png">

when it should be:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/43198/122329069-9bb38c00-cee5-11eb-85c2-274138a52682.png">

**Comment by FWYongxing** [comment]
#1613
