### ISSUE TITLE
Tables with column ending with HTML tag aren't rendered right

### ISSUE THREAD

**Issue by Smittyvb** [rust-lang/mdBook#1583]
```markdown
a | b
--|--
<span>a</span> | b
```
produces
![a and b are on two different rows](https://user-images.githubusercontent.com/10530973/123012823-f723c500-d390-11eb-8dea-a6d408671d65.png)
The table should be one row, not two rows with one column per row.

**Comment by ehuss** [comment]
Hm, that's strange. It seems to render fine for me:

<img width="116" alt="image" src="https://user-images.githubusercontent.com/43198/123014317-d94b6580-d37a-11eb-93ab-8629d19a3a45.png">

Which version of mdbook are you using?  Which browser?

**Comment by Smittyvb** [comment]
@ehuss It turns out the issue was being caused by an extension, `mdbook-toc` that I was using in the book I was testing with (which is strange, because this doesn't use any of that extension's features). I've created an issue there: https://github.com/badboy/mdbook-toc/issues/19. Sorry for the confusion.
