### ISSUE TITLE
Add GH Pages + GH Actions flow to docs

### ISSUE THREAD

**Issue by MichaelCurrin** [rust-lang/mdBook#1590]
There are instructions for GH Pages using Travis

https://rust-lang.github.io/mdBook/continuous-integration.html#deploying-your-book-to-github-pages

But I am a fan of using GH Actions.

I have a workflow in use here which I would be happy to add to the guide.

https://github.com/MichaelCurrin/mdbook-quickstart/blob/main/.github/workflows/main.yml

**Comment by joshxyzhimself** [comment]
We got quicker build-times using this workflow

```

https://github.com/webdevph2/resources/blob/main/.github/workflows/main.yml

**Comment by ISSOtm** [comment]
(Well, you might want to try piping `curl` directly into `tar` instead of saving to a temporary file.)

**Comment by jiyinyiyong** [comment]
Cool with binary! how about lintchecker, is there a similar trick?
