### ISSUE TITLE
Rust edition 2021 support

### ISSUE THREAD

**Issue by ehuss** [rust-lang/mdBook#1593]
mdbook needs to be updated to support the 2021 edition configuration for Rust.  There are several things to do here:

* Update [`RustEdition`](https://github.com/rust-lang/mdBook/blob/b3c0b013501b43468852f4fb648e7a80495f8cd4/src/config.rs#L469-L476) and everything that references it (including the javascript code for the playground).  In hindsight this probably should have been a free-form string (so it wouldn't need updating each time), but that can't change now. Perhaps that would be good to change for 0.5.
* Update documentation.
* Unfortunately until the edition is stabilized, it requires the `-Zunstable-options` flag to be passed to rustdoc. I'm thinking maybe just pass that for now, and then remove it when it is stabilized?

**Comment by Dylan-DPC** [comment]
> Unfortunately until the edition is stabilized, it requires the -Zunstable-options flag to be passed to rustdoc. I'm thinking maybe just pass that for now, and then remove it when it is stabilized?

yeah that sounds fine.
