### ISSUE TITLE
Can mdBook implement some simple replacements?

### ISSUE THREAD

**Issue by KevinBlandy** [rust-lang/mdBook#1600]
I use mdBook to write the documentation, which needs to declare the version number in many places. Something like this.
  
    ```markdown
    Latest Version: 0.0.1
    ```

But after the version update, I need to manually go and change the version number information declared in various places, which is too tiring.

I wish it could use placeholders to replace some variables in the configuration file, like the template engine does.

Like this.

### foo.md

    ```markdown
    Latest Version: {{ .version }}
    ```

### conifg

```properties
version=0.0.1
```

Each time a page is generated, the placeholder in the md file is replaced with the value of the property in the configuration.

Any good suggestions? Thanks!

> The mdbook is really great, simple and practical.

**Comment by joshrotenberg** [comment]
I haven't used it, but it looks like this [mdbook-variables](https://crates.io/crates/mdbook-variables) crate might do what you want. Looks like it might just do regex based replacements, but it does make me wonder if a handlebars based preprocessor would be a useful addition to the list.
