### ISSUE TITLE
Test fails to compile when an item is `use`d inside a function

### ISSUE THREAD

**Issue by lo48576** [rust-lang/mdBook#1605]
Tested with mdbook v0.4.10 and the latest `master` branch.

The code below let `mdbook test` fail while I expected it to successfully compile:

```rust
mod foo {
    pub struct Foo;
}

fn function() {
    use foo::Foo;
}
```

Error message:

```
---- /tmp/mdbook-ARFYcC/modules.md - modules (line 66) stdout ----
error[E0432]: unresolved import `foo`
 --> /tmp/mdbook-ARFYcC/modules.md:72:9
  |
8 |     use foo::Foo;
  |         ^^^ maybe a missing crate `foo`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
Couldn't compile the test.
```

The same code compiles successfully (as expected) on the playground: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=feb8c8fff473c2e2f4708c01e66d125e>.

Is this intended behavior?

**Comment by ehuss** [comment]
Yes. There are two possible solutions:

* Add `#fn main() {}` to the bottom.  If you don't have a main, `rustdoc` wraps it in a `fn main {...}` function.
* Use edition2018 (or set the edition in book.toml).  

`use` paths in the 2015 edition are relative to the crate root, which means you can't `use` a module from within a function. In 2018, `use` paths are like normal paths, and are relative to the current scope.

You can read more about writing tests here: https://doc.rust-lang.org/nightly/rustdoc/documentation-tests.html

**Comment by lo48576** [comment]
Oh, I didn't noticed that edition 2015 is used as the default...
I'll use edition 2018.
Thank you for quick response!
