### ISSUE TITLE
images

### ISSUE THREAD

**Issue by leonard3333** [rust-lang/mdBook#1606]
I feel stupid asking this, but cannot find anything whatsoever in the user guide. Where is the Library located (where I assume images are placed), and how do I code reference to this image when I edit a page, eg Chapter 2:

some text bla bla bla

image

some more text bla bla bla

**Comment by ehuss** [comment]
I don't know what you mean by "Library".  Images can be placed in the `src` directory with all the other source files.  You can then link to it as with `![alt text](image.jpg)`. The link will be relative to wherever the page is.

**Comment by leonard3333** [comment]
Thank you. To be fair, I searched the guide for "images", ".png" etc etc and found nothing. I also couldn't find anything elsewhere online. Don't get me wrong, mdbook looks very, very, very good; There just seems to be a few "blind spots" in the documentation (especially for idiots like me where are not good at line coding.)

**Comment by leonard3333** [comment]
Can you be more specific about how to format this. I have THREE files in src: Chapter_1, SUMMARY, and coconut chicken curry.jpg

This is the text for Chapter_1:

`It was the best of times, it was the worst of times.

![testing](coconut chicken curry.jpg)

Have a nice day.`

The image doesn't show when I test on localhost, I just get the above as text. (I've also tried putting the image ref text in the SUMMARY.) This is what I mean by it would be helpful if the documentation showed an example of how to place images within the book. Honestly, there is nothing.

**Comment by ehuss** [comment]
The part on the right is a relative URL.  URLs can't have spaces in them, so it needs to be encoded somehow.  Usually you can replace the spaces with `%20`.

There are quite a few guides out there for how to write markdown, or if you want the full details you can see the spec at https://spec.commonmark.org/.

The documentation could always be better, though I think it is unlikely we would want to replicate a markdown guide.  It could definitely provide some links to learning Markdown, and I think it could better explain how static files are handled and where to put them.

**Comment by leonard3333** [comment]
Thank you. I'll read everything I can on markdown. I should be able to figure it out now.

**Comment by winternet-studio** [comment]
I don't see how #1609 actually solved this?! I still can't find anything about it in the documentation...

**Comment by ehuss** [comment]
@winternet-studio Ah, that PR took care of one part: the guide now has a [markdown section](https://rust-lang.github.io/mdBook/#markdown) which provides some links to tutorials and the specification, which should provide some assistance for how to write image tags.

However, It does look like information on including and linking to static files isn't covered. I opened #1708 as a request for that.
