### ISSUE TITLE
About image/figure's caption text

### ISSUE THREAD

**Issue by tsagaanbar** [rust-lang/mdBook#1608]
Hello! I've been using mdBook to build some static pages and everthing goes fine. However, I've been thinking about showing image's alternative text below the image, no matter the image is available or not. 

| code | currently | expected |
| :---: | :---: | :---: |
| `![A dog is running](./running-dog.png)` |![A dog is running](./running-dog.png)| ![A dog is running](./running-dog.png) <br>*A dog is running.*|

I know that some user may spare the trouble of thinking up the alternative text, so showing the text forcely might make things even worse. So, I'd like to know if mdBook could make this an optional choice, or if there is already an option. Or should I achieve this by using a custom CSS file?

Thanks a lot!

**Comment by CoelacanthusHex** [comment]
It is called caption.
Maybe you want to generate HTML like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption

**Comment by tsagaanbar** [comment]
@CoelacanthusHex Thanks for hleping me remembering the word "caption" and learning the HTML tag of `<figcaption>`. 😂 It came out that I didn't know there's a HTML tag of `<figcaption>`, and somehow confused the concept of alternative text and caption. 

It seems like Markdown dosen't have native support for figure caption, but can be achieved by methods provided on the website: https://thesynack.com/posts/markdown-captions/.

However, I had just tried using raw HTML code, and mdBook doesn't seem to handle this situation (by rendering figure and its caption differently). I'd really appreciate it if mdBook can handle this in its built-in CSS files in the future, if convenient. ❤️

**Comment by tsagaanbar** [comment]
After doing some research, I found in fact there *is* no need for mdBook's developer to make any effort on making caption text more pretty. It should be the site editor's responsibility. 

As for my case, where I want the alt text to be shown under the figure as a caption, should be achieved by some 3rd-party Markdown preprocessor, by wrapping the image and its caption (copied from alt text) together in a `<figure>` tag. Certainly, the task of writing caption is also on the site editor themself, too. 

Sorry for bringing so much trouble!
