### ISSUE TITLE
Hidden lines from file code snippet are rendered

### ISSUE THREAD

**Issue by qinsoon** [rust-lang/mdBook#1619]
This seems to be introduced in the recent release 0.4.11. Code snippets are rendered with the hidden lines.
```rust
#![allow(unused)]
fn main() {

}
```

Also the examples in https://rust-lang.github.io/mdBook/format/mdbook.html seem to be broken as well. The examples for 'Hiding code lines' and 'Including a file but initially hiding all except specified lines' seem to include the lines that are supposed to be hidden.

**Comment by ehuss** [comment]
Apologies, I have published 0.4.12 to resolve the regression.
