### ISSUE TITLE
CommonMark backslash escapes for lists are ignored

### ISSUE THREAD

**Issue by twelho** [rust-lang/mdBook#1620]
According to the [docs](https://rust-lang.github.io/mdBook/#markdown) mdBook adheres to the CommonMark specification. CommonMark supports escaping functional characters using [backslash escapes](https://spec.commonmark.org/0.30/#backslash-escapes), which apply to the list syntax as demonstrated in [example 14](https://spec.commonmark.org/0.30/#example-14):
```
1\. not a  
1\. list
```

Based on this here's a test input:
```
Regular text.

1. this is
1. a list

1\. this is  
1\. not a list

2\. reverse  
1\. order
```

The [CommonMark dingus](https://spec.commonmark.org/dingus/) (as recommended in the [docs](https://rust-lang.github.io/mdBook/#markdown)) handles this correctly (two spaces are used to force a newline after non-list entries):

![image](https://user-images.githubusercontent.com/38858901/127870536-dbe70f1b-c9fd-4f79-a1fb-e9f9137ea68f.png)

But attempting to write the same into a page document causes mdBook `v0.4.11` to ignore the escapes altogether and parse the whole thing as one loose list (escapes are also ignored if they don't directly follow a valid list):

![image](https://user-images.githubusercontent.com/38858901/127870357-1f050cb0-58a8-4c2a-af18-1d1d758180ba.png)

HTML generated by dingus:
```html
<p>Regular text.</p>
<ol>
<li>this is</li>
<li>a list</li>
</ol>
<p>1. this is<br />
1. not a list</p>
<p>2. reverse<br />
1. order</p>
```

HTML generated by mdBook:
```html
<p>Regular text.</p>
<ol>
<li>
<p>this is</p>
</li>
<li>
<p>a list</p>
</li>
<li>
<p>this is</p>
</li>
<li>
<p>not a list</p>
</li>
<li>
<p>reverse</p>
</li>
<li>
<p>order</p>
</li>
</ol>
```

I have not checked if this backslash escape ignoring behavior applies to the other cases presented in [example 14](https://spec.commonmark.org/0.30/#example-14). I can also file an issue against the [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark) parser used by mdBook if requested.

**Comment by ehuss** [comment]
Hm, I copied and pasted your example, and got the following output:

<img width="125" alt="image" src="https://user-images.githubusercontent.com/43198/127876291-c89f6bbc-b6d9-431e-ab4e-5bc4e784779c.png">

Are you sure your editor did not delete the trailing whitespace?

**Comment by twelho** [comment]
Figured it out, we're using the [mdbook-toc](https://github.com/badboy/mdbook-toc) preprocessor, which when enabled causes this issue (even if no table of contents is to be rendered). I presume that it "unescapes" the input (removes the backslashes), as I can match the erroneous output if I do that by hand. If I remove that specific preprocessor everything renders as it's supposed to, so no error in mdBook. Sorry to bother you, should have checked reproducibility without preprocessors first! Will move discussion over to mdbook-toc now.
