### ISSUE TITLE
serve/watch with --open blocks change watcher

### ISSUE THREAD

**Issue by johannst** [rust-lang/mdBook#1639]
In case the `watch` feature is enabled and we  run one of the following commands
```bash
mdbook serve --open
mdbook watch --open
```
listening for file changes is blocked until the browser is closed.

Should we open the browser in a separate thread and start listening for changes immediately?

See PR (#1638) for example.

**Comment by johannst** [comment]
As discussed in PR (#1638) we can move to [`opener`](https://lib.rs/crates/opener), which opens in background by default without waiting for the child process to finish.

I just took another look in [`open`](https://lib.rs/crates/open) and saw that there is also [`that_in_background`](https://github.com/Byron/open-rs/blob/main/src/lib.rs#L121-L124).

Using `that_in_background` we would need to take care of joining the thread handle.

I can create a new PR, any preference on staying with `open` or switching to `opener`?

**Comment by ehuss** [comment]
I would probably lean towards using `opener`.  That is what we use in Cargo, so I am more familiar with it from there.

**Comment by johannst** [comment]
Created new PR (#1656), switching to `opener`.
