### ISSUE TITLE
Warn about 404 links

### ISSUE THREAD

**Issue by Volker-Weissmann** [rust-lang/mdBook#1648]
If you do`[desc](path/to/nonexisting.html)`, you obviously get a 404 link. I think running `mdbook` should either error out or at least print a warning so that it's caught in testing/CI/CD.

For example, I just found some 404 links in the lalrpop book.

**Comment by ehuss** [comment]
[`mdbook-linkcheck`](https://github.com/Michael-F-Bryan/mdbook-linkcheck) is the common solution for adding link checking.  Otherwise, I think this is mostly a duplicate of #431, so closing in favor of that.
