### ISSUE TITLE
Support parsing Markdown inside HTML

### ISSUE THREAD

**Issue by arctic-hen7** [rust-lang/mdBook#1653]
I want to add collapsible accordions to my book, like so:

<details>
<summary>Accordion</summary>

### Heading
Example text.

</details>

This can be done with the following code in Markdown:

```markdown
<details>
<summary>Accordion</summary>

### Heading
Example text.

</details>
```

However, if I do this in mdBook, the accordion doesn't appear, but it does work if I only use HTML elements inside the `<details></details>` block. This leads me to believe that mdBook, or it's underlying Markdown parser, doesn't support parsing Markdown within raw HTML. Is there a way to do this currently with a particular metadata tag? Otherwise, would it be possible to add this as a feature?

**Comment by ehuss** [comment]
Thanks for the report!  It seems to be working for me:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/43198/133948180-3693ed1f-5846-46d9-a492-409dbbd0a9b2.png">

Which version of mdbook are you using?  Can you include a screenshot of what is happening?

**Comment by arctic-hen7** [comment]
Interesting, I can get it to work if I add a newline after the `<summary>`, but otherwise it renders thus:

```
### Heading Example text. 
```

I'm on v0.4.10.

**Comment by arctic-hen7** [comment]
And that would appear to also be the same behavior on GitHub, so this is a non-issue! For anyone else having this problem, newlines after `<summary>` matter!

**Comment by arctic-hen7** [comment]
Sorry for the dud issue!

**Comment by ehuss** [comment]
Ah, yea, markdown can be finicky in some cases.  This is part of the spec for [html blocks](https://spec.commonmark.org/0.30/#html-blocks).  A `<details>` tag starts an HTML block in which no markdown is processed.  However, a blank line ends the block, so then everything afterwards gets processed.
