### ISSUE TITLE
[Question] Is it possible to have inter-document links listed inside the sidebar?

### ISSUE THREAD

**Issue by mainrs** [rust-lang/mdBook#1654]
To give an example:

The book I'm writing contains a section called `Data Types`. I'd like to have all the different data types inside the file `data-types.md` where each data type uses a new header (`##` for example). In the sidebar I'd now like to have all those `##` headers listed below the `Data Types` header. 

I know that I can achieve this by splitting the `data-types.md` file into separate files, one for each data type. 

However, this removes the ability to simply "scroll down" the `Data Types` chapter, since it has been split up. 

I hope my explanation was understandable.

**Comment by ehuss** [comment]
No, that is not supported, see #167.

**Comment by mainrs** [comment]
Ah, sorry. I did an issue search but it looks like I haven't used the right keywords! I'll close this one.
