### ISSUE TITLE
Mdbook create single chapter as book

### ISSUE THREAD

**Issue by MinSiThu** [rust-lang/mdBook#1664]
I want to export each single md chapter as pdf.
But mdbook build export a complete book.

**Comment by ellcs** [comment]
Hello MinSiThu, i did not find an option in `mdBook` which allows exporting to PDFs at all. Did you mean the epub?

**Comment by ehuss** [comment]
I'm going to close as this is unlikely to be a feature we would add.  Thanks for the suggestion, though!
