### ISSUE TITLE
Content can overlap open menu in mobile Safari

### ISSUE THREAD

**Issue by vwkd** [rust-lang/mdBook#1667]
Opening the menu in mobile Safari allows the main content to be scrolled around. It seems the overflow is not being hidden. I didn't test on other mobile browsers.

https://user-images.githubusercontent.com/33468089/140620139-56415c2e-e25d-4eea-94a8-ca2b287606cd.mp4

Safari on iOS 15.0.1 

Reference: https://github.com/rust-lang/book/issues/2905

**Comment by ehuss** [comment]
This should now be fixed via #1994 in 0.4.26.
