### ISSUE TITLE
Is it possible to use spoiler markdown syntax?

### ISSUE THREAD

**Issue by hrishim** [rust-lang/mdBook#1694]
Some markdown formats allow text to be hidden (blacked out) until clicked. Is there a way to do that in msBook? I read the user guide and did not see an obvious way. Using ">!"  does not work.

**Comment by ehuss** [comment]
The markdown parser mdbook uses tries to keep very close to the standard markdown syntax, with only minimal extensions. For this, I think you'll need to use HTML or implement a preprocessor.

**Comment by hrishim** [comment]
Hi 

Thanks for responding. I asked the same question on the Rust Discord server and got the response below. The method described worked for me.

---
mdbook says it uses CommonMark, which has a details tag you can use for spoiler-like behaviour
<details>
  <summary>Spoiler warning</summary>
 
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
   
</details>

I think this will work
Sources:
https://rust-lang.github.io/mdBook/
https://spec.commonmark.org/0.30/
https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287
---

**Comment by ehuss** [comment]
Sounds good, closing as this seems to be resolved.
