### ISSUE TITLE
git-repository-url links should ideally point to a specific file

### ISSUE THREAD

**Issue by matklad** [rust-lang/mdBook#1695]
![image](https://user-images.githubusercontent.com/1711539/143570404-c6a415f1-937a-4b28-aa1c-8f1bc429b792.png)

Would be nice if this pointed to https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/build-scripts.md directly

**Comment by ehuss** [comment]
The `output.html.edit-url-template` setting provides a separate icon that can link to an individual page. Does that fit your needs?  An example can be found in the [guide](https://rust-lang.github.io/mdBook/format/configuration/renderers.html) in the upper-right corner.

**Comment by matklad** [comment]
Yeah, that's exactly what I am asking for, thanks. https://github.com/rust-lang/cargo/pull/10124 if we want to enable that for Cargo.
