### ISSUE TITLE
website visits

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/mdBook#1697]
I would like to consult, have plug-ins can get website visits?

**Comment by ehuss** [comment]
Sorry, I don't understand the question.  Can you elaborate?

**Comment by joshrotenberg** [comment]
I could be wrong but I'm guessing @silence-coding is looking for ways to track visits to a deployed book. Most likely you'll want to include some kind of tracking stuff via javascript which I imagine you can integrate into a [theme](https://rust-lang.github.io/mdBook/format/theme/index.html).

**Comment by silence-coding** [comment]
@joshrotenberg Yes, I'd like to ask whether there is a theme that implements this function.

**Comment by silence-coding** [comment]
@ehuss I want to be able to collect PV(Page View) metrics for deployed books

**Comment by ehuss** [comment]
Ah, in that case you'll need to get some service which provides that.  [Google Analytics](https://marketingplatform.google.com/about/analytics/) is a free option. After signing up, there is a small JavaScript tracking code you can add.   In your book, just create a file `theme/head.hbs` with the contents of the script.  Note that I don't think it will work with a local server, it will only work on a public website.

I'm going to close as this isn't a specific issue with mdbook.
