### ISSUE TITLE
How to add custom css and js ?

### ISSUE THREAD

**Issue by nurmohammed840** [rust-lang/mdBook#1700]
I read docs, and find out that there is `additional-css` and `additional-js` for custom css and js.
```
[output.html]
additional-css = ["https://cdnjs.cloudflare.com/ajax/libs/...]
additional-js = ["https://cdnjs.cloudflare.com/ajax/libs/...",]
```
Does it support url link? It give me this error:

```
[ERROR] (mdbook::utils): Error: Rendering failed
[ERROR] (mdbook::utils):    Caused By: Unable to copy across additional CSS and JS
[ERROR] (mdbook::utils):    Caused By: Unable to create E:\projects\docs\book\https://cdnjs.cloudflare.com/ajax/libs/...
[ERROR] (mdbook::utils):    Caused By: The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

**Comment by ehuss** [comment]
The `additional` fields are only for local files.

If you want to include remote scripts, I might suggest adding a `theme/head.hbs` file with the corresponding `<script>` and `<link>` tags.

**Comment by nurmohammed840** [comment]
How to include `theme/head.hbs` file ?  via `SUMMARY.md` ?

**Comment by ehuss** [comment]
Just create a file relative to the root of the book called `theme/head.hbs`, there isn't anything else that needs to be done. There is more information at https://rust-lang.github.io/mdBook/format/theme/index.html.

**Comment by nurmohammed840** [comment]
Thanks!
