### ISSUE TITLE
[suggestion] Update the rust edition to 2021

### ISSUE THREAD

**Issue by stupidodie** [rust-lang/mdBook#1722]
Since rust edition 2021 is stable, consider change the edition to 2021.

**Comment by ehuss** [comment]
That would require increasing the minimum supported rust version to 1.56.  Can you say why it would be good to update it? I'm not aware of anything particularly noteworthy in 2021 that I think mdbook would use right away.

**Comment by stupidodie** [comment]
Yes, you are right. Just curious why the 2021 edition has not been updated in time... :)
