### ISSUE TITLE
Error in MathJax render

### ISSUE THREAD

**Issue by Yang-Xijie** [rust-lang/mdBook#1733]
```
设 \\(A \boldsymbol x=\boldsymbol b\\) 有一个解 \\(\boldsymbol x^*\\), 则 \\(A \boldsymbol x=\boldsymbol b\\) 的解集为 \\(\boldsymbol x^*+N(A)\\)
```

renders as

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/57952362/150869279-e2eac71b-8b26-4da4-8152-2e213a189d8c.png">

It seems that two `*` in different `\\(` `\\)` pair are recognized as italic ...

**Comment by ehuss** [comment]
I think you need to ensure that there is a space after the open parenthesis (and before the closing one).

```
设 \\( A \boldsymbol x=\boldsymbol b \\) 有一个解 \\( \boldsymbol x^* \\), 则 \\( A \boldsymbol x=\boldsymbol b \\) 的解集为 \\( \boldsymbol x^*+N (A) \\)
```

**Comment by Yang-Xijie** [comment]
Adding a space to each `*` will solve the problem.
