### ISSUE TITLE
Fix sidebar layout on mobile screens

### ISSUE THREAD

**Issue by supfiger** [rust-lang/mdBook#1734]
## Steps to repro:
* Watch the video https://monosnap.com/file/6NcwSNtDnBfYjTV34EbPWe1xc1psha

## Expected behavior:
* Elements don't overlap each other

## Environment:
* device: iPhone X
* OS: IOS 15+
* browser: Safari

**Comment by ehuss** [comment]
Screenshot just to capture from the remote site.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/43198/171324024-c5f25878-c6cc-459a-a972-37a273292bdc.png">

**Comment by ehuss** [comment]
This should now be fixed via #1994 in 0.4.26.
