### ISSUE TITLE
Weird GitLab issue

### ISSUE THREAD

**Issue by GogoFC** [rust-lang/mdBook#1737]
I edit the SUMMARY.md on GitLab, pipeline runs, an entry get's added but no corresponding .md file in /src
I do git pull from my VPS and the file is there.
The first time I added an entry to SUMMARY a file was created.
Was it supposed to be created? I run `mdbook build` on the VPS and then push the changes to GitLab to create the files

```bash
image: rust:1.55.0

before_script:
  - wget -qO- https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xvz -C /usr/local/bin
  - chmod 0755 /usr/local/bin/mdbook
    
# the 'pages' job will build your site and deploy if on main
pages:
  stage: deploy
  script:
    - ls -lath
    - mdbook build $([ "$CI_COMMIT_BRANCH" = "main" ] && echo "-d public") # build to public path on main
  artifacts:
    paths:
      - public
#      - book
#    expire_in: 1 day
```

```bash
Running with gitlab-runner 14.7.0~beta.58.gfa48f33b (fa48f33b)
  on green-2.shared.runners-manager.gitlab.com/default ns46NMmJ
Resolving secrets
00:00
Preparing the "docker+machine" executor
Using Docker executor with image rust ...
Pulling docker image rust ...
Using docker image sha256:269d9943b0d310e1ab49a55e14752596567a74daa37270c6217abfc33f48f7f5 for rust with digest rust@sha256:e4979d36d5d30838126ea5ef05eb59c4c25ede7f064985e676feb21402d0661b ...
Preparing environment
00:03
Running on runner-ns46nmmj-project-33266499-concurrent-0 via runner-ns46nmmj-shared-1643581925-4138088a...
Getting source from Git repository
00:02
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 20...
Initialized empty Git repository in /builds/GogoFC/lightmeter-control-center-docs/.git/
Created fresh repository.
Checking out b5bcacde as main...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:02
Using docker image sha256:269d9943b0d310e1ab49a55e14752596567a74daa37270c6217abfc33f48f7f5 for rust with digest rust@sha256:e4979d36d5d30838126ea5ef05eb59c4c25ede7f064985e676feb21402d0661b ...
$ wget -qO- https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xvz -C /usr/local/bin
mdbook
$ chmod 0755 /usr/local/bin/mdbook
$ ls -lath
total 28K
drwxrwxrwx 6 root root 4.0K Jan 30 22:33 .git
drwxrwxrwx 3 root root 4.0K Jan 30 22:33 src
drwxrwxrwx 5 root root 4.0K Jan 30 22:33 .
drwxrwxrwx 6 root root 4.0K Jan 30 22:33 book
-rw-rw-rw- 1 root root  512 Jan 30 22:33 .gitlab-ci.yml
-rw-rw-rw- 1 root root  440 Jan 30 22:33 book.toml
drwxrwxrwx 4 root root 4.0K Jan 30 22:33 ..
$ mdbook build $([ "$CI_COMMIT_BRANCH" = "main" ] && echo "-d public")
2022-01-30 22:33:54 [INFO] (mdbook::book): Book building has started
2022-01-30 22:33:54 [INFO] (mdbook::book): Running the html backend
Uploading artifacts for successful job
00:02
Uploading artifacts...
public: found 86 matching files and directories    
Uploading artifacts as "archive" to coordinator... 201 Created  id=2032600394 responseStatus=201 Created token=Azbf94Nk
Cleaning up project directory and file based variables
00:01
Job succeeded
```

**Comment by ehuss** [comment]
Sorry, I don't know what you are asking here.  If you add an entry to SUMMARY.md, mdbook will automatically generate that file if it doesn't already exist.  Normally that is done while you are writing the book, and are expected to check those files into source control.  Is that what you are referring to?

**Comment by GogoFC** [comment]
Yes, it doesn't do that on GitLab. 
It doesn't work as it does on a regular server. Is it supposed to? Does it have permissions to write to the main repo? 
mdBook works just fine on server.

**Comment by ehuss** [comment]
Can you show or demonstrate the files not being created?  The logs you posted above just show running `mdbook build` but doesn't really illustrate which files are not being created.

And, FWIW, those auto-generated files are usually just empty placeholders.  Those aren't really intended for CI/CD, but more for development on your local system when you add a new chapter.

**Comment by GogoFC** [comment]
So how do I show that which doesn't exist :) 
OK so I guess I can just post a link here and that's how I can show it :)
I'm new at GitLab, I actually just edit the files via text editor usually.
I was wondering when people use GitLab to create documentation do they have to create the empty placeholder file themselves, because the entry does get created on the rendered page just not the corresponding .md file
So here's the link https://gogofc.gitlab.io/lightmeter-control-center-docs/a.html 
If you click on the top right to edit this file on GitLab it will say it doesn't exist, but the html page is there.
On the server both html and md files get created, and then I don't have to manually create a file and edit it.

**Comment by ehuss** [comment]
Ah, I see.  The CI would need to be able to `git add`, `git commit`, and `git push` the new files.  I don't know if GitLab has the permissions to do that.  That is a pretty unusual thing to do, but if you really want to do it, you can research how to commit from the pipeline.  Personally I would just manually create the files.

I'm going to close, as this seems to be more of an issue with using GitLab.  I don't have much time to help out, but you may be able to use the gitlab forum for help on adding new files from a pipeline.

**Comment by GogoFC** [comment]
Yeah man I use this to write my [notes](https://irondesign.dev/intro.html), it's been pretty sick so far, very clean and builds fast.  Thanks.
