### ISSUE TITLE
export pre-processed markdown

### ISSUE THREAD

**Issue by danieleades** [rust-lang/mdBook#1739]
apologies if this has been mentioned before.

It would be handy to have a flag to export (or simply skip deletion of) pre-processed markdown files.

my use case- I'm using mdbook to write documentation/reports and heavily using the 'include' feature of mdbook to create summaries of specific topics without repeating the content. For example, say I had a number of separate documents each representing a report for a day of the week, then i add a separate document which uses 'include' to collate a particular subheading across multiple days into a single summary.

that all works fine, but I'd like to be able to share this as raw markdown for colleagues that are happy working with markdown, but not interested in using mdbook.

i'm assuming (perhaps incorrectly) that the markdown directory is pre-processed as an intermediate step before converting to HTML. it's that pre-processed markdown that i'm after.

I also use a `plantuml` plugin. Would be great to be able to share properly pre-processed embedded plantuml images in the same way.

**Comment by ehuss** [comment]
You can use the [Markdown renderer](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#markdown-renderer) to get the processed markdown.

**Comment by danieleades** [comment]
> You can use the [Markdown renderer](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#markdown-renderer) to get the processed markdown.

that gets me out of trouble! cheers.

i was hoping for a command-line arg, rather than having to modify the config file. Generally I want both outputs, so that would leave me having to switch back and forth manually.

Still, that's not a massive headache. Thanks for the assist.

**Comment by ehuss** [comment]
All book settings can be set with an environment variable.  The command `MDBOOK_OUTPUT__MARKDOWN={} mdbook build` will turn on the markdown renderer.
