### ISSUE TITLE
Links break logical sentences/paragraphs when using VoiceOver on Mac when traversing into the textual main body.

### ISSUE THREAD

**Issue by CinchBlue** [rust-lang/mdBook#1740]
I wanted to to use VoiceOver (the free a11y screenreader + navigation tool for accessibility on Mac OS X) to read out the Features page in The Cargo Book: https://doc.rust-lang.org/cargo/reference/features.html

You can try the following with Mac OS X 12.1 (Monterrey):

- Select the page + tab for the link above.
- Press Esc.
- Cmd + F5 (Start VoiceOver)
- VO + Right 6 times (Navigate to the main body of text.)
- VO + Shift + Down (Instead of remaining on the main body of text, you instead navigate into the text.)
- VO + Right/Left (You'll see that the text seems to be partitioned by the presence of links when they exist.)

You'll notice that the way the screen-reader will halt when it reaches certain links too if you let it read. It will look something like this, with the red box being the text that was selected (it doesn't look exactly like this):

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/844699/152607306-823dd65a-f961-4e98-8ea8-3e4f9c7bfd25.png">

I'm still very new to VoiceOver so I'm not sure whether this is intended behavior but from an outsider's perspective, it seems non-ideal. I'm willing to look into the issue if someone is interested.

**Comment by ehuss** [comment]
I think that's just how VoiceOver works.  See for example https://phabricator.wikimedia.org/T126922 and https://stackoverflow.com/questions/55814416/screen-reader-stops-reading-paragraph-when-it-reaches-anchor-tag.

It gives the user an opportunity to follow the link or not. It seems awkward to me, but I do not use a screen reader. This might be something to bring up with Apple.

**Comment by ehuss** [comment]
Closing as I do not think there is anything we can do to fix this.  If there is some solution out there, feel free to reopen.
