### ISSUE TITLE
dioxus-desktop compile error: no argument named mime

### ISSUE THREAD

**Issue by tchua0927** [rust-lang/mdBook#1742]
I am currently going through the getting started page and I am currently getting a compile error:

Compiling dioxus-desktop v0.1.6
error: there is no argument named `mime`
   --> C:\Users\troic\.cargo\registry\src\github.com-1ecc6299db9ec823\dioxus-desktop-0.1.6\src\lib.rs:247:49
    |
247 | ...                   let meta = format!("{mime}");
    |                                           ^^^^^^

error: could not compile `dioxus-desktop` due to previous error

**Comment by ehuss** [comment]
I think if you install with rust 1.58, it should work.
If you ran `cargo install mdbook`, then an alternative is to use `cargo install --locked mdbook`

**Comment by ehuss** [comment]
Closing per the recommendations above.
