### ISSUE TITLE
Feature request: move navigation arrows to the center of the page sides

### ISSUE THREAD

**Issue by laoshaw** [rust-lang/mdBook#1747]
This is what gitbooks and other static sites do, and it's of great convenience. With this I do not need to scroll down all the way to the bottom for next/prev pages then.

A demo screenshot attached:

![x](https://user-images.githubusercontent.com/18351761/153783113-1bb9a61c-6e11-4a29-9151-0dcc8f2453ec.png)

**Comment by ehuss** [comment]
Sorry, it is not clear to me what this is asking.  On a sufficiently wide screen, then arrows are vertically centered as in the picture.  If you are referring to a narrow screen, then it is intentionally placed at the bottom to avoid using a large amount of valuable screen real estate.  Can you clarify more what this is asking?  What platform and browser are you using? What is your window size?

**Comment by laoshaw** [comment]
Sorry I did not widen my screen size enough to see those arrows, now it works. I am using chrome on a PC monitor but I narrowed the screen too much that hides the side-arrow. Thanks!
