### ISSUE TITLE
Unicode chars are not italicized

### ISSUE THREAD

**Issue by sephiron99** [rust-lang/mdBook#1751]
I wrote like this. This is from https://github.com/sephiron99/async-book-ko/blob/ko_KR/ko/src/04_pinning/01_chapter.md#%EC%A0%95%EB%A6%AC
![image](https://user-images.githubusercontent.com/12970474/154816263-d659ff91-97c7-48e2-882c-b5e5f4723b0c.png)

But, It is compiled like this by mdbook.
![image](https://user-images.githubusercontent.com/12970474/154816358-71937246-472a-4f59-b162-697c0e86f8e7.png)

Is this a bug?

**Comment by ehuss** [comment]
The underscores need to be separated with spaces as in `this is an _emphasized text_ example`.

I don't read Korean, so I don't know if the word breaks make sense, but adding spaces makes it italics:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/43198/154848556-3b963ad2-6eec-45c4-8adb-124909776098.png">

**Comment by sephiron99** [comment]
Thanks for your answer. Spaces in those places break Korean grammer a littel, but It's minor.
