### ISSUE TITLE
Theme directory not being read

### ISSUE THREAD

**Issue by parazyd** [rust-lang/mdBook#1756]
Hi. I'm trying to customize the Ayu theme, add additional fonts, and update the favicon on my mdbook instance.
However, it seems that the files aren't copied in place, and instead mdbook just spawns the default fonts and CSS files.

My directory structure looks like this:
```
├── book.toml
├── src
└── theme
    ├── book.js
    ├── css
    │   ├── chrome.css
    │   ├── general.css
    │   ├── print.css
    │   └── variables.css
    ├── favicon.png
    ├── favicon.svg
    ├── highlight.css
    ├── highlight.js
    └── index.hbs
```

I made this with `mdbook init --theme`, and then subsequently I'm trying to change files inside.
Not even changing the favicon results in a change, but rather the output directory contains stock files, let alone
changing something in the CSS files.

My `book.toml`:

```
[book]
authors = ["P"]
language = "en"
multilingual = false
src = "src"
title = "Book"

[output.html]
theme = "ayu"
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.katex]

[preprocessor.katex]
```

I'm building the book with `mdbook build` and viewing the HTML files with Firefox.
Does anyone know what I'm doing wrong here?

**Comment by parazyd** [comment]
Also with strace, I see no calls that even look for the `theme` directory.

**Comment by ehuss** [comment]
`theme = "ayu"` specifies the folder where the theme is located. This overrides the default of "theme".  There probably should be an error or warning if it doesn't exist.

**Comment by clarkfw** [comment]
I've made a PR #1791, which gives user an error message when theme directory does not exists.

It's been 2 months since this issue was opened. How I wish we could have more active contributors
