### ISSUE TITLE
modify print output

### ISSUE THREAD

**Issue by Tealk** [rust-lang/mdBook#1757]
Hello,

is it possible to modify the print output? e.g. add a background or similar?

**Comment by ehuss** [comment]
Yea, you should be able to add CSS that applies only when printing using an `@media print` CSS query. Alternatively you can override the `print.css` file in the theme.  Does that answer your question?

**Comment by Tealk** [comment]
I haven't tested it yet but that sounds like what I'm looking for.

**Comment by Tealk** [comment]
My idea would have been a background like this one, let's see how I can best implement that.
https://codepen.io/AgnusDei/pen/NWPbOxL
