### ISSUE TITLE
I want to output first HTML and then execute my extension

### ISSUE THREAD

**Issue by shijunti19** [rust-lang/mdBook#1769]
The generated JS cannot be overwritten in the extension

**Comment by alechp** [comment]
Agreed. Was just looking for this; seems there's a lifecycle discussion here:
https://github.com/rust-lang/mdBook/issues/163#issue-170890662

In our case we need a `<base...` tag rendered in the HTML head. While it's a simple fix we have to manually insert `<base...` on every subsequent build

**Comment by shijunti19** [comment]
I have modified the code myself. I can modify HTML at will and analyze and search in Chinese
