### ISSUE TITLE
Is it possible to embed a small wasm app in an mdbook?

### ISSUE THREAD

**Issue by max-sixty** [rust-lang/mdBook#1780]
Firstly thanks for building such a wonderful library!

I'm hoping to include a small wasm app in an mdbook. I have some rust experience but very little web experience.

I'm including this snippet in an md page, which was build by `trunk`:
```
<script type="module">import init from './dist/index-aa17a837077bf43a.js';init('./dist/index-aa17a837077bf43a_bg.wasm');</script></body></html>
```

This almost works — initially the normal `md` page appears, and then a moment later the wasm app appears. But the wasm app fills the whole screen — there's no sidebar remaining.

Possibly this question could be reduced to "embed an HTML page within an mdbook", and the wasm aspect is tangential? If so, has anyone succeeded at this? It seems related to https://github.com/rust-lang/mdBook/issues/773.

Thank you

**Comment by max-sixty** [comment]
Thanks @ehuss . I'll close this. 

It sounds like this was accurate:
> Possibly this question could be reduced to "embed an HTML page within an mdbook", and the wasm aspect is tangential? If so, has anyone succeeded at this?

...and possible even more reduced to "embed an HTML page within another". Though if anyone has done this successfully in an mdbook, I'd be grateful to learn how.

**Comment by max-sixty** [comment]
If any future travelers have a similar need — I eventually got this working. I'm sure there are more elegant approaches! https://lang.prql.builders/editor.html
https://github.com/max-sixty/prql/pull/312, 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/5635139/161875696-e69261de-42f6-4cc5-b09a-5ad6a33822ec.png">

**Comment by Marcono1234** [comment]
> I eventually got this working. I'm sure there are more elegant approaches! https://lang.prql.builders/editor.html
> https://github.com/max-sixty/prql/pull/312,

For future reference, it seems the correct PR link is now https://github.com/PRQL/prql/pull/312
