### ISSUE TITLE
Chapters aren't appearing while deployed.

### ISSUE THREAD

**Issue by xzntrc** [rust-lang/mdBook#1786]
I've deployed my book using gitlab-cmi following a guide I found, for some reason chapters aren't visible on the deployed site https://eccentrici.gitlab.io/templeos/. Although it's included in the summary:

```
# Summary

# Getting Started
- [Introduction](./introduction.md)
- [Installation](./installation.md)
- [Diving In](./lookingintotempleos.md)
- [License](./license.md)
``` 
I'm not sure why this is happening as when I build it locally it works just fine? My source code is here: https://gitlab.com/eccentrici/templeos

**Comment by clarkfw** [comment]
I'm looking into this issue,  but the urls you provided returns 404. It seem to be a private repo, is it?
