### ISSUE TITLE
How to resize the image?

### ISSUE THREAD

**Issue by ChenZhongPu** [rust-lang/mdBook#1790]
I didn't find any clue about how to resize the image in `mdbook`. Any idea?

**Comment by schungx** [comment]
I don't think you can under MarkDown...

You may have to put in `<img>` tags directly.

**Comment by ChenZhongPu** [comment]
> I don't think you can under MarkDown...
> 
> You may have to put in `<img>` tags directly.

But some website/document generating tools (e.g., [docsify](https://docsify.js.org)) supports such feture/extension.
