### ISSUE TITLE
Mismatch in documentation

### ISSUE THREAD

**Issue by glatavento** [rust-lang/mdBook#1804]
At the beginning of [this page](https://rust-lang.github.io/mdBook/format/configuration/general.html), the field used to represent author is `book.author` (requires a string)

https://github.com/rust-lang/mdBook/blob/bf258eeb9b245b9c329e147dd1884307c5ef7644/guide/src/format/configuration/general.md?plain=1#L7-L14

but then changed to `book.authors` (requires a list):

https://github.com/rust-lang/mdBook/blob/bf258eeb9b245b9c329e147dd1884307c5ef7644/guide/src/format/configuration/general.md?plain=1#L37-L43

and it should be the latter one, according to the config parser

https://github.com/rust-lang/mdBook/blob/981b79b3b39d80b61da2a10622d6cf611a23686a/src/config.rs#L403-L420

(please point out if I have misunderstood)

**Comment by ehuss** [comment]
Oops, good catch! Yea, the docs should be `authors` plural.

**Comment by glatavento** [comment]
Or maybe it would be easier to modify the parser...? There are already many books using the singular form `author`, see

https://github.com/rust-lang/book/blob/d9415b7cbfcb4b24062683f429bd0ff535396362/book.toml#L1-L3

https://github.com/rust-lang/rustc-dev-guide/blob/0c02acdb6f48f03907a02ea8e537c3272b4fde9f/book.toml#L1-L3

https://github.com/rust-lang/rust-by-example/blob/e9f93cfcf410bc092c9107b8a41a82f144c761f2/book.toml#L1-L4

**Comment by ehuss** [comment]
Oh my!  I wonder how that division happened.  I would prefer to keep only a single field, and `authors` seems reasonable to me. Mdbook doesn't even use the field for anything, so it's probably not too important.  If #1595 is addressed, then that should handle any warnings for unknown fields.

**Comment by kg4zow** [comment]
Maybe leave them both in there, with `author` allowing a single string and `authors` taking an array of strings? And if both _happen_ to be present, add the `author` value to the `authors` array before returning from the parser function?

... wow, it looks like you did the merge _while_ I was typing this. 😁
