### ISSUE TITLE
Feature Suggestion: Keyboard Keys Rendering

### ISSUE THREAD

**Issue by epomatti** [rust-lang/mdBook#1813]
It would be nice to have keyboards key markup like this:

<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Space</kbd>

**Comment by ISSOtm** [comment]
Can/should we use the same style entirely, or should we come up with something similar?

**Comment by epomatti** [comment]
hmmm what is "same style"?

**Comment by ISSOtm** [comment]
The style applied to `<kbd>` elements on GitHub. I'm not sure if we would be able to copy their CSS; if not, I'm no good designer, so I would have trouble coming up with something similar but different.

**Comment by epomatti** [comment]
Maintainability comes first then, simpler would be a better choice.

**Comment by ISSOtm** [comment]
My question isn't so much about maintainability as it is about copyright.

**Comment by brettchalupa** [comment]
I'd like to take on this issue if it's still available.
