### ISSUE TITLE
Cannot Uninstall mdbook from Ubuntu

### ISSUE THREAD

**Issue by mala27** [rust-lang/mdBook#1822]
Ran via Ubuntu Terminal: "sudo apt-get --purge remove mdbook" and ran many other variations of remove cmd, failed uninstall
i) mdbook is still in my .cargo/bin folder
ii) It's constantly looking for the correct package name, spent hours on internet looking for "exact" package name and tried dpkg list too
iii) Apologies but not willing to spend anymore time on this, just need exact cmd for Ubuntu Terminal to uninstall this package
Thank you very much.

**Comment by anzome** [comment]
.cargo folder managed by the cargo. It seems that you probably have used `$ cargo install mdbook` to install package and so you have to use `$ cargo uninstall mdbook` to remove it.

**Comment by mala27** [comment]
Thank you very much Alexander, much appreciated.
