### ISSUE TITLE
How to host a site using mdbook on github pages?

### ISSUE THREAD

**Issue by user0159** [rust-lang/mdBook#1823]
Can someone explain how [this](https://github.com/troyerta/recipes) site is created that uses mdbook and hosted on github pages? It does not have clear instructions on how to host a similar website, or to replicate that website itself. My [website](https://user0159.github.io/recipes/) does not show up like it shows [here](https://troyerta.github.io/recipes/), even though the two repositories are same. I do have Rust, Python, and other dependencies installed on my computer as suggested by the original repository [here](https://github.com/troyerta/recipes/blob/master/docs/intro_advanced.md). I searched online to find some instructions that could help me create [this](https://github.com/troyerta/recipes) site using mdbook and github pages, and came across [this](https://github.com/peaceiris/actions-mdbook), but I don't really understand it well.

**Comment by joshrotenberg** [comment]
Have a look at the [wiki](https://github.com/rust-lang/mdBook/wiki/Automated-Deployment) and this [issue](https://github.com/rust-lang/mdBook/issues/1803).

**Comment by user0159** [comment]
@joshrotenberg I tried to use your suggested [example](https://github.com/joshrotenberg/wtd-bayarea-mdbook) in the issue you cited (as seen [here](https://github.com/user0159/mdbook-main-test)), but the github page only displays the contents in the [README.md](https://github.com/user0159/mdbook-main-test#readme) file. I think I am missing something that I do not understand, and the guidance in those issues is not sufficient to figure out myself.

**Comment by ISSOtm** [comment]
Did you [set the publishing source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) to the `gh-pages` branch in the options?

**Comment by user0159** [comment]
@ISSOtm thanks for your comment. After @kg4zow comment in [this](https://github.com/rust-lang/mdBook/issues/1803) issue,  I understood that I would need to select `gh-pages` as the branch in settings, but I have been getting various errors for some commands in VS Code (Windows). I will try WSL in Windows to see if I can get rid of those errors.
