### ISSUE TITLE
Text Column Width Configuration

### ISSUE THREAD

**Issue by Dgarc359** [rust-lang/mdBook#1847]
Hello!

First of all, I just want to say that this is a great project! I'm super excited to follow this repository as it grows.

I've searched through the open and closed issues to see if this question had been asked before, apologies if I missed it!

I'm trying to have some control over the width of the main text column that is rendered by mdBook. On mobile, the padding around the column is already great.

I have found that there is a lot of unused space on wider screens, ex: 
![image](https://user-images.githubusercontent.com/87497958/178078364-0b9eb4d4-fe7f-4f52-99b2-cef9763c8cd6.png)

and I was wondering if the recommended approach for something like this is to leverage the `additional-css` renderer option? Otherwise, is there a simpler way to configure this?

Appreciate the pointers!

**Comment by ehuss** [comment]
Yea, I would recommend using CSS to change the styling as you desire. There isn't a specific setting for the width. Something like this should work:

```css
:root {
    --content-max-width: 500px;
}
```

There are several css files and such that you can override. https://rust-lang.github.io/mdBook/format/theme/index.html discusses the files, and `mdbook init --theme` will give you a copy of the defaults.
