### ISSUE TITLE
Identify (and optionally delete) unreachable pages?

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/mdBook#1880]
When working on an outline I'll frequently add/remove/rename pages in `SUMMARY.md` and because `mdbook` automatically creates the files for those pages when `SUMMARY.md` changes (which is great!) I end up with a bunch of no-longer-used `.md` files in my `src/` directory. Figuring out which ones are used and which ones aren't and can be deleted is a bit of a pain. Would be nice if `mdbook` could help out a bit here.

**Comment by ehuss** [comment]
Thanks for the suggestion!  I think this is more or less the same as #1720, so closing in favor of that.
