### ISSUE TITLE
html attributes with single quotes produce invalid output

### ISSUE THREAD

**Issue by milahu** [rust-lang/mdBook#1898]
html single quotes are converted to doublequotes
but doublequotes in the attribute value are not escaped

input.md

```md
# test

<div title='hello "world" again'>
  hover me
</div>
```

output.html

```html
<h1>test</h1>

<div title="hello "world" again">
  hover me
</div>
```

expected: either/or

* keep single quotes in attributes, and hope that the input is valid html
* convert attributes to double quotes, and escape `"` to `&quot;` in attribute values

**Comment by ehuss** [comment]
Can you say more about why it appears to be converted for you?  Pasting your example, then HTML looks like:

```
> rg "hover me" book/chapter_1.html
147:  hover me
~/Temp/z47> rg -C4 "hover me" book/chapter_1.html
143-                <div id="content" class="content">
144-                    <main>
145-                        <h1 id="test"><a class="header" href="#test">test</a></h1>
146-<div title='hello "world" again'>
147:  hover me
148-</div>
149-
150-                    </main>
151-
```

If you are looking at the source via the DOM inspector, then I believe that is just the way it is displayed. The attribute should still have the value with the double quotes:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/43198/192385132-256dbd1b-0b83-47ef-b8f3-f675bf534b66.png">

Here it shows the DOM value is the string as expected.
