### ISSUE TITLE
Custom favicon

### ISSUE THREAD

**Issue by curryrasul** [rust-lang/mdBook#1903]
Hi. Is it possible to set a custom favicon for a build?

**Comment by brettchalupa** [comment]
@curryrasul you can override the default favicon placing a `favicon.png` and/or `favicon.svg` file in the `theme` dir in the root of your mdBook project (next to your `src` dir, not within it).

[Here's more info in the docs about overriding one-off default theme files.](https://rust-lang.github.io/mdBook/format/theme/index.html)

**Comment by curryrasul** [comment]
Thanks for the answer!
