### ISSUE TITLE
Add support for darwin arm64

### ISSUE THREAD

**Issue by camilamacedo86** [rust-lang/mdBook#1905]
It seems that it still without support for mac os x, arm64

**Comment by ehuss** [comment]
Yea, `x86_64-apple-darwin` should work. macOS has a thing called Rosetta 2 that will allow running x86_64 programs.

I'm going to close as I would prefer to keep the number of binary distributions to a minimum, and `aarch64-apple-darwin` is currently a tier 2 platform which carries some risk. Once `aarch64-apple-darwin` is available as tier 1, I think it would be worth considering adding it at that time.

In the meantime, if there are problems with running the x86_64 binaries, one can also build from source ([instructions](https://rust-lang.github.io/mdBook/guide/installation.html#build-from-source-using-rust)).
