### ISSUE TITLE
mdbook-katex can not fix bug #24

### ISSUE THREAD

**Issue by ayoubelmhamdi** [rust-lang/mdBook#1910]
this bug [#24](https://github.com/lzanini/mdbook-katex/issues/24) not fixed from a while

**Comment by ehuss** [comment]
I'm sorry you're running into trouble with mdbook-katex. That is a third-party project, so I think it is best to follow up with them at https://github.com/lzanini/mdbook-katex.

**Comment by SichangHe** [comment]
Should be fixed with https://github.com/SichangHe/mdbook-katex2/commit/7551d898d49e7f639ab85bf3512c8f6466314d69.

**Comment by ayoubelmhamdi** [comment]
@SichangHe thinks

**Comment by SichangHe** [comment]
@ayoubelmhamdi, please use the original `mdbook-katex` instead of `mdbook-katex2` now. I accepted their invitation to be a collaborator and I am now maintaining the original repo.

**Comment by ayoubelmhamdi** [comment]
@SichangHe: I saw your commit, in `the original repo. please, don't forget to launch a new release that contains the new commit.
