### ISSUE TITLE
Top menu bar did not show `edit` icon

### ISSUE THREAD

**Issue by astraw99** [rust-lang/mdBook#1914]
Tried to set `book.toml` like this:
```
[output.html]
...
git-repository-url = "https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs"
edit-url-template = "https://github.com/kubernetes-sigs/kubebuilder/edit/master/docs/book/{path}"
```
Then `mdbook serve` locally, but only showed the git-repo icon, no edit icon.

**Comment by ehuss** [comment]
It looks like your book has overridden the `theme/index.hbs` file. That is where the icons are defined. You'll need to update that file with the latest changes. The latest version can be found here: https://github.com/rust-lang/mdBook/blob/master/src/theme/index.hbs

**Comment by astraw99** [comment]
Added the git-edit code block, then edit icon shows.
```
{{#if git_repository_edit_url}}
    <a href="{{git_repository_edit_url}}" title="Suggest an edit" aria-label="Suggest an edit">
        <i id="git-edit-button" class="fa fa-edit"></i>
    </a>
{{/if}}
```
But when click the edit icon, it just redirect to page `https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src`, not the corresponding page that can edit directly.
Any config I miss?

**Comment by ehuss** [comment]
I don't offhand know. Can you post your edits to a branch I can check out?  Can you also include which version of mdbook you are using?

**Comment by astraw99** [comment]
> I don't offhand know. Can you post your edits to a branch I can check out? Can you also include which version of mdbook you are using?

You can check at this branch: https://github.com/astraw99/kubebuilder/blob/ftr-add-faq/docs/book/book.toml
```
mdbook --version
mdbook v0.4.21
```

**Comment by ehuss** [comment]
It looks like your plugins are out-of-date. Specifically [here](https://github.com/astraw99/kubebuilder/blob/5d59e40a7b7a2f35476a7b657973f63ad734bdb8/docs/book/utils/plugin/input.go#L99-L106) needs to be kept in sync with the definition with [`Chapter`](https://github.com/rust-lang/mdBook/blob/3a24f10d7cdb01a0da36f2f34db013b0d9c71317/src/book/book.rs#L154-L170). I didn't test it (I couldn't get your plugins to work), but I would assume the missing `source_path` would be a good start.

**Comment by astraw99** [comment]
OK, I will check it. Thanks.
BTW, please help to check in by branch, why the `print` feature did not work?

**Comment by ehuss** [comment]
Sorry, I don't have the time to debug an external plugin. I'm going to close as this seems to be an issue with external tooling.
