### ISSUE TITLE
MathJax inside HTML `details` tag

### ISSUE THREAD

**Issue by your-diary** [rust-lang/mdBook#1926]
Is is possible to render MathJax inside `<details>` tag?

**Input**

```html
<details>
<summary>Proof</summary>
\\[
    {}_{N - 1} C _{M - 1}
\\]
</details>
```

**Output**

```
▼ Proof
\\[ {}_{N - 1} C _{M - 1} \\]
```

(The equation is output as it is. Not rendered...)

---

By the way, I use `mdbook` for mathematical writing (rather than LaTeX), and I sometimes want to embed a long proof inside a `<details>` tag.

**Comment by SichangHe** [comment]
I tried this with the [`mdbook-katex`](https://github.com/lzanini/mdbook-katex) preprocessor and it is rendered. I recommend you to give it a shot.

Note that you currently have to use `$` and `$$` instead, though.

Steven Hé (Sīchàng)

**Comment by your-diary** [comment]
@SichangHe 
I just tested it today and it worked like a charm.
Thank you for your suggestion and I'm sorry for my very late reply.

**Comment by your-diary** [comment]
Finally found a solution without the need of `mdbook-katex`.

Just insert an empty line after the closing `</summary> tag.
```markdown
<details>
<summary>Proof</summary>

\\[
    {}_{N - 1} C _{M - 1}
\\]
</details>
```

ref: #2145
