### ISSUE TITLE
Print page on firefox includes blank column when sidebar is visible

### ISSUE THREAD

**Issue by ehuss** [rust-lang/mdBook#1932]
On firefox, if the sidebar is visible, generating the print page will incorrectly include visible whitespace on the left side.

Actual:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/43198/203123662-09b46eef-24ae-44bb-8638-5aac395d2822.png">

Expected:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/43198/203123710-345666ee-727c-4c98-9d93-48b66eb67deb.png">

This doesn't seem to affect Chrome or Safari

Tested with Firefox 107.0.

**Comment by ehayes2000** [comment]
I am experiencing the same issue using google chrome Version 119.0.6045.124 (Official Build) (64-bit). I am served my book with `mdbook serve` . I have 20 chapters in my book all of which are empty except the first chapter.
