### ISSUE TITLE
What is this Array for?

### ISSUE THREAD

**Issue by katopz** [rust-lang/mdBook#1945]
https://github.com/rust-lang/mdBook/blob/master/src/theme/book.js#L169-L172
```js
        Array 👈🤔
        code_nodes
            .filter(function (node) {return !node.classList.contains("editable"); })
            .forEach(function (block) { hljs.highlightBlock(block); });
```

**Comment by schungx** [comment]
Probably an artifact... Since it probably gets ignored in JavaScript

**Comment by Dylan-DPC** [comment]
This is a mistake when code was moved from the previous module, and JS ignores it so it didn't cause any issue. Thanks for noticing it
