### ISSUE TITLE
Precompiled `mdbook` gnu executable requires newer glibc version (v0.4.23)

### ISSUE THREAD

**Issue by jontze** [rust-lang/mdBook#1954]
With the latest `v0.4.23` release the precompiled [mdbook-v0.4.23-x86_64-unknown-linux-gnu.tar.gz](https://github.com/rust-lang/mdBook/releases/download/v0.4.23/mdbook-v0.4.23-x86_64-unknown-linux-gnu.tar.gz) binary doesn't run on the github runner of `ubuntu-20.04` anymore. As it fails with the following error:

```sh
mdbook --version
mdbook: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by mdbook)
```
Further workflow logs her: https://github.com/jontze/action-mdbook/actions/runs/3702275493/jobs/6272375311. It still works on the latest ubuntu-22.04 runner.

I observed this behavior especially in context of the current ongoing github `ubuntu-latest` runner rollout: https://github.com/actions/runner-images/issues/6399 . So `ubuntu-latest` will slowly switch from `20.04` to `22.04`.

With the latest mdBook release, the build of the precompiled binaries are now executed on `ubuntu-22.04`.

Other projects where affected by this as well and their selected solution was to build the precompiled binaries on `ubuntu-20.04` instead of `ubuntu-latest`.

https://github.com/rust-lang/mdBook/blob/eb77083d23c768521a0024c6317b8d295198a501/.github/workflows/deploy.yml#L21-L22

For example the `nushell` project had the same issue:
- https://github.com/nushell/nushell/issues/7282
- https://github.com/nushell/nushell/pull/7290

So we might choose this way as well for the mdBook builds. However, I'm not quite sure if this is the way to go, or if there are better solutions to resolve this.

**Comment by ehuss** [comment]
Thanks for the heads up!  I posted #1955 to fix it.  In the mean time, I might suggest using the musl binary which is currently statically linked and should exhibit the same problem.
