### ISSUE TITLE
mdbook test ignores the directory argument when the -L flag is passed before it

### ISSUE THREAD

**Issue by cvybhu** [rust-lang/mdBook#1958]
Our `mdbook` workflow in https://github.com/scylladb/scylla-rust-driver suddenly started failing.

The failing command was:
```bash
mdbook test -L target/debug/deps docs
```

It started complaining that it can't find `SUMMARY.md` in the directory `<repository>/src`
The book is in the directory `<repository>/docs` and that's why we pass the `docs` argument to guide it to the right place.

Swapping the order of the arguments fixes the problem:
```bash
mdbook test docs -L target/debug/deps
```

This looks like a bug in argument parsing.

Refs: https://github.com/scylladb/scylla-rust-driver/pull/616

**Comment by ehuss** [comment]
Thanks for the heads up! I have posted #1959 with a fix and will publish a new release.
