### ISSUE TITLE
Support copying only shell commands, not `$` in `shell` code blocks

### ISSUE THREAD

**Issue by mgeisler** [rust-lang/mdBook#1963]
Hi there,

For Comprehensive Rust, it would be nice if we could let users copy the _commands_ from `shell` code blocks _without_ also copying the leading `$` sign.

So a `shell` code block like

```shell
$ apt install cargo
```

should let me copy the `apt install cargo` part alone. The dollar sign (the prompt) is still nice since it indicates that this is a command (it is syntax highlighted nicely).

This was brought up in https://github.com/google/comprehensive-rust/pull/25 and https://github.com/google/comprehensive-rust/pull/29.

**Comment by ehuss** [comment]
Thanks for the report!  I think this is essentially the same as #864 so closing as a duplicate.

**Comment by mgeisler** [comment]
Thanks!
