### ISSUE TITLE
Preprocessors cannot modify `SUMMARY.md`

### ISSUE THREAD

**Issue by mgeisler** [rust-lang/mdBook#1979]
Hi there,

As far as I can tell, a preprocessor is not executed on the data in `SUMMARY.md`. If that is true, can be change this somehow?

My usecase for this is to [support translations](https://github.com/google/comprehensive-rust/issues/115) via a mdbook preprocessor. However, if the preprocessor doesn't have access to the outline, it cannot translate it :smile: 

A simple work-around for me is to translate all the Markdown files (including `SUMMARY.md`) manually via an external script. However, it would be nice to have the whole thing integrated with mdbook.

**Comment by ehuss** [comment]
Preprocessors should be able to modify the summary from the `sections` array. IIRC, all the information of the summary (such as the chapter names) are stored within. You won't be able to modify the file as a whole.

**Comment by mgeisler** [comment]
Oh, cool, I'll take a look at that. I was looking at the `BookItem` enum and that only seems to give me the headers between the chapters — not the actual chapters from the sidebar.

**Comment by mgeisler** [comment]
Ah, I got it now! I need to translate the [`name` field in `Chapter`](https://docs.rs/mdbook/latest/mdbook/book/struct.Chapter.html#structfield.name). The updated `name` is used in the sidebar. I _do_ have access to this from a [`BookItem::Chapter`](https://docs.rs/mdbook/latest/mdbook/enum.BookItem.html#variant.Chapter).

Thanks!
