### ISSUE TITLE
Invoking the "katex" renderer even though book.toml specifies "html" renderer

### ISSUE THREAD

**Issue by mschoenebeck** [rust-lang/mdBook#1984]
My book.toml:

```
[book]
authors = ["Matthias Schoenebeck"]
language = "en"
multilingual = false
src = "src"
title = "My Book"

[output.katex]

[preprocessor.katex]
renderers = ["html"]
macros = "macros.txt"
```

Executing mdbook fails because for some reason it invokes 'katex' renderer.
```
$ mdbook build book
2023-01-11 10:28:20 [INFO] (mdbook::book): Book building has started
2023-01-11 10:28:20 [INFO] (mdbook::book): Running the katex backend
2023-01-11 10:28:20 [INFO] (mdbook::renderer): Invoking the "katex" renderer
thread 'main' panicked at 'The katex preprocessor is only compatible with the html renderer!', src/lib.rs:176:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-01-11 10:28:20 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2023-01-11 10:28:20 [ERROR] (mdbook::utils): Error: Rendering failed
2023-01-11 10:28:20 [ERROR] (mdbook::utils): 	Caused By: The "katex" renderer failed
```

What am I missing?

**Comment by ehuss** [comment]
I think you also need to enable the HTML renderer by adding:

```toml
[output.html]
```

If you specify one `output`, that disables the built-in html renderer.

mdbook probably should have a check if `preprocessor.{name}.renderers` specifies a renderer that is not defined and print a message.

**Comment by mschoenebeck** [comment]
Thanks! That solved my issue. Should definitely be added to the mdbook-katex readme file.

btw I just realized this is not even the mdbook-katex repo. Anyway, thanks again!

**Comment by mschoenebeck** [comment]
Thanks! That solved my issue. Should definitely be added to the mdbook-katex readme file.

btw I just realized this is not even the mdbook-katex repo. Anyway, thanks again!
