### ISSUE TITLE
Generating a toc when printing the whole book

### ISSUE THREAD

**Issue by Hoffenbar** [rust-lang/mdBook#1997]
### Problem

Printing a big book as pdf leaves the reader with no possibility to navigate through the document, or am I wrong?

### Proposed Solution

Output a toc in the pdf.

**Comment by Hoffenbar** [comment]
Furthemore, I noticed that Inrra-page-TOCs generated with `mdbook-toc` don't work in a PDF created with the print button in the upper right corner.

**Comment by ehuss** [comment]
Thanks for the report! I believe this is a duplicate of #1817, so closing in favor of that.
