### ISSUE TITLE
Footnotes show as code when indented

### ISSUE THREAD

**Issue by max-sixty** [rust-lang/mdBook#2003]
### Problem

When prettier formats a footnote, it adds indentation to the footnote text:

```
[^1]:
    Our approach is very consistent with
    **[@matklad](https://github.com/matklad)**'s advice, in his excellent blog
    post [How to Test](https://matklad.github.io//2021/05/31/how-to-test.html).
```

On GitHub, this shows as a normal footnote. 

But on mdbook, this shows as:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/5635139/215943285-c3462d9d-fd81-4603-b736-338185b06725.png">

### Version

```text
mdbook v0.4.25
```

**Comment by ehuss** [comment]
Thanks, I believe this is already tracked in https://github.com/raphlinus/pulldown-cmark/issues/623.

**Comment by max-sixty** [comment]
Ah thanks, I'll close this then
