### ISSUE TITLE
ANCHOR display on *.md

### ISSUE THREAD

**Issue by mingkeYao** [rust-lang/mdBook#2004]
### Problem

like the picture below. The /* ANCHOR xxx */ and  /* ANCHOR_END xxx */ display on the html

![image](https://user-images.githubusercontent.com/33944326/216013286-2c835bf1-1b0a-4d70-8039-75d1b8abd19b.png)

### Version

```text
v0.4.25
```

**Comment by mingkeYao** [comment]
ok, I can prepare an example.
First, I build 2 md files, named a_book.md and b_book.md.
The catalog like this
![image](https://user-images.githubusercontent.com/33944326/216242761-526ecc18-d92f-4cca-bfef-e6568fc7a0ee.png)

In **a_book.md**, the content like this
```
# A-book

## a start

// ANCHOR: pack

* line1
* line2
* line3

// ANCHOR_END: pack


## a end
```
In **b_book.md**, the content like this
```
# B-book

## b start


{{#include a_book.md:pack}}



## b end
```

Last, on the pages,  the 'pack' in a_book has been imported to b_book.  
![image](https://user-images.githubusercontent.com/33944326/216243764-0156c24f-cb9e-4626-a816-8f35889d14ab.png)

But, the "ANCHOR" marker not disappear in a_book
![image](https://user-images.githubusercontent.com/33944326/216243765-bec14c46-7b1b-4bfb-ae8f-61c039d70db8.png)

**Comment by ehuss** [comment]
You'll need to use HTML style comments, like:

```
<!-- ANCHOR: pack -->
...
<!-- ANCHOR END: pack -->
```

Or, put the content in a separate file (not linked from SUMMARY.md) and include the entire contents in both A and B.

**Comment by mingkeYao** [comment]
ok, thanks,  "HTML style comments" works.

**Comment by Kevinizevbigie** [comment]
incase anybody else reads this, its `ANCHOR_END` not `ANCHOR END`.

Note the underscore.
