### ISSUE TITLE
Documentation: Add to documentation how to disable print feature

### ISSUE THREAD

**Issue by jrmiller82** [rust-lang/mdBook#2005]
### Problem

The documentation is silent about how to disable the print feature. 

### Proposed Solution

Include some information that shows the configuration setting in #1169, namely:

```
[output.html.print]
enable = false
```

Is how you disable print.

**Comment by ehuss** [comment]
I believe the section at https://rust-lang.github.io/mdBook/format/configuration/renderers.html#outputhtmlprint explains this option.  Can you say more about what appears to be missing?

**Comment by jrmiller82** [comment]
I must have missed it in the documentation. My apologies.
