### ISSUE TITLE
Sticky header bar isn't sticky any more

### ISSUE THREAD

**Issue by tavianator** [rust-lang/mdBook#2028]
### Problem

I updated from mdBook 0.4.21 to 0.4.27 and it seems to have broken the sticky header bar.

### Steps

1. Go to https://tavianator.com/2022/ray_box_boundary.html
2. Scroll down a page or two
3. Scroll back up a few inches

When I do this, the header bar remains off screen.  I can only see it when I scroll all the way back up to the top of the page.

### Notes

I tried both Firefox and Chrome on Arch LInux.

### Version

```text
mdbook v0.4.27
```

**Comment by ehuss** [comment]
Oh my, thanks for the report!  It looks like it regressed from #1994. @Skwodo do you think you could take a look?
