### ISSUE TITLE
Poll option for file watching

### ISSUE THREAD

**Issue by digitalcora** [rust-lang/mdBook#2035]
### Problem

Some file systems one might reasonably want to use with mdBook don't support change events ([mounted Windows file systems under WSL2](https://github.com/microsoft/WSL/issues/4739) are rather infamous for this). If your book is on such a file system, the `watch` and `serve` commands cannot detect changes, making them not very useful.

### Proposed Solution

The `watch` and `serve` commands could have an option (e.g. `--poll`) to detect changes by periodically polling the file system.

### Implementation

I'm not at all familiar with Rust, but it appears the `notify` package used by mdBook already has a [`PollWatcher`](https://docs.rs/notify/latest/notify/poll/struct.PollWatcher.html) intended for just this situation. So, mdBook would not have to implement this logic from scratch.

### Prior Art

Polling is supported by some popular static site generators; I'm familiar with it from [Hugo](https://gohugo.io/commands/hugo_server/#options), but Jekyll apparently has it as well. Hugo requires the user to specify a poll interval, but suggests 700ms as a default. In my experience this strikes a decent balance between responsiveness and resource usage for small sites, but those with more files might warrant a higher value.

### Workarounds

The command-line tool [`fswatch`](https://github.com/emcrisostomo/fswatch) supports polling, with a default interval of 1s. I've gotten it working with mdBook like so (then opening the output files using `file://` in the browser):

```
fswatch -m poll_monitor -o -r src | xargs -I{} mdbook build
```

This is not quite as ergonomic as a built-in option would be — it deletes and recreates everything in the output directory on every change, which takes a second or two, and if you refresh before it's ready you can get a 404 or missing CSS/fonts.

**Comment by KFearsoff** [comment]
@rustbot label +C-bug +Command-serve +Command-watch +S-Duplicate

See https://github.com/rust-lang/mdBook/issues/2102#issuecomment-1810982299
