### ISSUE TITLE
Navigation overlaps with the content in mobile browsers (at least ios safari)

### ISSUE THREAD

**Issue by dlitsman** [rust-lang/mdBook#2051]
### Problem

When navigation is open, sometimes sliding content instead of closing navigation adds text on top of it

### Steps

1. Open navigation
2. Use touch and slide motion on main content

Expected:
Navigation is closed

Actual:
Navigation and content are overlapping each other

https://user-images.githubusercontent.com/963490/226202910-64528f83-fe5a-48b3-b008-0e3150df49ec.mp4

### Version

```text
Tested on prod rust docs
iOS 16.0.2
```

**Comment by ehuss** [comment]
Thanks for the report and the screen cap!  I believe this is fixed via #1994.  Can you verify that it works on https://rust-lang.github.io/mdBook/?

**Comment by dlitsman** [comment]
Yes, you a right! I just verified and it is fixed on this version!

**Comment by ehuss** [comment]
Thanks for checking.  I have posted an update so that the Rust documentation gets updated.
