### ISSUE TITLE
Upgrade to highlight.js v11

### ISSUE THREAD

**Issue by jonaprieto** [rust-lang/mdBook#2054]
The current book.js uses an outdated version (10.7) of Highlight.js.
Are there any plans to support the new version? It seems that simply changing the source code for the new one breaks a couple of things.

- https://highlightjs.readthedocs.io/en/latest/upgrade-11.html

**Comment by ehuss** [comment]
Unfortunately it will require significant work to update.  This is already tracked in #1622, so closing as a duplicate of that.
