### ISSUE TITLE
`themePopup.querySelector(...) is null` when deployed to GitHub Pages

### ISSUE THREAD

**Issue by mrjones2014** [rust-lang/mdBook#2090]
### Question

I'm sure it's something I've configured wrong, but I'm getting this JS error, and the theme selector and collapse sidebar buttons do not work when deployed to GitHub Pages, but it all works locally if I do `mdbook serve docs` or `mdbook build docs && npx serve docs`.

Here's my GitHub Actions workflow to deploy it: https://github.com/mrjones2014/dotfiles/blob/master/.github/workflows/github-pages.yml

And I'm using a custom domain: https://mjones.network

### Version

GitHub Actions is using `'latest'`, locally I have `v0.4.28` installed via Nix/`home-manager`.

**Comment by ehuss** [comment]
Hm, I don't seem to be having any issues with the linked site. You may want to make sure your local cache is cleared, or try a different browser?

**Comment by mrjones2014** [comment]
Interesting, it works when I check from mobile (Safari) but when I check from my computer on Firefox, Librewolf, or Brave, I get the issue 🤔

**Comment by mrjones2014** [comment]
The other weird thing is, here's the stack trace:

```
Uncaught TypeError: themePopup.querySelector(...) is null
    updateThemeSelected https://mjones.network/book.js:308
    set_theme https://mjones.network/book.js:366
    themes https://mjones.network/book.js:372
    <anonymous> https://mjones.network/book.js:441
[book.js:308:20](https://mjones.network/book.js)
```

If I follow it into the code, you'll find the line `var themePopup = document.getElementById('theme-list');`

If I run that `querySelector` manually in the browser console, it does return the right element 🤔

**Comment by mrjones2014** [comment]
Something really weird is going on..... If I set a breakpoint in the browser devtools here, where the error originates:

```
function updateThemeSelected() {
        themePopup.querySelectorAll('.theme-selected').forEach(function (el) {
            el.classList.remove('theme-selected');
        });
        themePopup.querySelector("button#" + get_theme()).classList.add('theme-selected'); // this line
    }
```

And when it pauses, go to the console and evaluate `themePopup.querySelector` it outputs `function querySelector()`....

**Comment by mrjones2014** [comment]
I manually added some logging statements to the js file and got this output:

```
	console.log(themePopup);
	console.log(themePopup.querySelector);
	console.log(get_theme());
	console.log(themePopup.querySelector("button#" + get_theme()));

// outputs:

<ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
function querySelector()
dark
null
```

I am not sure why this would fail on desktop and not mobile, but I do notice that on mobile, there is no theme called "dark". I think this is due to my config, will test it out and close the issue if that's the case.

**Comment by mrjones2014** [comment]
Yeah, that fixes it. I had `default-theme` set to `"dark"` in `book.toml`, which I think was not correct. It's supposed to be the name of a specific theme.
