### ISSUE TITLE
Add support for orgmode 

### ISSUE THREAD

**Issue by OrionRandD** [rust-lang/mdBook#2112]
### Problem

Could you add support for orgmode as well?
orgmode from Emacs is superb and has lots of features that surpass markdown...
And has also org-ref for citations
Thx a lot

### Proposed Solution

This is a tuto about how to use org-ref for an orgmode file
https://invidious.nerdvpn.de/watch?v=2t925KRBbFc

### Notes

Here we have an example of how powerful orgmode is:
https://invidious.nerdvpn.de/watch?v=cRUCiF2MwP4&listen=false

**Comment by ehuss** [comment]
Thanks for the suggestion! I think at this time we won't be directly supporting different input formats. I understand there are formats which are better in many ways than markdown, but a key aspect of markdown is that it is compatible with lots of other tooling, such as GitHub or GitLab rendering, and its broad usage.

Different input formats can be supported by implementing a [preprocessor](https://rust-lang.github.io/mdBook/for_developers/preprocessors.html) which can convert the input to either markdown or html. If you have access to something that supports that, then it should be pretty easy to wire up.
