### ISSUE TITLE
Code blocks with syntax highlighting nested in lists doesn't work

### ISSUE THREAD

**Issue by franksouza183** [rust-lang/mdBook#2115]
### Problem

This works:

```
* Item

        block code

* Item
```

Output: 
![image](https://github.com/rust-lang/mdBook/assets/6532907/e7f10c33-cf76-4730-a3bb-1b29d3a8deed)

With syntax highlighting doesn't:

```
* Item

        ```rust
        block code
        ```

* Item
```

Output: 
![image](https://github.com/rust-lang/mdBook/assets/6532907/0cb82cdd-ccb2-4e63-97f9-428218dd8cd6)

Not this either:

```
* Item

        ```
        block code
        ```

* Item
```

Output: 
![image](https://github.com/rust-lang/mdBook/assets/6532907/f31f543a-ed0c-4485-924d-a708e8928fbc)


### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
0.4.30
```

**Comment by ehuss** [comment]
When indenting content inside a list, you typically want it indented to match the previous item's indentation. So, for example, to include a code block in a list, it would be something like:

``````
* Item

  ```rust
  block code
  ```

* Item
``````

Where it is indented 2 spaces. https://spec.commonmark.org/0.30/#list-items explains the indentation rules.

**Comment by franksouza183** [comment]
> 

Oh, my fault! Thank you for the spec link.
