### ISSUE TITLE
Is it possible to support a gitbook-like hint block?

### ISSUE THREAD

**Issue by Aye10032** [rust-lang/mdBook#2141]
### Question

I'm trying to convert my gitbook books to use mdbook for editing, however due to the fact that I use a lot of the following syntax in my original markdown files:
```
{% hint style='info' %}
Important info: this note needs to be highlighted
{% endhint %}
```
Which is supported by gitbook's plugin-hints. But unfortunately mdbook doesn't support this format, is it possible to support it in the future? Or is there any similar 3rd party plugin?

**Comment by cr0mll** [comment]
Check out [mdbook-admonish](https://github.com/tommilligan/mdbook-admonish). I use it in my own project and it's pretty good.
