### ISSUE TITLE
Markdown inside <details> tag?

### ISSUE THREAD

**Issue by your-diary** [rust-lang/mdBook#2145]
### Question

Is it possible to render Markdown inside `<details>` tag?

```
<details>
<summary>Detailed Log</summary>
```bash
$ cat log.txt

[2023-07-28T09:00:15] INFO ...
(very long text here)
`` `
</details>
```
(The single space inside "`` `" is just for escaping a backtick for GitHub.)

This hack doesn't work well (e.g. no syntax highlight):
```
<details>
<summary>Detailed Log</summary>
<pre>
<code>
$ cat log.txt

[2023-07-28T09:00:15] INFO ...
(very long text here)
</code>
</pre>
</details>
```

**Comment by bgotink** [comment]
You have to leave a blank line between the HTML and the ```` ``` ````. That's due to Markdown, not something specific to mdbook.

````markdown

<details>
<summary>Detailed Log</summary>

```bash
$ cat log.txt

[2023-07-28T09:00:15] INFO ...
(very long text here)
```
</details>

````

FYI: in markdown you can use more backticks to make it possible to write three backticks in a code block, e.g.

Inline code ```` ``` ```` is written as ````` ```` ``` ```` `````

Code block

````markdown
```bash
false
```
````

is written as 

`````markdown
````markdown
```bash
false
```
````
`````

**Comment by your-diary** [comment]
@bgotink You are my hero. Thank you.
