### ISSUE TITLE
Can't display code

### ISSUE THREAD

**Issue by ovo-Tim** [rust-lang/mdBook#2153]
### Question

On FireFox:
![图片](https://github.com/rust-lang/mdBook/assets/116942368/09fed3e0-3300-4e03-b518-b8aedbade12a)

On edge:
![图片](https://github.com/rust-lang/mdBook/assets/116942368/db7372d5-e860-4fbd-b5fa-a67ac99c1010)

### Version

```text
mdbook v0.4.32
```

**Comment by ehuss** [comment]
This looks like the ace editor didn't load. Can you check your browser's console for any errors, or try refreshing?  cc @mgeisler in case this is something specific to your theme.

**Comment by ovo-Tim** [comment]
> Can you check your browser's console for any errors
![图片](https://github.com/rust-lang/mdBook/assets/116942368/70eb6d45-b135-4f0e-8e36-e519f8c9c320)

**Comment by ovo-Tim** [comment]
> Can you check your browser's console for any errors
![图片](https://github.com/rust-lang/mdBook/assets/116942368/70eb6d45-b135-4f0e-8e36-e519f8c9c320)

**Comment by mgeisler** [comment]
Thanks @ehuss for the ping! @ovo-Tim, this issue looks like https://github.com/google/comprehensive-rust/issues/733 — the solution is to enable symlinks in Git on Windows with

```
git config --global core.symlinks true
```

This is (briefly) mentioned in our [README](https://github.com/google/comprehensive-rust/blob/main/README.md?plain=1#L76-L77).

**Comment by ovo-Tim** [comment]
> Thanks @ehuss for the ping! @ovo-Tim, this issue looks like [google/comprehensive-rust#733](https://github.com/google/comprehensive-rust/issues/733) — the solution is to enable symlinks in Git on Windows with
> 
> ```
> git config --global core.symlinks true
> ```
> 
> This is (briefly) mentioned in our [README](https://github.com/google/comprehensive-rust/blob/main/README.md?plain=1#L76-L77).

But I am using arch linux.
```
❯ neofetch
                   -`                    tim@TimTu-Arch 
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Code01 Ver2.0 1 
               `+oooooo:                 Kernel: 6.4.8-arch1-1 
               -+oooooo+:                Uptime: 4 days, 22 mins 
             `/:-:++oooo+:               Packages: 1220 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.16 
           `/++++++++++++++:             Resolution: 2560x1600 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.7 
         ./ooosssso++osssssso+`          WM: kwin 
        .oossssso-````/ossssss+`         Theme: NephriteLight [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], Colloid [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: Hack [SRC] 10 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 6800H with Radeon Graphics (16) @ 3.200GHz 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon 680M 
 `++:.                           `-/+/   Memory: 17725MiB / 30808MiB 
 .`                                 `/

```

It did,'t solve my problem.

**Comment by mgeisler** [comment]
Okay, can you check that `theme/book.js` is symlink pointing to `../third_party/mdbook/book.js`?

It looks like this in my working copy:

```shell
% ls -l theme/book.js
lrwxrwxrwx 1 mgeisler group 29 May  4 11:30 theme/book.js -> ../third_party/mdbook/book.js
```

How did you get hold of the course files? Via a `git clone` or via some other mechanism?

**Comment by ovo-Tim** [comment]
I may know the problem.
I just download the zip file from github.
As far as I know, zip can't support symlink well.
I will have a try after two days.
Thanks you.

**Comment by mgeisler** [comment]
Thanks for explaining @ovo-Tim, you're exactly right: the zip files generated by GitHub don't work since they don't preserve the symlinks we use. I think we should close this issue — it's not a problem with mdbook.
