### ISSUE TITLE
Checkboxes delimited by empty lines are rendered incorrectly.

### ISSUE THREAD

**Issue by your-diary** [rust-lang/mdBook#2180]
### Problem

I have this Markdown:

```markdown
# A

- [ ] apple
- [ ] bear
- [ ] cow

# B

- [ ] apple

- [ ] bear

- [ ] cow
```

GitHub and VSCode (tested with Markdown Preview Enhanced) render it correctly:

![Screenshot 2023-08-31 at 13 33 27](https://github.com/rust-lang/mdBook/assets/58146437/37a565e7-5711-491d-84cf-0af0cb584192)

However, `mdbook` renders it incorrectly:

![Screenshot 2023-08-31 at 13 33 37](https://github.com/rust-lang/mdBook/assets/58146437/28189848-219a-4c62-abfa-f8e8762cceda)

### Notes

By the way, `mdbook` can render lists correctly, meaning empty lines break rendering only for checkboxes:

```markdown
# C

- apple
- bear
- cow

# D

- apple

- bear

- cow
```

![Screenshot 2023-08-31 at 13 35 49](https://github.com/rust-lang/mdBook/assets/58146437/49fdc74b-133c-4ed5-86d7-a71553bc0839)

### Version

```text
mdbook v0.4.34

(No preprocessor is used. CSS and JavaScript are not customized. Fully vanilla `mdbook` is used.)
```

**Comment by ehuss** [comment]
Thanks for the report! This has already been fixed (https://github.com/raphlinus/pulldown-cmark/pull/558), but we are waiting for a new release of the markdown renderer.

**Comment by your-diary** [comment]
@ehuss Thank you!
