### ISSUE TITLE
Is there a way to show the markdown icons after the rendering?

### ISSUE THREAD

**Issue by linc01** [rust-lang/mdBook#2203]
### Question

Hello, 

Is there a way to show icons in the markdown files as it is in the below image:

![iconinmd](https://github.com/rust-lang/mdBook/assets/30107747/a504b748-d3dd-4643-a6bf-9fd3b632a093)

After the rendering: 
![iconinmd2](https://github.com/rust-lang/mdBook/assets/30107747/4a586425-5931-4167-a06e-b4082fa7903b)

Thanks!

### Version

```text
mdbook v0.4.28
```

**Comment by ehuss** [comment]
mdbook comes with FontAwesome version 4.7.0. These can be inserted with code like `<i class="fa fa-folder"></i>`. The icons are documented at https://fontawesome.com/v4/icons/.

If you need other icons, you can customize the theme with a `theme/fonts/` folder with whatever custom icon-based fonts you want, or use images with standard markdown image tags, or even inline SVG.

**Comment by codesplode** [comment]
Ran into the same thing for printable documents with mdbook-pdf and printing. To workaround, I put this in our custom styles:

```css
@media print {
	.fa {
		display: inline-block !important;
	}
}

```

**Comment by linc01** [comment]
> mdbook comes with FontAwesome version 4.7.0. These can be inserted with code like `<i class="fa fa-folder"></i>`. The icons are documented at https://fontawesome.com/v4/icons/.
> 
> If you need other icons, you can customize the theme with a `theme/fonts/` folder with whatever custom icon-based fonts you want, or use images with standard markdown image tags, or even inline SVG.

I put the NerdFonts SymbolsNerdFont-Regular.ttf to the folder you mentioned, but it seems nothing happened to the page. 

Here is the message with `mdbook build`: 
"2023-09-27 06:14:13 [INFO] (mdbook::book): Book building has started
2023-09-27 06:14:13 [INFO] (mdbook::book): Running the html backend"

book.toml:
`[book]
authors = ["l"]
language = "en"
multilingual = false
src = "src"
title = "RUST"

[dependencies]
printpdf = "0.3"

[preprocessor]

[preprocessor.catppuccin]
assets_version = "1.0.0" # DO NOT EDIT: Managed by `mdbook-catppuccin install`

[output]

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-admonish.css"]
copy_fonts = "false"
`

Anything else I need to do? Thanks.

**Comment by ehuss** [comment]
The font needs to be loaded in `fonts/fonts.css`.

**Comment by linc01** [comment]
> The font needs to be loaded in `fonts/fonts.css`.

here is the fonts.css:
/*NerdFonts Symbols*/
@font-face {
  font-family: 'NerdFonts';
  font-style: normal;
  font-weight: normal;
  src: local('SymbolsNerdFont-Regular'),
       url('SymbolsNerdFont-Regular.ttf') format('ttf');
}

`mdbook build`:
2023-09-27 15:45:35 [INFO] (mdbook::book): Book building has started
2023-09-27 15:45:35 [INFO] (mdbook::book): Running the html backend
2023-09-27 15:45:35 [WARN] (mdbook::renderer::html_handlebars::hbs_renderer): output.html.copy_fonts is deprecated.
Set copy_fonts=false and ensure the fonts you want are in the `theme/fonts/` directory.

book.toml:
[book]
authors = ["l"]
language = "en"
multilingual = false
src = "src"
title = "RUST"

[dependencies]
printpdf = "0.3"

[preprocessor]

[preprocessor.catppuccin]
assets_version = "1.0.0" # DO NOT EDIT: Managed by mdbook-catppuccin install

[output]

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-admonish.css"]
copy_fonts = "false"

**Comment by ehuss** [comment]
`mdbook v0.4.28` — This version is quite old. Can you update to the latest version (`0.4.34`)?

**Comment by linc01** [comment]
> `mdbook v0.4.28` — This version is quite old. Can you update to the latest version (`0.4.34`)?

It's v0.4.34 now. The icons seem unchanged.

**Comment by ehuss** [comment]
Can you put together a sample project to reproduce it and upload it as a `.zip` here? Or as a new repo on GitHub? Preferably without the preprocessor. I can't tell from what is posted what might be missing.

**Comment by ehuss** [comment]
Without more information I'm going to close this issue. If you're able to make a minimal reproduction, feel free to reopen.
