### ISSUE TITLE
Sidebar not collapsing

### ISSUE THREAD

**Issue by rsteube** [rust-lang/mdBook#2217]
### Problem

In `v0.4.35` the sidebar isn't collapsable anymore. Works in `v0.4.34`.

### Steps

1. `mdbook serve --open`
2. click on menu icon (burger)

### Version

```text
v0.4.35
```

**Comment by rsteube** [comment]
Linux (Manjaro Sway):
- qutebrowser v3.0.0
- Mozilla Firefox 118.0.1
- Chromium 117.0.5938.149 Arch Linux

Android:
- DuckDuckGo
- Firefox Focus

**Comment by ehuss** [comment]
And just to confirm, this is happening on https://rust-lang.github.io/mdBook/?

**Comment by rsteube** [comment]
> And just to confirm, this is happening on https://rust-lang.github.io/mdBook/?

No, it doesn't. It works there.

**Comment by ehuss** [comment]
Can you share where it doesn't work? Does that book have a custom theme? Has it been updated?

**Comment by rsteube** [comment]
Ah, totally forgot about that.
A fresh initialized mdbook works, and updating the theme files do so as well.

Sorry for the trouble.

**Comment by micahsnyder** [comment]
@ehuss we ran into this issue with the https://github.com/Cisco-Talos/clamav-documentation project documentation.  Mdbook v0.4.34 works correctly, but v0.4.35 the sidebar will not collapse and lays on top of the book text when the browser window is too narrow.  I just pushed a commit to revert to build the docs.clamav.net page with v0.4.34 until we can fix it.

**Comment by rsteube** [comment]
@micahsnyder here's how it was done in catppuccin: https://github.com/catppuccin/mdBook/commit/55e872267de2c63e91659c6be5eac1be4fc34540

**Comment by micahsnyder** [comment]
Thanks @rsteube I just did something similar and it appears to have fixed the issue:
https://github.com/Cisco-Talos/clamav-documentation/commit/47875401b7659ac23e8d0e0aaf264acc127025b6
