### ISSUE TITLE
Are monitoring services available?

### ISSUE THREAD

**Issue by heisen-li** [rust-lang/mdBook#2298]
### Problem

I'm very happy with all aspects of mdbook, but I can't seem to find a monitoring service for traffic? mdbook doesn't seem to support it?

I want to monitor web browsing, and I want more information, including: statistics on the number of visitors, time spent, location information, number of clicks, and other information.

I know some tools can meet part of my needs, such as Google Analytics that I know of, but it would be better if mdbook supported it.

Are there plans to support these features?

### Proposed Solution

Or is there some crate that can implement a monitoring service? Any recommendations? Thanks to all.

**Comment by ehuss** [comment]
I think your best option is to use something like Google Analytics. I don't think mdBook will have any intention of adding support for something like that (indeed, the old google analytics support is being removed). Site tracking requires a server component among other things, and is far outside the scope of what the tool itself provides.

**Comment by heisen-li** [comment]
Ok, thank you so much for your reply @ehuss.
