### ISSUE TITLE
Images cannot be displayed when there is a space in the images' name.

### ISSUE THREAD

**Issue by youkoutaku** [rust-lang/mdBook#2301]
### Problem

Images cannot be displayed when there is a space in the images' name.

Just like that,

.md:
```
![](attachments/Pasted image 20230504182138.png)
```

.html:
```
<p>![](attachments/Pasted image 20230504182138.png)</p>
```

I don't think it's a big problem and hopefully, it can be dealt with easily.

**Comment by asibahi** [comment]
I will try to work on it today.

**Comment by asibahi** [comment]
As far as I can tell this is a markdown parsing issue, which is not done in mdbook directly but is done by the [pulldown_cmark](https://github.com/raphlinus/pulldown-cmark) crate. 

VSCode exhibits the same behaviour 
<img width="1009" alt="image" src="https://github.com/rust-lang/mdBook/assets/17417266/f09d1ae8-97b9-4d6a-bfae-9696ddf0d10e">

**Comment by ehuss** [comment]
Thanks for the report!

Commonmark does not allow spaces in links. They can be included with `%20` or enclosing the link in angle brackets.

```md
![](attachments/Pasted%20image%2020230504182138.png)

![](<attachments/Pasted image 20230504182138.png>)
```
