### ISSUE TITLE
sidebar doesn't close or content invisible

### ISSUE THREAD

**Issue by ssiyad** [rust-lang/mdBook#2314]
### Problem

In rust book, when sidebar is collapsed, the space doesn't go away. When an already collapsed is reopened, its content is not visible. I found https://github.com/rust-lang/mdBook/issues/2217 searching issues, but not sure if its related.

https://github.com/rust-lang/mdBook/assets/28098330/8f082fd1-076c-4293-9010-2e3e07a8dd44

https://github.com/rust-lang/mdBook/assets/28098330/1839493d-d8d0-4fdd-9930-0c26e385f8c9

MacOS 14.2.1
Chrome 121.0.6167.139

**Comment by ehuss** [comment]
Thanks for the report! Can you share which browser you are on? Do you have any extensions? Does it reproduce if the cache is cleared, or running on a separate profile?

**Comment by ssiyad** [comment]
Browser is Chrome (version `121.0.6167.139`). Issue is gone after a hard refresh (cache cleared)

**Comment by Dylan-DPC** [comment]
I assume this is one of those spurious browser cache issues. So closing it. Thanks for the report
