### ISSUE TITLE
Is it possible to remove the next/previous page buttons?

### ISSUE THREAD

**Issue by skycloudd** [rust-lang/mdBook#2329]
### Question

As the title says. I'm using mdBook for a blog and the navigation buttons get in the way sometimes. It would be nice to be able to remove them.

**Comment by ehuss** [comment]
One option is to customize the theme. https://rust-lang.github.io/mdBook/format/theme/index.html contains some information on how that works, in particular you'll need to edit `index.hbs`.

Another option is to set up custom CSS, and use `display: none;` on the appropriate classes.

**Comment by skycloudd** [comment]
Ah, that makes sense. thanks for the help!
