### ISSUE TITLE
Specific ligatures not working

### ISSUE THREAD

**Issue by Ciflire** [rust-lang/mdBook#2335]
### Problem

In [rust-by-practice](https://practice.course.rs/) code block i found that some ligatures of MonoLisa won't render and make the dots in `..=` and `.=` invisible, where it should render like that
![image](https://github.com/rust-lang/mdBook/assets/39668077/edfb373f-4be4-4247-ba12-8f362971a0ca)

### Steps

1. Go on rust by practice
2. Use monolisa font (or maybe some others)
3. write `..=` inside a code block

### Notes

it does work in monolisa playground and typst online editor, so i fugured it might come from here
It does render inside of code block, but not input code block

### Version

```text
Could not figure out from the github repo
```

**Comment by ehuss** [comment]
Thanks for the report! I'm not sure what monalisa is, but the fonts are defined by the book's CSS. In particular, code blocks use "Source Code Pro", which is a different font. If you are overriding the fonts, you will need to make sure they are overridden for all places fonts are defined.

**Comment by ehuss** [comment]
Hm, I don't see anything at https://github.com/sunface/rust-by-practice/tree/master/en that indicates that the font is being overridden, and the fonts are the normal fonts when I open the given link. Are you using a local override?

Regardless, we have noted issues in the past (like #1061) where the ACE editor is sensitive to the font that is used, and the CSS was adjusted to prevent those overrides.

**Comment by Ciflire** [comment]
yeah i'm locally overriding this

**Comment by shenef** [comment]
Have you tried enabling more [font features](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings)?
Took a bit of searching but when you scroll down far enough, the [specimens page](https://www.monolisa.dev/specimen) of MonoLisa lists the font feature needed for each ligature set. For your case it seems to be `SS17`.
