### ISSUE TITLE
Hidelines does not work with multiple languages

### ISSUE THREAD

**Issue by Mouthless-Stoat** [rust-lang/mdBook#2354]
### Problem

`output.html.code.hidelines` does not seem to work with any other language apart from the example language `python` and `rust`. I have try `json`, `gdscript` and none of the language work

### Steps

1. Create a new book
2. In the `book.toml` add:
```toml
[output.html.code.hidelines]
json= "~"
```
3. Edit a chapter and add
~~~md
```json
{
    ~"hello"
}
```
~~~
4. Render the page using `mdbook serve` and see the code block not render with hidden lines.

### Version

```text
mdbook v0.4.37
```

**Comment by ehuss** [comment]
Hm, I'm not able to reproduce with the given example. Can you check if there are any errors in the javascript console? Can you check if the generated HTML code block has `<span class="boring">`?

**Comment by Mouthless-Stoat** [comment]
There no `<span class="boring">` and also no error in the console

**Comment by ehuss** [comment]
The newer versions of highlight.js won't work. There are instructions at https://github.com/rust-lang/mdBook/blob/master/CONTRIBUTING.md#updating-highlightjs for checking out an older version and building it. We're currently on `10.1.1`.
