### ISSUE TITLE
markdown > syntax cannot wrap

### ISSUE THREAD

**Issue by chenxuan520** [rust-lang/mdBook#2367]
### Problem

- markdown > syntax cannot wrap. All the rows squeezed into one row

### Steps

1. Here is an example markdown source file
![图片](https://github.com/rust-lang/mdBook/assets/77540051/c702595f-f73c-4ba1-8029-6f4105f3a7e0)
2. use mdbook to create assets
3. show like this pic
![图片](https://github.com/rust-lang/mdBook/assets/77540051/70324c1d-4a46-4912-8304-91fece2c9e35)

**Comment by ehuss** [comment]
Thanks for the report! This is intentional behavior, as it is part of the commonmark spec.

If you want them to be separate, you can make them separate paragraphs, like:

```
> foo
>
> bar
```

or use manual linebreaks, such as:

```
> foo\
> bar
```
