### ISSUE TITLE
Let all the output html files share the same one sidebar 

### ISSUE THREAD

**Issue by phpmooc** [rust-lang/mdBook#2371]
### Problem

I just modified the `SUMMARY.md` file and do nth else, which means that I just added one new chapter, but the contents of all the other chapters were **NOT modified**. As a result, I found that the contents of all compiled html files were changed. I think it is unreasonable,  and it was confirmed that it was caused by changes of the sidebar content. It seems that the sidebar does not adopt a separate and shared loading method.

Maybe I'm using it incorrectly, please tell me if u know what to do, thanks a lot.

### Proposed Solution

separate the sidebar and let all the output html files share the same one sidebar

**Comment by ehuss** [comment]
The sidebar is embedded in each chapter, so it is static. This is the intended behavior.

**Comment by phpmooc** [comment]
I couldn't understand why the sidebar need to be embedded in each chapter,  is it possible to put it into one separated file to be shared or included by some other chapters with the method like `iframe` or others?

**Comment by ppom0** [comment]
Well, the purpose of static websites is to do all computations at compilation so that websites are fully optimized. An iframe means more HTTP requests.

**Comment by phpmooc** [comment]
> Well, the purpose of static websites is to do all computations at compilation so that websites are fully optimized. An iframe means more HTTP requests.

yeah,  I agree with that `iframe` means more HTTP requests,  and I'm not meaning to have to use `iframe`, we just needs to ensure the shared sidebar be separated and included  before html files are generated. I also don't know about `Rust` lang,  but I think it is possible and easy to make it by some other better similar ways than `iframe` for most of thoses server-side languages,  it can be done at compilation.

**Comment by ppom0** [comment]
Well, embedding another html file is a feature HTML doesn't have.
In this project Rust is not a server-side language, there is no server-side language. So dynamic HTML-including is not an option!

I'd advise read documentation about how HTML works, and then either come back with a more practical request, or more likely close this issue ^^

**Comment by phpmooc** [comment]
> Well, embedding another html file is a feature HTML doesn't have. In this project Rust is not a server-side language, there is no server-side language. So dynamic HTML-including is not an option!
> 
> I'd advise read documentation about how HTML works, and then either come back with a more practical request, or more likely close this issue ^^

It is apparently that u r not understand what I said .  It's essentially have nothing to do with how html works,  bcz we are not just focus on html itself.  Indeed,  html lacks real `include` features support，so many languages like Rust or Java or PHP comes to help it for this, and it is not important whether Rust is server-side lanugage or not.  Similar practices had been conducted by myself with PHP in this regard for a long long time.
