### ISSUE TITLE
0.4.38 release has no assets

### ISSUE THREAD

**Issue by casey** [rust-lang/mdBook#2390]
I just had CI job that installs mdbook fail with a 404 trying to download release binaries for [0.4.38](https://github.com/rust-lang/mdBook/releases/download/v0.4.38/mdbook-v0.4.38-x86_64-apple-darwin.tar.gz), and the [release](https://github.com/rust-lang/mdBook/releases/tag/v0.4.38) indeed has no assets. This was caused by [this action run](https://github.com/rust-lang/mdBook/actions/runs/9119897012) failing, causing the assets not to be published.

**Comment by ehuss** [comment]
Thanks for the report! This was fixed in https://github.com/rust-lang/mdBook/pull/2383, and the assets should be generating with 0.4.40.

**Comment by casey** [comment]
Thanks! For some reason the [CI job is still trying to download 0.4.38](https://github.com/casey/intermodal/actions/runs/9122901740/job/25084456673?pr=537), but that's probably an issue with caching or the action I'm using to download mdbook. Just wanted to mention it here in case anyone else had the same issue.
