### ISSUE TITLE
Is there an option to disable automatic file creation from `SUMMARY.md`?

### ISSUE THREAD

**Issue by Social-Mean** [rust-lang/mdBook#2413]
### Question

When `mdbook serve` or `mdbook watch`, mdbook will automatically create files that do not exist in dirs. It is convenient but sometimes may cause mistakes. For example, sometimes I type the wrong filename and save the `SUMMARY.md`, but mdbook helps me create the file, and I have to delete the file manually.

Is there an option to disable automatic file creation from `SUMMARY.md`? Like `mdbook serve --no-create-file` (the name `--no-create-file` may not be the best). And the mdbook compiler will not create files but raise warnings in the command line.

### Version

```text
mdbook v0.4.40
```

**Comment by ehuss** [comment]
Set `build.create-missing=false`, see [build options](https://rust-lang.github.io/mdBook/format/configuration/general.html#build-options).

**Comment by Social-Mean** [comment]
@ehuss 
Perfect！Thanks a lot.
