### ISSUE TITLE
Small options for creating interactive fictions

### ISSUE THREAD

**Issue by ravaq** [rust-lang/mdBook#2417]
### Problem

Hi, and thanks for awesome mdBook,
If there was an option to disable page navigation arrows and contents list in book.toml, it could be used to create simple interactive fiction.

**Comment by ehuss** [comment]
There are no direct options for that. You might be able to override index.hbs (via the theme) to customize the layout of the page. Otherwise, this seems out of scope for this tool, thanks for the suggestion, though!

**Comment by ravaq** [comment]
> There are no direct options for that. You might be able to override index.hbs (via the theme) to customize the layout of the page. Otherwise, this seems out of scope for this tool, thanks for the suggestion, though!

Why not? By adding some simple options mdBook can be used as a 'common markdown to site', not only a 'help maker'.
