### ISSUE TITLE
mdBook x PyOdide: How to make Python code snippets run using pyodide?

### ISSUE THREAD

**Issue by jymchng** [rust-lang/mdBook#2426]
### Question

Hi,

Thank you for your hard work this. It is a lovely piece of work.

Can you point me to how I can possibly tweak to get runnable code snippets using pyodide?

Pyodide is a wasm binary that is compiled from CPython and is capable of running many Python codes within the browser.

**Comment by ehuss** [comment]
Hi! Unfortunately other languages aren't supported at this time. You may be able to hack something in with a custom theme (such as writing some custom javascript code which adds the relevant buttons and code to the code blocks).

Closing in favor of #350 which is the general issue for supporting other languages.
