### ISSUE TITLE
Is there a way to force horizontal rules under headings while generating the book?

### ISSUE THREAD

**Issue by ksd3** [rust-lang/mdBook#2427]
### Question

I'm sure this is a simple modification, but I was wondering if there was a way to explicitly force mdbook to add horizontal rules underneath headings without the user having to put them in explicitly. I'm getting annoyed looking at the double lines and want the nice horizontal line under Test Header 1 in the generated webpage.

For example, this is what I currently have (some information censored) in a VSCode preview

![image](https://github.com/user-attachments/assets/e3ab7417-391a-441f-9cc1-cbabf4edf6d5)

but this is what it looks like in the actual generated book:
![image](https://github.com/user-attachments/assets/be823f01-379b-4450-9ade-ef942fc24a1e)

### Version

```text
mdbook v0.4.40
```

**Comment by ehuss** [comment]
I would suggest using CSS to style your headings as you desire.

**Comment by ksd3** [comment]
Thanks. If anyone has the same problem in the future, the solution is as follows:

1. Create a file in your mdbook directory called 'myfile.css', and put your css in.
2. In ``book.toml`` add the following:
```
[output.html]
additional-css = ["myfile.css"]
```

This is obvious but it is somewhat difficult to find in the documentation.
