### ISSUE TITLE
Implement auto dark mode in CSS

### ISSUE THREAD

**Issue by atjn** [rust-lang/mdBook#2440]
### Problem

Currently, the page will load with a default light style, then JS will take over and if it detects that it is in "auto theme" mode and that the browser is in dark mode, it replaces the light colors with dark colors. This causes a few problems:

- If the internet connection is slow, the page will display the light colors first, destroying the dark mode user's eyes.
- If the user has JS disabled or if it breaks in any way, they will never be able to have dark mode support.

### Proposed Solution

You can use CSS media queries to perform the dark mode check inside the CSS.

### Notes

Related: #1504

**Comment by atjn** [comment]
This was apparently already implemented in #1069 but has regressed since then. I plan on submitting a bug fix soon.

**Comment by ehuss** [comment]
I'm going to close as I *think* this should be resolved by #2454.
