### ISSUE TITLE
No theme selector when page is deployed

### ISSUE THREAD

**Issue by StefanSalewski** [rust-lang/mdBook#2449]
### Problem

This is for mdbook  0.4.40 installed with Gentoo package manager.

Unfortunately I do not know how exactly that tool is called, that opens the pulldown menu where we then can select various themes -- which made Google search about this issue a bit difficult.

But you can see it in action at https://stefansalewski.github.io/rust_for_c_programmers/ where is only the plain white default them available.

Yesterday, I manage after more than one hour with try and error to deploy the book draft to github pages following the guide in the mdbook wiki. First gh-pages was always displaying the main branch, but somehow I managed to make it display the gh-pages branch.

But now there is no theme choice, and I would really prefer a dark theme.

Some experiments tough me, that theming works when the book folder is contained in the parent directory with original name, which is rust_for_c_programmers in my case.  Then I can call "firefox book/index.html" and get the page with theming. But when I do cp -r book /tmp and then firefox /tmp/book/index.html I get only the default white them without theme selector.

I have no real idea for the reason or how to fix that. I could deploy the book to my own homepage, I think I will have the same issue. Because the index.html file always has to be located in some toplevel directory, so it makes no sense to copy the full rust_for_c_programmers to my internet providers space.

I will do some more experiments -- but maybe someone known the reason already?

**Comment by StefanSalewski** [comment]
The good news is, that for a fresh created default book all seems to work:

mkdir mymdbooktest
cd mymdbooktest
mdbook init
mdbook build
cp -r book /tmp/book/
firefox /tmp/book/index.html

I will check if it is somehow related to my book content. Or maybe the reason is, that I just upgraded to latest rust 1.81 and rebuild mdbook? Folder name containing underscores could be a reason as well?

**Comment by StefanSalewski** [comment]
This is an extremely strange bug. Might be related to Firefox.

Firefox somehow stores the selected theme.

The issue seems to only arise when I select a theme in book.toml like

[book]
authors = ["GPT-4, Claude 3.5 Sonnet, Llama 3.1, S. Salewski"]
language = "en"
multilingual = false
src = "src"
title = "Rust for C-Programmers"
[output.html.playground]
editable = true
[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"

With that I get problems even with the mdbook empty default book, when I copy the book folder to /tmp/book7

For my test, without

[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"

it seems always to work fine. I have currently no other web browser installed to test, and I would not like to remove all the Firefox configuration files for now, as that would imply loosing all my bookmarks.

So I will try a real deploy without the theme section now, hoping that it will work.

**Comment by StefanSalewski** [comment]
I got it working without the default theme selection, see

https://rust-for-c-programmers.salewskis.de/

I will let this issue open for some time, perhaps someone has an idea about the issue.

**Comment by ehuss** [comment]
> default-theme = "dark"

Have you added a new theme called "dark"? If not, this is likely the issue. The theme name needs to match one of the available themes.

**Comment by StefanSalewski** [comment]
Oh. I have not found a detailed listing of the available themes in the mdbook documentation, but was quite sure "dark" is valid -- I think because I read somewhere that "light" is the default. And during testing, before deploying, I used "mdbook serve --open" which was working fine, so I forgot about this detail. Can you tell me what possible options in book.toml are to get a dark default instead of my current

[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"

In any case, it would be good if mdbook would give an error message for invalid entries in book.toml.

Best regards,

Dr. Stefan Salewski

**Comment by StefanSalewski** [comment]
OK, I think I can close this issue. I would like to delete the github page linked at the top, I think it is not needed any longer as the reason for this issue is now clear. I will delete that github page in a few hours, and might use it then for hosting the book source code.
