### ISSUE TITLE
Big < > buttons at the bottom by incident

### ISSUE THREAD

**Issue by StefanSalewski** [rust-lang/mdBook#2457]
### Question

Typically there are no "back" and "forward" button at the bottom of pages.

Due to a silly mistake, I just found out that we get these buttons, when the source text ends with

```
Understanding traits, generics, and lifetimes is crucial for mastering Rust, but they can be challenging concepts, especially since many other programming languages do not have direct equivalents. In this chapter, we'll delve deeply into these topics, explaining how they interact and how to use them effectively in your Rust programs.

<!---


```

See https://rust-for-c-programmers.salewskis.de/ch11/chapter_11_traits_generics_and_lifetimes.html

Is this a special annotation? I have not seen that in the manual?

Another idea I recently had: It would be very nice, if code examples would have a button which copies the code directly to the Rust playground and opens the playground page immediately. Of course we can always copy the code, move to the playground tab, and paste it. But just one action instead of three would be nice if that is technically possible.

**Comment by Pistonight** [comment]
Not a maintainer, but it looks like those buttons are intended for mobile navigation, and `<!--` starts a comment, so this is an injection "attack"

**Comment by StefanSalewski** [comment]
Thanks for you explanation.

I did a Google search myself yesterday, and also consulted the mdbook documentation. But I found nothing, so I think this is not a new mdbook feature.

Unfortunately the above link points to actual used content, so I can not use it for a longer time period just to demonstrate this issue.
