### ISSUE TITLE
Support Djot

### ISSUE THREAD

**Issue by dcampbell24** [rust-lang/mdBook#2460]
### Problem

It would be nice if you could write [Djot](https://djot.net/) files. There currently is a [library](https://github.com/hellux/jotdown) supporting Djot.

### Proposed Solution

This would work by files ending in `.md` are Markdown and files ending in `.dj` are Djot. The Djot files would be parsed into html by Jotdown. Otherwise, Djot files would be handled the same as Markdown files.

**Comment by Dylan-DPC** [comment]
Thanks for creating the issue. A mdbook plugin might be a better option for this than supporting it out of the box at the moment as this does sound niche.

**Comment by dcampbell24** [comment]
What do you mean by a plugin? Do you mean make it an optional feature?

**Comment by dcampbell24** [comment]
Alright, I made a plugin:  https://github.com/dcampbell24/mdbook-djot.
