### ISSUE TITLE
Broken book; folding sections does not work and certain sections are 404

### ISSUE THREAD

**Issue by hydroperfox** [rust-lang/mdBook#2479]
### Problem

When I set `output.html.fold = { enable= true }`, my documentation's expand buttons do not expand (always collapsed), and I have broken sections now leading to a 404 error.

### Steps

1. Clone `https://github.com/whackengine/docs`
2. Run `mdbook serve`

### Version

```text
mdbook v0.4.42
```

**Comment by ehuss** [comment]
You will need to update index.hbs with the latest version, since some of the navigation has changed.

**Comment by hydroperfox** [comment]
Right, thanks!
