### ISSUE TITLE
relative links are not correctly working on 0.4.42

### ISSUE THREAD

**Issue by mimoo** [rust-lang/mdBook#2482]
### Problem

we had to downgrade to `mdbook@0.4.40` in order to have relative links work in the rendered html (when we use subfolders in chapters). Version `0.4.42` had this problem:

* imagine you have `./foo/bar.md` and `./foo2/bar2.md` in the summary file
* imagine that in the rendered page you go to is in `/foo/bar/index.html`
* then mdbook usually convert the link in the menu to the other page as `../foo2/bar2/index.html`
* but it doesn't and render it as `foo2/bar2/index.html` (which obv doesn't work)

**Comment by ehuss** [comment]
Sorry, I'm not quite able to follow the reproduction. With those two entries in SUMMARY.md, going to `/foo/bar/index.html` would be a 404. Can you show the exact contents of the `SUMMARY.md` file, and any other relevant source files?

**Comment by mimoo** [comment]
an example would be:

```md
# Summary

- [page1](./page1/index.md)
- [page2](./page2/index.md)
```

if you are on page 1, the link to page 2 is broken and will lead to `page1/page2/index.html`

I can probably produce more logs, but the problem comes from the `mdbook` binary. If we get the version 0.4.42 it doesn't work, but if we install it with `cargo install mdbook@0.4.40` the links are properly rendered

**Comment by ehuss** [comment]
Hm, I'm not able to reproduce that.

Do you maybe have a stale `book` directory that needs to be deleted? Do you have a custom theme or any other custom settings? Which browser/platform are you on?

**Comment by mimoo** [comment]
This was happening to us in cloudflare pages BTW, we didn't try reproducing it locally as downgrading the version fixed the issue. Here are [the logs](https://pastebin.com/z7H1mtJi) so you can see the exact dependency version pulled when doing `cargo install mdbook`. Maybe you can try to reproduce locally with the git commit that is getting pulled in these logs :o 

Or you can just give up if nobody else is seeing this issue. Maybe not worth investigating if nobody else complains about that.

**Comment by ehuss** [comment]
It looks like you have a custom [`index.hbs`](https://github.com/zksecurity/halo2-course/blob/publish/theme/index.hbs). It will need to be updated to the latest version since some of the navigation has changed.

**Comment by mimoo** [comment]
oh I see, thanks so much for taking a look!
