### ISSUE TITLE
Make 404 Page Accessible In Deployments

### ISSUE THREAD

**Issue by dcampbell24** [rust-lang/mdBook#2489]
### Question

I want to automatically run mdBook as a service. What should I make the systemd `.service` file look like? The idea is that I am running the Rust mdBook html server instead of a server like Apache, so I can get the mdBook 404 pages.   

### Version

mdbook v0.4.42

**Comment by dcampbell24** [comment]
Another solution would be to add an option to generate `.htaccess` or similar files for deployment and add docs for deployment. It looks like this was suggested in the [initial 404](https://github.com/rust-lang/mdBook/issues/539) page issue, but then never done.

**Comment by ehuss** [comment]
Can you say more about your use case? The built-in web server should not be used for deployment, only local development.

If you want to add instructions for setting up a service like Apache, that would probably best go on something like [the wiki](https://github.com/rust-lang/mdBook/wiki).

**Comment by dcampbell24** [comment]
I figured out how to get 404 pages working and created a [wiki page](https://github.com/rust-lang/mdBook/wiki/Apache). I also linked to it from the main page.
