### ISSUE TITLE
Import code from codebases

### ISSUE THREAD

**Issue by drdozer** [rust-lang/mdBook#2496]
### Problem

I am sorry if this is already supported and I missed it. I'd like to be able to write my book, and display code blocks or fragments from real source files. Without copy-pasting the code into the book. So by specifying the file it comes from, and some locator information (line number, regex, function name, whatever), ideally some locator that's robust to the source being edited. I need the source to be guaranteed runnable, and keeping code blocks in sync with the code is a PITA. Also, ideally I'd be able to embed output from tests or benchmarks into the book. A sort of half-way house between book + code and a workbook and a literate code-base.

**Comment by ehuss** [comment]
There are several include mechanisms described in https://rust-lang.github.io/mdBook/format/mdbook.html#including-files, which support anchors and hiding.
