### ISSUE TITLE
Option to collapse elements in sidebar

### ISSUE THREAD

**Issue by azerupi** [rust-lang/mdBook#25]
Right now, all the elements of the sidebar are visible at all time. But if you have a large book the sidebar can become very crowded.

An option to collapse the sidebar elements would solve this problem.

There could be a config entry to set the default, but ultimately the end user should be able to decide if it's enabled or not. Therefore it should be done in JS.

**Comment by ehuss** [comment]
I believe this is now implemented by #1027.
