### ISSUE TITLE
`mdbook serve` always rebuilds

### ISSUE THREAD

**Issue by eureka-cpu** [rust-lang/mdBook#2504]
### Question

Is there a way to opt out of the rebuild when serving?

If I've just run `mdbook build` then `mdbook serve` I see that it builds again, but I'd like to avoid that if possible. I wouldn't mind writing a command line flag for opting out, making the default opt-in.

### Version

```text
v0.4.43
```

**Comment by eureka-cpu** [comment]
I see there's some config types, maybe adding an option to `BuildConfig` so that I can declare it would be nice.

The problem I'm running into with this is that the context I've built the mdbook in is read-only and the book is already built, but when I try to serve I have to always override the read-only state so that it will serve. If it isn't strictly necessary to rebuild every time, it would be nice to opt out, or just make the rebuilding smarter so that if the expected contents aren't there only then will it rebuild before serving.

Open to suggestions 🙂

**Comment by ehuss** [comment]
The `mdbook serve` command is only intended to be used for development, and thus needs to build the output. If you need a webserver for serving content, there are many good options out there.
