### ISSUE TITLE
Links not working when placed within a div tag

### ISSUE THREAD

**Issue by jacott** [rust-lang/mdBook#2512]
### Problem

```md
<div>[test](#test)</div>
```

causes the link markdown to be included verbatim. Expected `<a href="#test">test</a>` to be rendered instead.

### Steps

1. Place a div around a markdown paragraph with a markdown link inside.
2. Rendered html is missing link; markdown displayed verbatim instead

### Version

```text
mdbook v0.4.43
```

**Comment by ehuss** [comment]
Thanks for the report! This is intentional behavior. mdbook uses the commonmark spec which specifies that within an [HTML block](https://spec.commonmark.org/0.31.2/#html-blocks), all content inside the block is treated as raw HTML, and will not have markdown processing.
