### ISSUE TITLE
in MathJax, Latex, Double `\underbrace{}_{}` doesn't work

### ISSUE THREAD

**Issue by ManeraKai** [rust-lang/mdBook#2513]
### Problem

Works:
```md
$$ \underbrace{x+y}_{z} $$
```
Doesn't work:
```md
$$ \underbrace{x+y}_{z} + \underbrace{x+y}_{z} $$
```
Also doesn't work:
```md
\\( \underbrace{x+y}_{z} + \underbrace{x+y}_{z} \\)
```

### Notes

I tried this on MathJax's [web demo](https://www.mathjax.org/#demo), it works fine over there.

### Version

```text
mdbook v0.4.43
```

**Comment by ehuss** [comment]
Thanks for the report! You need to escape the underscores because otherwise they are being interpreted as markdown italics.
