### ISSUE TITLE
serve: double reload on backup files deletion

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/mdBook#383]
The problem arises when working with an editor like [Kate](https://kate-editor.org/) which keeps your current edits in a swap file.

When saving the swapped contents to the real file an event occurs and triggers the rebuild of the book.
While the book is building another event occurs because the swap file is deleted. 

On my machine this creates a race. 
Sometimes the second thread is fast enough to delete the folder before the first finishes working and nothing happens.
But around 50% of the time the deletion happens right after the first build finished. This means the browser will receive a reload command at the same time as the second thread starts deleting the files. In that case the browser gets a 404 and the reload function is dead. A manual reload is required now.

I see a probable solution by triggering the rebuild with some delay on the server.
Delaying the client is also possible but the client would either have to poll the server for the file or delay a fixed amount of time.
What do you think?

**Comment by budziq** [comment]
Hi @dns2utf8 thanks for the bug report.
Trying to fix race conditions by sleep tuning is universally a bad idea 😉  . We will most likely need to introduce some synchronization with a command queue

**Comment by dns2utf8** [comment]
Another way to solve this would could be the 404 page. If it had code included for may displaying the index or detect the page beeing served (maybe again). 
This would cover the scenario where the user switched from one branch of the book to another or merges.

**Comment by azerupi** [comment]
Maybe we could add a command line argument to blacklist certain patterns of files, would that help?

**Comment by dns2utf8** [comment]
What if mdbook were to ignore all changes coming from files marked by the `.gitignore` (or similar) file?

**Comment by budziq** [comment]
@dns2utf8 could you look on this PR https://github.com/azerupi/mdBook/pull/427? It solves multiple reloads on my system with vim (using notify crates builtin event aggregation logic which we have circumvented so far). It might not solve your case yet though.

**Comment by azerupi** [comment]
Release 0.0.24 includes the fix from @budziq.
Could anyone try with the new version and see if it fixed the issues?

**Comment by dns2utf8** [comment]
Happy new year everybody. With the latest 0.1.1 release this behavior has become more intrusive. Even though I have this ignore file the reloads get triggerd while I type.
```
book
.DS_Store
.directory
*.kate-swp
```

On my system the actual file does not change while typing, so I get no live preview. The edits go into the `.filename.kate-swp` and I get many rebuilds and reloads without any effect. As soon as I save I get a 404 because in the very moment it builds the original file is removed and then kate moves the swap file to the original location.

**Comment by Michael-F-Bryan** [comment]
I'm looking through the [notify docs] and I don't know if you can give it some sort of ignore pattern. You can unset specific paths, but I'm not sure whether it'll keep ignoring a file once it's been deleted. 

> Even though I have this ignore file the reloads get triggerd while I type.

I don't think we pay any attention to your `.gitignore` at the moment. Instead we'll unconditionally watch everything in your `src/`, as well as the `themes/` directory (if it exists), and `book.toml`. 

[notify docs]: https://docs.rs/notify/4.0.3/notify/trait.Watcher.html

**Comment by dns2utf8** [comment]
I did some work with the `ignore` crate: [see this branch](https://github.com/dns2utf8/mdbook/tree/ignore)
My current problem is new and recreated (unlink + create) files. So I asked on the [issue tracker](https://github.com/BurntSushi/ripgrep/issues/763) but I will have to look at it tomorrow.

**Comment by KFearsoff** [comment]
@rustbot label +C-bug +Command-serve +Command-watch +S-Duplicate

See https://github.com/rust-lang/mdBook/issues/2102#issuecomment-1810982299
