### ISSUE TITLE
Make hiding and showing of setup code in code examples more obvious

### ISSUE THREAD

**Issue by brendanzab** [rust-lang/mdBook#663]
Just came across this [in the Kotlin docs](http://kotlinlang.org/docs/reference/basic-syntax.html) - they let you hide and show the setup code in examples:

![screen shot 2018-04-04 at 12 32 00 pm](https://user-images.githubusercontent.com/695077/38285611-5d7bf6be-3804-11e8-8296-c811b8e8389f.png)
![screen shot 2018-04-04 at 12 32 14 pm](https://user-images.githubusercontent.com/695077/38285615-61c1ef30-3804-11e8-8c86-15f4b166ff55.png)
![screen shot 2018-04-04 at 12 32 21 pm](https://user-images.githubusercontent.com/695077/38285616-63c1e416-3804-11e8-8450-021519fe4485.png)

Very slick!

It seems that instead of the `#` comments [like we currently have for hiding code lines](https://rust-lang-nursery.github.io/mdBook/format/theme/syntax-highlighting.html#hiding-code-lines), they [use special comments](https://github.com/JetBrains/kotlin-web-site/blob/master/pages/docs/reference/basic-syntax.md#defining-functions) to mark the beginning and end of samples:

```kotlin
//sampleStart
fun sum(a: Int, b: Int): Int {
    return a + b
}
//sampleEnd

fun main(args: Array<String>) {
    print("sum of 3 and 5 is ")
    println(sum(3, 5))
}
```

Also note that code is re-indented as necessary:

![screen shot 2018-04-04 at 12 35 28 pm](https://user-images.githubusercontent.com/695077/38285684-bb0b4e42-3804-11e8-82cb-95c39dc79e38.png)
![screen shot 2018-04-04 at 12 35 47 pm](https://user-images.githubusercontent.com/695077/38285687-bdd2f4fe-3804-11e8-80da-502a9207617b.png)

```kotlin
fun main(args: Array<String>) {
    val fruits = listOf("banana", "avocado", "apple", "kiwifruit")
//sampleStart
    fruits
        .filter { it.startsWith("a") }
        .sortedBy { it }
        .map { it.toUpperCase() }
        .forEach { println(it) }
//sampleEnd
}
```

---

**Edit**

I didn't actually realise you could hide/show code in mdBook, but it seems you can! Alas it's hidden behind a non-obvious icon that I interpreted to mean 'fullscreen':

<img width="151" alt="screen shot 2018-04-04 at 9 42 54 pm" src="https://user-images.githubusercontent.com/695077/38306004-618e8cdc-3852-11e8-8119-c22d4871c5c3.png">

Also, the Kotlin examples have a different background behind the setup code in the expanded mode, which is really nice touch. Makes the setup code recede into the background, and you don't have to remember so much what the original example looked like. The is very handy for more involved examples.

**Comment by steveklabnik** [comment]
This already exists today http://rust-lang-nursery.github.io/mdBook/format/mdbook.html#hiding-code-lines

**Comment by steveklabnik** [comment]
Oh, you want a new, additional syntax. Sorry! I missed that.

**Comment by brendanzab** [comment]
Yup, also see how the reader can expand the example to see the setup. This is nice, because the author can focus in on a specific point, while still allowing folks to copy-paste a working thing if they want to.

**Comment by steveklabnik** [comment]
That's already in there today; this would purely be about the new comment style.

**Comment by brendanzab** [comment]
OHH, we're talking about the 'fullscreen' icon here?

<img width="151" alt="screen shot 2018-04-04 at 9 42 54 pm" src="https://user-images.githubusercontent.com/695077/38305720-3a7c18f4-3851-11e8-84cf-3a9b3fc05334.png">

I thought it was a full screen icon, so I never tried clicking on it. Also, it would be nice to have some styling that separated the hidden code from the non-hidden code in the expanded mode. The UX design on the Kotlin docs seems to have been nicely thought through in that respect.

I do understand that there might have been  time and resource allocation constraints when the feature was first added. But yeah, all the more reason to be inspired by other people's good ideas!

**Comment by brendanzab** [comment]
Updated the title and issue description to reflect the discussion!

**Comment by brendanzab** [comment]
I would say that one issue with the `#` syntax is that it's hard to get the indentation right in examples. Also, does Rustdoc fix the indentation of stuff like:

```rust
#fn main() {
    println!("hi");
#}
```

So that it renders like this in the collapsed mode:

```rust
println!("hi");
```

And not this:

```rust
    println!("hi");
```

**Comment by steveklabnik** [comment]
It's too hard to fix in the general case, so we don't deal with indentation at all.

**Comment by onelson** [comment]
Just wanted to echo the sentiment here:

> Alas it's hidden behind a non-obvious icon that I interpreted to mean 'fullscreen':

It took me a long time to notice that icon, then to not dismiss it as something like "open in a new window" or "fullscreen" to the point where I actually hovered over and saw the title.

Sharing the fact this feature exists with others has made me feel popular and smart, but this definitely seems like the icon could be working harder to promote itself.

An "eye" icon in open and closed variants was suggested and makes a lot of sense to me.

**Comment by ashneverdawn** [comment]
Wow just found out about the hidden-code-lines! I think an icon similar to https://image.flaticon.com/icons/png/512/56/56181.png would be more appropriate. 

But yeah, the way it is in the Kotlin docs is really nice! Much more intuitive.

**Comment by ashneverdawn** [comment]
I believe this is what we'd use:
- https://fontawesome.com/v4.7.0/icon/eye-slash
- https://fontawesome.com/v4.7.0/icon/eye
