### ISSUE TITLE
It is the Rust Playground, not the Playpen

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/mdBook#674]
"Playpen" was a very old name for it.

**Comment by pavelrappo** [comment]
It would definitely help if someone could describe the relationship between _playground_ and _playpen_.  When reading mdBook documentation it's not clear what the difference is between `{{#playpen}}` and fenced runnable code blocks. Both these types seem to be compiled and executed the same way by the Rust Playground.

**Comment by ehuss** [comment]
`playpen` is just an old name for `playground`, they are one in the same.

`{{#playpen file.rs}}` is identical to:

```markdown
    ```rust
    {{#include file.rs}}
    ```
```

It looks like `{{#playpen}}` predates `{{#include}}`.  Probably not a super-strong reason to have both.

**Comment by pavelrappo** [comment]
I do like it as a metaphor, though. Kids go outside of their house to get to a  playground. Toddlers stay inside and play in a playpen.

`mdBook` sends the snippets for compilation and execution, receives the results, and shows them in-place. Whereas `rustdoc` opens a new tab with your code copied to the playground.

Hope that makes sense.

**Comment by shepmaster** [comment]
My original idea when opening this issue is that anything public-facing in mdBook be updated to use the term "playground". This *probably* would have backwards-compatibility effects, so I'd expect that `playpen` in code would stay around as aliases to the newly-renamed thing. Thus `#playpen` and `#playground` would do the same, but in all the docs it would only say "playground".

It's a low-priority change, but one that might be more valuable before more people are introduced to mdBook.

**Comment by pavelrappo** [comment]
Right. Being consistent and expanding vocabulary only if absolutely necessary are good goals. Rustdoc seems to be using the word "playground", so one more reason for mdBook to use that instead of "playpen".
