### ISSUE TITLE
Spacers in sidebar don't appear at correct level

### ISSUE THREAD

**Issue by mattico** [rust-lang/mdBook#733]
For example, [the spacer in SUMMARY.md](https://github.com/rust-lang-nursery/mdBook/blob/master/book-example/src/SUMMARY.md#L25) is placed inside the subsection list, when it should be top-level:

![image](https://user-images.githubusercontent.com/853158/43154592-79612ed4-8f3a-11e8-86a1-bc66b67e97c6.png)

**Comment by mickvangelderen** [comment]
Just noticed this. Still happening.

**Comment by ehuss** [comment]
Copying my comment from #1730:

I suspect it would be around [here](https://github.com/rust-lang/mdBook/blob/0ec4b692f49b11d961e740e1ed14c4507d48621d/src/renderer/html_handlebars/helpers/toc.rs#L63-L67), where it uses an `<li>` for the spacer.  Perhaps it could use a different tag, like `<hr>`? However, this would need careful consideration of how it will change existing users, and whether or not it will affect their expected rendering.
