### ISSUE TITLE
Add link to mdbook user guide website to repository website section

### ISSUE THREAD

**Issue by chinedufn** [rust-lang/mdBook#775]
I always come here and have to scroll to find the link that I'm looking for - so this would help!

![image](https://user-images.githubusercontent.com/2099811/44786357-d6e04700-ab61-11e8-8a38-887a116c1d78.png)

https://rust-lang-nursery.github.io/mdBook/

**Comment by rbuckland** [comment]
👍 Yes - this should be simple. Could you do this please @mattico  and close this ticket.

**Comment by mattico** [comment]
Unfortunately I don't have write access to that. Not sure how github permissions work... maybe @steveklabnik  can help 😃.

**Comment by nikomatsakis** [comment]
Done!
