### ISSUE TITLE
editions support for mdbook test

### ISSUE THREAD

**Issue by vorner** [rust-lang/mdBook#812]
Hello

I can't find a way to turn on the 2018 edition in `mdbook test`. I guess this is more of a documentation issue, because after all, there's the 2018 edition of The Book, so it must work somehow. But some kind of option somewhere or explanation how to do that in docs would be nice.

**Comment by steveklabnik** [comment]
Mdbook calls out to rustdoc, which supports “edition2018” and “edition2015” as a modifier to the triple backtick code blocks.

**Comment by tkaitchuck** [comment]
It would be useful to have a config option to set a default. That would avoid having to type it every time, and prevent the loss of syntax highlighting within the IDE.

**Comment by kpp** [comment]
@steveklabnik Looks like `edition2018` is ignored by rustdoc.

src/chapter_1.md:

    # Chapter 1
    
    ```edition2018
    async fn hello() {}
    fn main() {
        assert_eq!(1, 2);
    }
    ```

```
$ rustdoc --test src/chapter_1.md 

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

However with:


    ```rust
    async fn hello() {}
    fn main() {
        assert_eq!(1, 2);
    }
    ```

Works as expected:

```
$ rustdoc --edition 2018 --test src/chapter_1.md 

running 1 test
test src/chapter_1.md - Chapter_1 (line 4) ... FAILED

failures:

---- src/chapter_1.md - Chapter_1 (line 4) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/chapter_1.md:4:5
```

**Comment by ehuss** [comment]
Yea, this was just recently discovered.  There is a PR (https://github.com/rust-lang/rust/pull/66238) to fix that.

**Comment by kpp** [comment]
How about adding `edition=2018` option to mdbook config?

**Comment by ehuss** [comment]
> How about adding `edition=2018` option to mdbook config?

There was a recent PR to add that (#1086), but it had a problem so had to be reverted. I'm looking at fixing it, but I wanted to change how the config was defined.  It's near the top of my list, so hopefully soon!
