### ISSUE TITLE
Mobile - Remove the CSS sidebar

### ISSUE THREAD

**Issue by travankor** [rust-lang/mdBook#859]
I usually browse things on my mobile phone without javascript, since javascript eats my phone's battery life (thanks advertising/analytics companies?).

mdBook generally works well on mobile w/o JS, except for the large CSS sidebar that takes up half of my phone's screen. Instead of trying to auto-hide the sidebar using JS, could there be a better way to integrate the sidebar? FWIW, mkdocs does not have this issue.

I know this is a somewhat niche case, but it would be great to not have to enable JS just to read simple markdown.

**Comment by zcdunn** [comment]
I would be in favor of a CSS solution, too, even though I don't disable JS. Less JS is always a good thing and the current JS sidebar is finicky on mobile.

**Comment by Dylan-DPC** [comment]
@travankor is it possible to send a PR that makes this change? thanks
