### ISSUE TITLE
How implement rtl

### ISSUE THREAD

**Issue by mhf-ir** [rust-lang/mdBook#921]
How implement rtl languages?

Or in rtl pages scope with ltr, or in ltr page rtl section?

https://mhf-ir.github.io/i18nplease/

**Comment by zzy** [comment]
Hi, gay, do you mean this?

1. mdbook init --theme rtltest;
2. edit src/theme/index.hbs
`<html lang="{{ language }}" class="sidebar-visible no-js" dir="rtl">`
3. It's look like all pages are rtl style.

**Comment by Hitaro** [comment]
where the rtl.css should be located? Does _mdbook_ have any support for custom css files, something like this:

![Untitled](https://user-images.githubusercontent.com/18015032/79603349-7076b680-8101-11ea-8ffe-04dc1202bd5a.png)

**Comment by netlander** [comment]
Interested in RTL feature, anyone found a good solution?

**Comment by Hitaro** [comment]
@netlander 
- Add `additional-css= ["theme/rtl.css"]` to the _book.toml_
- Create a theme folder inside the root of your book project
- add some css rules into `theme/rtl.css`, for example:

```
body { direction: rtl; }
code { direction: ltr; }
```

Please your css classes here, if you found something.

**Comment by netlander** [comment]
Does this make the nav panel move to the right?

**Comment by EliRenzer** [comment]
this should be done in html and not css, read why
https://www.w3.org/International/questions/qa-bidi-css-markup

so better edit index.hbs.. probably

>  [@netlander] Does this make the nav panel move to the right?
 no only text aligned to right

**Comment by mgeisler** [comment]
This was implemented in https://github.com/rust-lang/mdBook/pull/1641, yet to be released :rocket: 

We've testing the PR for a Persian translation of Comprehensive Rust: https://google.github.io/comprehensive-rust/fa/.

**Comment by ehuss** [comment]
Indeed, it looks like this can be closed, thanks!
