### ISSUE TITLE
I don't need offline mode, how should I config?

### ISSUE THREAD

**Issue by alexwanng** [rust-lang/mdBook#974]
I have lots of files on my mdbook , so now it appears an WARN:
```
(mdbook::renderer::html_handlebars::search): searchindex.json is very large (18430984 bytes)
```
and I cann't load my page from browser.

So, I'd like to remove offline model, how should I do?

Thanks.

**Comment by ehuss** [comment]
I'm not sure what you mean by "offline", but you can disable the search with the following in `book.toml`:

```toml
[output.html.search]
enable = false
```

**Comment by sanmai-NL** [comment]
It seems this can be closed, @alexwanng?
