### ISSUE TITLE
[Tracking issue] sccache no longer work in nightly CI

### ISSUE THREAD

**Issue by tesuji** [rust-lang/mdBook#995]
Waiting for https://github.com/mozilla/sccache/issues/488.

**Comment by lzutao** [comment]
mozilla/sccache#488 fixed. Waiting for new sccache release.

**Comment by Dylan-DPC** [comment]
@lzutao scache has released a new version, CI looks fine, anything else?

**Comment by lzutao** [comment]
I am thinking about caching target/ dir instead of using sccache. Will try a look and
investigate it later.

**Comment by lzutao** [comment]
Now we moved to GitHub actions, but the CI provider hasn't supported caching yet. We could close thi

**Comment by ehuss** [comment]
I'm going to close, as I probably won't be adding CI caching back in the foreseeable future.
